(function(b,c){"function"===typeof define&&define.amd?define(["exports"],c):"object"===typeof exports?c(exports):c(b)})(this,function(b){if(!b.Promise){var c=function(a){this._state=0;this._timeout=this._value=null;this._cb={fulfilled:[],rejected:[]};this._thenPromises=[];a&&this._invokeResolver(a)};c.resolve=function(a){return new this(function(d,b){d(a)})};c.reject=function(a){return new this(function(d,b){b(a)})};c.all=c.when=function(a){return new this(function(d,b){var c=0,h=[];a.forEach(function(a,
k){c++;a.then(function(a){h[k]=a;c--;c||d(h)},function(a){c=1/0;b(a)})})})};c.race=function(a){return new this(function(d,b){a.forEach(function(a){a.then(d,b)})})};c.prototype.then=function(a,d){this._cb.fulfilled.push(a);this._cb.rejected.push(d);var b=new c;this._thenPromises.push(b);0<this._state&&this._schedule();return b};c.prototype.fulfill=function(a){if(0!=this._state)return this;this._state=1;this._value=a;this._thenPromises.length&&this._schedule();return this};c.prototype.reject=function(a){if(0!=
this._state)return this;this._state=2;this._value=a;this._thenPromises.length&&this._schedule();return this};c.prototype.resolve=function(a){if(a==this)this.reject(new TypeError("Promise resolved by its own instance"));else if(a instanceof this.constructor)a.chain(this);else if(null===a||"object"!=typeof a&&"function"!=typeof a)this.fulfill(a);else{try{var d=a.then}catch(b){this.reject(b);return}if("function"==typeof d){var c=!1,h=function(a){c||(c=!0,this.resolve(a))},f=function(a){c||(c=!0,this.reject(a))};
try{d.call(a,h.bind(this),f.bind(this))}catch(k){c||this.reject(k)}}else this.fulfill(a)}};c.prototype.chain=function(a){return this.then(function(d){a.resolve(d)},function(d){a.reject(d)})};c.prototype["catch"]=function(a){return this.then(null,a)};c.prototype._schedule=function(){this._timeout||(this._timeout=setTimeout(this._processQueue.bind(this),0))};c.prototype._processQueue=function(){for(this._timeout=null;this._thenPromises.length;){var a=this._cb.fulfilled.shift(),d=this._cb.rejected.shift();
this._executeCallback(1==this._state?a:d)}};c.prototype._executeCallback=function(a){var d=this._thenPromises.shift();if("function"!=typeof a)1==this._state?d.fulfill(this._value):d.reject(this._value);else try{var b=a(this._value);d.resolve(b)}catch(c){d.reject(c)}};c.prototype._invokeResolver=function(a){try{a(this.resolve.bind(this),this.reject.bind(this))}catch(d){this.reject(d)}};b.Promise=c}});
(function(b,c){"function"==typeof define&&define.amd?define(["exports"],c):"object"==typeof exports?c(exports):c(b)})(this,function(b){if(!b.GLMath){var c={vec3cross:function(a,d){return[a[1]*d[2]-a[2]*d[1],a[2]*d[0]-a[0]*d[2],a[0]*d[1]-a[1]*d[0]]},vec3dot:function(a,d){return a[0]*d[0]+a[1]*d[1]+a[2]*d[2]},vec3add:function(a,d){return[a[0]+d[0],a[1]+d[1],a[2]+d[2]]},vec3sub:function(a,d){return[a[0]-d[0],a[1]-d[1],a[2]-d[2]]},vec3addInPlace:function(a,d){var b=d[1],c=d[2];a[0]+=d[0];a[1]+=b;a[2]+=
c;return a},vec3subInPlace:function(a,d){var b=d[1],c=d[2];a[0]-=d[0];a[1]-=b;a[2]-=c;return a},vec3mulInPlace:function(a,d){var b=d[1],c=d[2];a[0]*=d[0];a[1]*=b;a[2]*=c;return a},vec3scaleInPlace:function(a,d){a[0]*=d;a[1]*=d;a[2]*=d;return a},vec3scale:function(a,d){return c.vec3scaleInPlace([a[0],a[1],a[2]],d)},vec3lerp:function(a,d,b){return[a[0]+(d[0]-a[0])*b,a[1]+(d[1]-a[1])*b,a[2]+(d[2]-a[2])*b]},vec4dot:function(a,d){return a[0]*d[0]+a[1]*d[1]+a[2]*d[2]+a[3]*d[3]},vec4scaleInPlace:function(a,
d){a[0]*=d;a[1]*=d;a[2]*=d;a[3]*=d;return a},vec4lerp:function(a,d,b){return[a[0]+(d[0]-a[0])*b,a[1]+(d[1]-a[1])*b,a[2]+(d[2]-a[2])*b,a[3]+(d[3]-a[3])*b]},vec3normInPlace:function(a){var d=a[0],b=a[1],c=a[2];len=Math.sqrt(d*d+b*b+c*c);0!=len&&(len=1/len,a[0]*=len,a[1]*=len,a[2]*=len);return a},vec4normInPlace:function(a){var d=a[0],b=a[1],c=a[2],h=a[3];len=Math.sqrt(d*d+b*b+c*c+h*h);0!=len&&(len=1/len,a[0]*=len,a[1]*=len,a[2]*=len,a[3]*=len);return a},vec3norm:function(a){return c.vec3normInPlace([a[0],
a[1],a[2]])},vec4norm:function(a){return c.vec4normInPlace([a[0],a[1],a[2],a[3]])},vec3length:function(a){var d=a[0],b=a[1];a=a[2];return Math.sqrt(d*d+b*b+a*a)},vec4length:function(a){var d=a[0],b=a[1],c=a[2];a=a[3];return Math.sqrt(d*d+b*b+c*c+a*a)},mat3identity:function(){return[1,0,0,0,1,0,0,0,1]},mat4identity:function(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]},quatIdentity:function(){return[0,0,0,1]},mat4copy:function(a){return a.slice(0,16)},vec3copy:function(a){return a.slice(0,3)},vec4copy:function(a){return a.slice(0,
4)},vec3assign:function(a,d){a[0]=d[0];a[1]=d[1];a[2]=d[2];return a},vec4assign:function(a,d){a[0]=d[0];a[1]=d[1];a[2]=d[2];a[3]=d[3];return a},mat4isIdentity:function(a){return 1==a[0]&&0==a[1]&&0==a[2]&&0==a[3]&&0==a[4]&&1==a[5]&&0==a[6]&&0==a[7]&&0==a[8]&&0==a[9]&&1==a[10]&&0==a[11]&&0==a[12]&&0==a[13]&&0==a[14]&&1==a[15]},mat4invert:function(a){var d=a[0]*a[10],b=a[0]*a[11],g=a[0]*a[5],h=a[0]*a[6],f=a[0]*a[7],k=a[0]*a[9],l=a[10]*a[12],n=a[10]*a[13],p=a[10]*a[15],m=a[11]*a[12],q=a[11]*a[13],r=
a[11]*a[14],v=a[1]*a[4],w=a[1]*a[6],x=a[1]*a[7],H=a[1]*a[8],B=a[2]*a[4],D=a[2]*a[5],A=a[2]*a[7],K=a[2]*a[8],y=a[2]*a[9],t=a[3]*a[4],C=a[3]*a[5],I=a[3]*a[6],L=a[3]*a[8],F=a[3]*a[9],O=a[4]*a[9],P=a[5]*a[8],N=a[6]*a[8],Q=a[6]*a[9],G=a[7]*a[8],M=a[7]*a[9],E=v-g,J=w-D,R=x-C,S=B-h,g=g-v,w=D-w,D=A-I,v=t-f,x=C-x,A=I-A,h=h-B,B=f-t,f=a[9]*a[12]*A+l*R+m*w+a[8]*a[13]*D+n*v+q*h+a[8]*a[14]*x+a[9]*a[14]*B+r*E+a[8]*a[15]*J+a[9]*a[15]*S+p*g;if(0==f)return c.mat4identity();f=1/f;t=[];t[0]=a[6]*q-a[7]*n+M*a[14]-a[5]*
r-Q*a[15]+a[5]*p;t[1]=a[3]*n-a[2]*q-F*a[14]+a[1]*r+y*a[15]-a[1]*p;t[2]=a[13]*D+a[14]*x+a[15]*J;t[3]=a[9]*A+a[10]*R+a[11]*w;t[4]=a[7]*l-a[6]*m-G*a[14]+a[4]*r+N*a[15]-a[4]*p;t[5]=a[2]*m-a[3]*l+a[14]*(L-b)+a[15]*(d-K);t[6]=a[12]*A+a[14]*B+a[15]*S;t[7]=a[8]*D+a[10]*v+a[11]*h;t[8]=a[5]*m-M*a[12]+G*a[13]-a[4]*q+a[15]*(O-P);t[9]=F*a[12]-a[1]*m+a[13]*(b-L)+a[15]*(H-k);t[10]=a[12]*R+a[13]*v+a[15]*g;t[11]=a[8]*x+a[9]*B+a[11]*E;t[12]=Q*a[12]-a[5]*l-N*a[13]+a[4]*n+a[14]*(P-O);t[13]=a[1]*l-y*a[12]+a[13]*(K-d)+
a[14]*(k-H);t[14]=a[12]*w+a[13]*h+a[14]*E;t[15]=a[8]*J+a[9]*S+a[10]*g;for(a=0;16>a;a++)t[a]*=f;return t},quatConjugate:function(a){return[-a[0],-a[1],-a[2],a[3]]},quatInvert:function(a){var d=1/c.quatDot(a,a);return c.vec4scaleInPlace(c.quatConjugate(a),d)},quatInverse:function(a){return c.quatNormInPlace(c.quatConjugate(a))},quatIsIdentity:function(a){return 0==a[0]&&0==a[1]&&0==a[2]&&1==a[3]},quatToMat4:function(a){var d,b,c,h,f,k,l,n,p;d=2*a[0];b=2*a[1];c=2*a[2];h=d*a[0];f=d*a[1];k=d*a[2];l=b*
a[1];n=c*a[1];p=c*a[2];d*=a[3];b*=a[3];a=c*a[3];return[1-(l+p),f+a,k-b,0,f-a,1-(h+p),n+d,0,k+b,n-d,1-(h+l),0,0,0,0,1]},quatToAxisAngle:function(a){var d=a[3],b=1-d*d;return 0<b?(b=1/Math.sqrt(b),[a[0]*b,a[1]*b,a[2]*b,Math.acos(d)*c.Num360DividedByPi]):[0,1,0,0]},quatFromVectors:function(a,d){var b=c.vec3cross(a,d),g=Math.sqrt(c.vec3dot(a,a))*Math.sqrt(c.vec3dot(d,d));0==g&&(g=1);b[3]=g+c.vec3dot(a,d);return c.quatNormInPlace(b)},quatFromAxisAngle:function(a,d,b,g){var h;"undefined"!=typeof b&&"undefined"!=
typeof g?(h=d,d=g):"undefined"==typeof d?(h=a[0],b=a[1],d=a[2]):(h=d[0],b=d[1],d=d[2]);g=(0<=a&&360>a?a:a%360+(0>a?360:0))*c.PiDividedBy360;a=Math.cos(g);g=Math.sin(g);h=c.vec3normInPlace([h,b,d]);h=[h[0],h[1],h[2],a];h[0]*=g;h[1]*=g;h[2]*=g;return h},quatFromTaitBryan:function(a,d,b,g){var h,f;null==g&&(g=c.RollPitchYaw);if(0>g||6<=g)throw Error("invalid mode");a.constructor==Array?(b=(0<=a[2]&&360>a[2]?a[2]:a[2]%360+(0>a[2]?360:0))*c.PiDividedBy360,h=(0<=a[0]&&360>a[0]?a[0]:a[0]%360+(0>a[0]?360:
0))*c.PiDividedBy360,f=(0<=a[1]&&360>a[1]?a[1]:a[1]%360+(0>a[1]?360:0))*c.PiDividedBy360):(b=(0<=b&&360>b?b:b%360+(0>b?360:0))*c.PiDividedBy360,h=(0<=a&&360>a?a:a%360+(0>a?360:0))*c.PiDividedBy360,f=(0<=d&&360>d?d:d%360+(0>d?360:0))*c.PiDividedBy360);a=Math.sin(h);h=Math.cos(h);d=Math.sin(f);f=Math.cos(f);var k=Math.sin(b);b=Math.cos(b);if(g==c.PitchYawRoll||g==c.PitchRollYaw){var l=[k*d,b*d,k*f,b*f];g==c.PitchYawRoll&&(l[0]=-l[0]);g=[l[3]*a+l[0]*h,l[1]*h+l[2]*a,l[2]*h-l[1]*a,l[3]*h-l[0]*a]}else g==
c.YawPitchRoll||g==c.YawRollPitch?(l=[b*a,k*a,k*h,b*h],g==c.YawRollPitch&&(l[1]=-l[1]),g=[l[0]*f-l[2]*d,l[3]*d+l[1]*f,l[2]*f+l[0]*d,l[3]*f-l[1]*d]):(l=[f*a,d*h,d*a,f*h],g==c.RollPitchYaw&&(l[2]=-l[2]),g=[l[0]*b+l[1]*k,l[1]*b-l[0]*k,l[3]*k+l[2]*b,l[3]*b-l[2]*k]);return g},quatToTaitBryan:function(a,b){var e=a[3],g,h,f,k=1;null==b&&(b=c.RollPitchYaw);if(0>b||6<=b)throw Error("invalid mode");b==c.RollPitchYaw?(g=a[1],h=a[0],f=a[2],k=-1):b==c.PitchYawRoll?(g=a[2],h=a[1],f=a[0],k=-1):b==c.PitchRollYaw?
(g=a[1],h=a[2],f=a[0]):b==c.YawPitchRoll?(g=a[2],h=a[0],f=a[1]):b==c.YawRollPitch?(g=a[0],h=a[2],f=a[1],k=-1):(g=a[0],h=a[1],f=a[2]);var l=h*h,n=f*f,p=Math.atan2(2*(e*g-k*h*f),1-2*(g*g+l)),m=2*(e*h+k*g*f);1<m&&(m=1);-1>m&&(m=-1);m=Math.asin(m);h=Math.atan2(2*(e*f-k*g*h),1-2*(l+n));p*=c.Num180DividedByPi;m*=c.Num180DividedByPi;h*=c.Num180DividedByPi;if(1E-6>Math.abs(m-90)||1E-6>Math.abs(m+90))h=0,p=Math.atan2(g,e)*c.Num180DividedByPi,isNaN(p)&&(p=0);e=[];b==c.RollPitchYaw?(e[0]=m,e[1]=p,e[2]=h):b==
c.PitchYawRoll?(e[0]=h,e[1]=m,e[2]=p):b==c.PitchRollYaw?(e[0]=h,e[1]=p,e[2]=m):b==c.YawPitchRoll?(e[0]=m,e[1]=h,e[2]=p):b==c.YawRollPitch?(e[0]=p,e[1]=h,e[2]=m):(e[0]=p,e[1]=m,e[2]=h);return e},quatSlerp:function(a,b,e){var g=c.quatDot(a,b),h=b;0>g&&(h=[-b[0],-b[1],-b[2],-b[3]],g=c.quatDot(a,h));b=0;if(-1<g)if(1>g){if(b=Math.acos(g),0==b)return h.slice(0,4)}else return h.slice(0,4);else b=Math.PI;var f=1/Math.sin(b),g=Math.sin((1-e)*b)*f;e=Math.sin(e*b)*f;return[a[0]*g+h[0]*e,a[1]*g+h[1]*e,a[2]*g+
h[2]*e,a[3]*g+h[3]*e]},quatRotate:function(a,b,e,g,h){return c.quatMultiply(a,c.quatFromAxisAngle(b,e,g,h))},quatTransform:function(a,b){var e=c.vec3cross(a,b);e[0]+=b[0]*a[3];e[1]+=b[1]*a[3];e[2]+=b[2]*a[3];var g=c.vec3cross(e,a),h=a[0]*b[0]+a[1]*b[1]+a[2]*b[2];return[a[0]*h+e[0]*a[3]-g[0],a[1]*h+e[1]*a[3]-g[1],a[2]*h+e[2]*a[3]-g[2],1]},quatFromMat4:function(a){var b=[],c=a[1],g=a[2],h=a[4],f=a[6],k=a[8],l=a[9],n=a[0]+a[5]+a[10];0<=n?(a=.5*Math.sqrt(n+1),n=.25/a,b[0]=(f-l)*n,b[1]=(k-g)*n,b[2]=(c-
h)*n,b[3]=a):a[0]>a[5]&&a[0]>a[10]?(a=.5*Math.sqrt(1+a[0]-a[5]-a[10]),n=.25/a,b[0]=a,b[1]=(h+c)*n,b[2]=(g+k)*n,b[3]=(f-l)*n):a[5]>a[10]?(a=.5*Math.sqrt(1+a[5]-a[0]-a[10]),n=.25/a,b[0]=(h+c)*n,b[1]=a,b[2]=(l+f)*n,b[3]=(k-g)*n):(a=.5*Math.sqrt(1+a[10]-a[0]-a[5]),n=.25/a,b[0]=(k+g)*n,b[1]=(l+f)*n,b[2]=a,b[3]=(c-h)*n);return b},mat4toMat3:function(a){return[a[0],a[1],a[2],a[4],a[5],a[6],a[8],a[9],a[10]]},mat4transpose:function(a){return mat4transposeInPlace(a.slice(0,16))},mat4transposeInPlace:function(a){var b=
a[1];a[1]=a[4];a[4]=b;b=a[2];a[2]=a[8];a[8]=b;b=a[3];a[3]=a[12];a[12]=b;b=a[6];a[6]=a[9];a[9]=b;b=a[7];a[7]=a[13];a[13]=b;b=a[11];a[11]=a[14];a[14]=b;return a},mat4inverseTranspose3:function(a){a=[a[0],a[1],a[2],a[4],a[5],a[6],a[8],a[9],a[10]];var b=a[0]*a[4]*a[8]+a[3]*a[7]*a[2]+a[6]*a[1]*a[5]-a[6]*a[4]*a[2]-a[3]*a[1]*a[8]-a[0]*a[7]*a[5];if(0==b)return[1,0,0,0,1,0,0,0,1];b=1/b;return[(-a[5]*a[7]+a[4]*a[8])*b,(a[5]*a[6]-a[3]*a[8])*b,(-a[4]*a[6]+a[3]*a[7])*b,(a[2]*a[7]-a[1]*a[8])*b,(-a[2]*a[6]+a[0]*
a[8])*b,(a[1]*a[6]-a[0]*a[7])*b,(-a[2]*a[4]+a[1]*a[5])*b,(a[2]*a[3]-a[0]*a[5])*b,(-a[1]*a[3]+a[0]*a[4])*b]},mat4scale:function(a,b,c,g){var h;"undefined"!=typeof c&&"undefined"!=typeof g?(h=b,b=g):(h=b[0],c=b[1],b=b[2]);return[a[0]*h,a[1]*h,a[2]*h,a[3]*h,a[4]*c,a[5]*c,a[6]*c,a[7]*c,a[8]*b,a[9]*b,a[10]*b,a[11]*b,a[12],a[13],a[14],a[15]]},mat4scaled:function(a,b,c){return"undefined"!=typeof b&&"undefined"!=typeof c?[a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1]:[a[0],0,0,0,0,a[1],0,0,0,0,a[2],0,0,0,0,1]},mat4transform:function(a,
b,c,g,h){var f;"undefined"!=typeof c&&"undefined"!=typeof g&&"undefined"!=typeof h?(f=b,b=h):(f=b[0],c=b[1],g=b[2],b=b[3]);return[f*a[0]+c*a[4]+g*a[8]+b*a[12],f*a[1]+c*a[5]+g*a[9]+b*a[13],f*a[2]+c*a[6]+g*a[10]+b*a[14],f*a[3]+c*a[7]+g*a[11]+b*a[15]]},mat3transform:function(a,b,c,g){var h;"undefined"!=typeof c&&"undefined"!=typeof g?(h=b,b=g):(h=b[0],c=b[1],b=b[2]);return[h*a[0]+c*a[3]+b*a[6],h*a[1]+c*a[4]+b*a[7],h*a[2]+c*a[5]+b*a[8]]},mat4translated:function(a,b,c){var g;"undefined"!=typeof b&&"undefined"!=
typeof c?(g=a,a=c):(g=a[0],b=a[1],a=a[2]);return[1,0,0,0,0,1,0,0,0,0,1,0,g,b,a,1]},mat4translate:function(a,b,c,g){var h;"undefined"!=typeof c&&"undefined"!=typeof g?(h=b,b=g):(h=b[0],c=b[1],b=b[2]);return[a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],a[11],a[0]*h+a[4]*c+a[8]*b+a[12],a[1]*h+a[5]*c+a[9]*b+a[13],a[2]*h+a[6]*c+a[10]*b+a[14],a[3]*h+a[7]*c+a[11]*b+a[15]]},mat4perspective:function(a,b,e,g){a=1/Math.tan((0<=a&&360>a?a:a%360+(0>a?360:0))*c.PiDividedBy360);var h;h=1/(e-g);return[a/
b,0,0,0,0,a,0,0,0,0,h*(e+g),-1,0,0,h*e*g*2,0]},mat4lookat:function(a,b,e){e||(e=[0,1,0]);b||(b=[0,0,0]);b=[b[0]-a[0],b[1]-a[1],b[2]-a[2]];var g=c.vec3length(b);if(1E-6>g)return c.mat4identity();g=1/g;b[0]*=g;b[1]*=g;b[2]*=g;e=c.vec3norm(e);e=c.vec3cross(b,e);c.vec3normInPlace(e);g=c.vec3cross(e,b);c.vec3normInPlace(g);b[0]=-b[0];b[1]=-b[1];b[2]=-b[2];return[e[0],g[0],b[0],0,e[1],g[1],b[1],0,e[2],g[2],b[2],0,-c.vec3dot(a,e),-c.vec3dot(a,g),-c.vec3dot(a,b),1]},mat4ortho:function(a,b,c,g,h,f){var k=
1/(b-a),l=1/(g-c),n=1/(f-h);return[2*k,0,0,0,0,2*l,0,0,0,0,-2*n,0,-(a+b)*k,-(g+c)*l,-(h+f)*n,1]},mat4perspectiveHorizontal:function(a,b,e,g){a=c.Num360DividedByPi*Math.atan2(Math.tan((0<=a&&360>a?a:a%360+(0>a?360:0))*c.PiDividedBy360),b);return c.mat4perspective(a,b,e,g)},mat4ortho2d:function(a,b,e,g){return c.mat4ortho2d(a,b,e,g,-1,1)},mat4ortho2dAspect:function(a,b,e,g,h){return c.mat4orthoAspect(a,b,e,g,-1,1,h)},mat4orthoAspect:function(a,b,e,g,h,f,k){var l=Math.abs(b-a),n=Math.abs(g-e);k/=l/n;
return 1>k?c.mat4ortho(a,b,e/k,g/k,h,f):c.mat4ortho(a*k,b*k,e,g,h,f)},mat4frustum:function(a,b,c,g,h,f){var k=2*h,l=1/(b-a),n=1/(g-c),p=1/(f-h);return[k*l,0,0,0,0,k*n,0,0,(a+b)*l,(g+c)*n,-(f+h)*p,-1,0,0,-(k*f)*p,0]},mat4scaleInPlace:function(a,b,c,g){var h;"undefined"!=typeof c&&"undefined"!=typeof g?(h=b,b=g):(h=b[0],c=b[1],b=b[2]);a[0]*=h;a[1]*=h;a[2]*=h;a[3]*=h;a[4]*=c;a[5]*=c;a[6]*=c;a[7]*=c;a[8]*=b;a[9]*=b;a[10]*=b;a[11]*=b;return a},mat4multiply:function(a,b){for(var c=[],g=0;16>g;g+=4)for(var h=
0;4>h;h++)c[g+h]=b[g]*a[h]+b[g+1]*a[h+4]+b[g+2]*a[h+8]+b[g+3]*a[h+12];return c},quatMultiply:function(a,b){return[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]+a[1]*b[3]+a[2]*b[0]-a[0]*b[2],a[3]*b[2]+a[2]*b[3]+a[0]*b[1]-a[1]*b[0],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]]},mat4rotate:function(a,b,e,g,h){var f,k;"undefined"!=typeof g&&"undefined"!=typeof h?(f=e,k=g,e=h,h=(0<=b&&360>b?b:b%360+(0>b?360:0))*c.PiDividedBy180):"undefined"==typeof e?(f=b[0],k=b[1],e=b[2],h=b[3],h=(0<=h&&360>h?h:h%360+
(0>h?360:0))*c.PiDividedBy180):(f=e[0],k=e[1],e=e[2],h=(0<=b&&360>b?b:b%360+(0>b?360:0))*c.PiDividedBy180);b=Math.cos(h);var l=Math.sin(h);if(1==f&&0==k&&0==e)return[a[0],a[1],a[2],a[3],b*a[4]+a[8]*l,b*a[5]+a[9]*l,b*a[6]+a[10]*l,b*a[7]+a[11]*l,b*a[8]-l*a[4],b*a[9]-l*a[5],b*a[10]-l*a[6],b*a[11]-l*a[7],a[12],a[13],a[14],a[15]];if(0==f&&1==k&&0==e)return[b*a[0]-l*a[8],b*a[1]-l*a[9],b*a[2]-l*a[10],b*a[3]-l*a[11],a[4],a[5],a[6],a[7],b*a[8]+a[0]*l,b*a[9]+a[1]*l,b*a[10]+a[2]*l,b*a[11]+a[3]*l,a[12],a[13],
a[14],a[15]];if(0==f&&0==k&&1==e)return[b*a[0]+a[4]*l,b*a[1]+a[5]*l,b*a[2]+a[6]*l,b*a[3]+a[7]*l,b*a[4]-l*a[0],b*a[5]-l*a[1],b*a[6]-l*a[2],b*a[7]-l*a[3],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15]];if(0==f&&0==k&&0==e)return a.slice(0,16);h=1/Math.sqrt(f*f+k*k+e*e);f*=h;k*=h;e*=h;var n=k*k;g=1-b;var p=f*k,m=k*e;h=f*l;k*=l;var q=e*l,l=g*m,r=g*p,v=g*f*e;f=b+g*f*f;p=r+q;m=v-k;n=b+g*n;q=r-q;r=l+h;e=b+g*e*e;b=v+k;h=l-h;return[a[0]*f+a[4]*p+a[8]*m,a[1]*f+a[5]*p+a[9]*m,a[10]*m+a[2]*f+a[6]*p,a[11]*m+a[3]*
f+a[7]*p,a[0]*q+a[4]*n+a[8]*r,a[1]*q+a[5]*n+a[9]*r,a[10]*r+a[2]*q+a[6]*n,a[11]*r+a[3]*q+a[7]*n,a[0]*b+a[4]*h+a[8]*e,a[1]*b+a[5]*h+a[9]*e,a[10]*e+a[2]*b+a[6]*h,a[11]*e+a[3]*b+a[7]*h,a[12],a[13],a[14],a[15]]},mat4rotated:function(a,b,e,g){var h;"undefined"!=typeof e&&"undefined"!=typeof g?(h=b,b=g,g=(0<=a&&360>a?a:a%360+(0>a?360:0))*c.PiDividedBy180):"undefined"==typeof b?(h=a[0],e=a[1],b=a[2],g=a[3],g=(0<=g&&360>g?g:g%360+(0>g?360:0))*c.PiDividedBy180):(h=b[0],e=b[1],b=b[2],g=(0<=a&&360>a?a:a%360+
(0>a?360:0))*c.PiDividedBy180);a=Math.cos(g);var f=Math.sin(g);if(1==h&&0==e&&0==b)return[1,0,0,0,0,a,f,0,0,-f,a,0,0,0,0,1];if(0==h&&1==e&&0==b)return[a,0,-f,0,0,1,0,0,f,0,a,0,0,0,0,1];if(0==h&&0==e&&1==b)return[a,f,0,0,-f,a,0,0,0,0,1,0,0,0,0,1];if(0==h&&0==e&&0==b)return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];g=1/Math.sqrt(h*h+e*e+b*b);h*=g;e*=g;b*=g;g=h*h;var k=e*e,l=b*b,n=h*b,p=e*b,m=h*f,q=e*f,f=b*f,r=1-a;h=r*h*e;e=r*n;b=r*p;return[a+r*g,h+f,e-q,0,h-f,a+r*k,b+m,0,e+q,b-m,a+r*l,0,0,0,0,1]}};c.quatDot=
c.vec4dot;c.quatNormInPlace=c.vec4normInPlace;c.quatNorm=c.vec4norm;c.quatLength=c.vec4length;c.quatScaleInPlace=c.vec4scaleInPlace;c.quatCopy=c.vec4copy;c.PiTimes2=6.283185307179586;c.HalfPi=1.5707963267948966;c.PiDividedBy180=.017453292519943295;c.PiDividedBy360=.008726646259971648;c.Num360DividedByPi=114.59155902616465;c.Num180DividedByPi=57.29577951308232;c.PitchYawRoll=0;c.PitchRollYaw=1;c.YawPitchRoll=2;c.YawRollPitch=3;c.RollPitchYaw=4;c.RollYawPitch=5;c.quatToEuler=c.quatToTaitBryan;c.quatFromEuler=
c.quatFromTaitBryan;b.GLMath=c}});
(function(b,c){"function"===typeof define&&define.amd?define(["exports"],c):"object"===typeof exports?c(exports):c(b)})(this,function(b){function c(a,b,c,f){this.ambient=b||[0,0,0,1];this.position=a?[a[0],a[1],a[2],1]:[0,0,1,0];this.diffuse=c||[1,1,1,1];this.specular=f||[1,1,1]}function a(){this.lights=[new c];this.sceneAmbient=[.2,.2,.2]}function d(a,b,c,f,d){null!=a&&(a=n.toGLColor(a));null!=b&&(b=n.toGLColor(b));null!=c&&(c=n.toGLColor(c));null!=d&&(d=n.toGLColor(d));this.shininess=null==f?0:Math.min(Math.max(0,
f),128);this.ambient=a?a.slice(0,3):[.2,.2,.2];this.diffuse=b?b.slice(0,b.length):[.8,.8,.8,1];this.specular=c?c.slice(0,3):[0,0,0];this.emission=d?d.slice(0,3):[0,0,0];this.texture=null}function e(a,b){this.subMeshes=[];this.context=n._toContext(b);for(var c=0;c<a.subMeshes.length;c++){var f=a.subMeshes[c];0!=f.indices.length&&this.subMeshes.push(new g(f,this.context))}}function g(a,b){var c=b.createBuffer(),f=b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,c);b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,f);
b.bufferData(b.ARRAY_BUFFER,new Float32Array(a.vertices),b.STATIC_DRAW);var d=b.UNSIGNED_SHORT;65536<=a.vertices.length||65536<=a.indices.length?(d=b.UNSIGNED_INT,b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint32Array(a.indices),b.STATIC_DRAW)):256>=a.vertices.length&&256>=a.indices.length?(d=b.UNSIGNED_BYTE,b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint8Array(a.indices),b.STATIC_DRAW)):b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint16Array(a.indices),b.STATIC_DRAW);this.verts=c;this.faces=f;this.numVertices=
a.vertices.length/a.getStride();this.facesLength=a.indices.length;this.type=d;this.format=a.attributeBits;this.context=b}function h(a,b,c){if(0>b||0>c)throw Error("width or height negative");this.context=a;this.textureUnit=1;this.buffer=a.createFramebuffer();this.colorTexture=a.createTexture();this.width=Math.ceil(b);this.height=Math.ceil(c);this.context.activeTexture(this.context.TEXTURE0+this.textureUnit);this.context.bindTexture(this.context.TEXTURE_2D,this.colorTexture);this.context.pixelStorei(this.context.UNPACK_FLIP_Y_WEBGL,
1);this.context.texImage2D(this.context.TEXTURE_2D,0,this.context.RGBA,this.width,this.height,0,this.context.RGBA,this.context.UNSIGNED_BYTE,null);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_MAG_FILTER,this.context.NEAREST);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_MIN_FILTER,this.context.NEAREST);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_WRAP_S,this.context.CLAMP_TO_EDGE);this.context.texParameteri(this.context.TEXTURE_2D,
this.context.TEXTURE_WRAP_T,this.context.CLAMP_TO_EDGE);this.depthbuffer=this.context.createRenderbuffer();b=this.context.getParameter(a.FRAMEBUFFER_BINDING);this.context.bindFramebuffer(a.FRAMEBUFFER,this.buffer);this.context.bindRenderbuffer(a.RENDERBUFFER,this.depthbuffer);this.context.renderbufferStorage(a.RENDERBUFFER,a.DEPTH_COMPONENT16,this.width,this.height);this.context.bindFramebuffer(a.FRAMEBUFFER,b)}function f(b){var c=b;"function"==typeof b.getContext&&(c=HTMLCanvasElement&&c.constructor==
HTMLCanvasElement?n.get3DContext(b):n._toContext(c));this.context=c;this.specularEnabled=this.lightingEnabled=!0;this.program=new ShaderProgram(c,this._getDefines()+ShaderProgram.getDefaultVertex(),this._getDefines()+ShaderProgram.getDefaultFragment());this.shapes=[];this.clearColor=[0,0,0,1];this.fboFilter=null;this.textureCache={};this._projectionMatrix=GLMath.mat4identity();this._viewMatrix=GLMath.mat4identity();this._invView=null;this.lightSource=new a;this.width=Math.ceil(1*this.context.canvas.width);
this.height=Math.ceil(1*this.context.canvas.height);this.context.viewport(0,0,this.width,this.height);this.context.enable(c.BLEND);this.context.blendFunc(c.SRC_ALPHA,c.ONE_MINUS_SRC_ALPHA);this.context.enable(this.context.DEPTH_TEST);this.context.depthFunc(this.context.LEQUAL);this.context.clearDepth(1);this._setClearColor();this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);this.useProgram(this.program)}function k(){this.shapes=[];this.parent=null;this.transform=new Transform}
function l(a){if(null==a)throw Error("mesh is null");this.bufferedMesh=a;this.transform=new Transform;this.material=new d;this.parent=null}if(!b.GLUtil){var n={renderLoop:function(a){a();var b=function(){window.requestAnimationFrame(b);a()};window.requestAnimationFrame(b)},createCanvas:function(a,b,c){var f=document.createElement("canvas");if(null==a)f.width=Math.ceil(window.innerWidth)+"";else{if(0>a)throw Error("width negative");f.width=Math.ceil(a)+""}if(null==b)f.height=Math.ceil(window.innerHeight)+
"";else{if(0>b)throw Error("height negative");f.height=Math.ceil(b)+""}c&&c.appendChild(f);return f},get3DOr2DContext:function(a){if(!a||!a.getContext)return null;var b=null,c={antialias:!0};try{b=a.getContext("webgl",c)}catch(f){b=null}if(!b)try{b=a.getContext("experimental-webgl",c)}catch(d){b=null}if(!b)try{b=a.getContext("moz-webgl",c)}catch(h){b=null}if(!b)try{b=a.getContext("webkit-3d",c)}catch(e){b=null}if(!b)try{b=a.getContext("2d",c)}catch(g){b=null}n.is3DContext(b)&&b.getExtension("OES_element_index_uint");
return b},get3DContext:function(a,b){var c=n.get3DOr2DContext(a),f=null;!c&&window.WebGLShader?f="Failed to initialize graphics support required by this page.":window.WebGLShader&&!n.is3DContext(c)?f="This page requires WebGL, but it failed to start. Your computer might not support WebGL.":c&&n.is3DContext(c)||(f="This page requires a WebGL-supporting browser.");return f?((b||window.alert)(f),null):c},is3DContext:function(a){return a&&"compileShader"in a},getPromiseResults:function(a,b,c){if(!a||
0==a.length)return Promise.resolve({successes:[],failures:[],results:[]});for(var f={successes:[],failures:[],results:[]},d=[],h=0;h<a.length;h++){var e=h;d.push(a[h].then(function(a){b&&b(a);f.successes[e]=a;return!0},function(a){c&&c(a);f.failures[e]=a;return!1}))}return Promise.all(d).then(function(a){for(var b=0;b<f.successes.length;b++)"undefined"==typeof f.successes[b]&&(f.successes.splice(b,1),--b);for(b=0;b<f.failures.length;b++)"undefined"==typeof f.failures[b]&&(f.failures.splice(b,1),--b);
f.results=a;return Promise.resolve(f)})},loadFileFromUrl:function(a,b){var c=b||"text";return new Promise(function(b,f){var d=new XMLHttpRequest;d.onreadystatechange=function(d){d=d.target;if(4==d.readyState)if(200<=d.status&&300>d.status){var h=d.response;h||(h="xml"==c?d.responseXML:"json"==c?(d.responseJSON||JSON.parse(d.responseText))+"":"arraybuffer"==c?d.response:d.responseText+"");b({url:a,data:h})}else f({url:a})};d.onerror=function(b){f({url:a,error:b})};d.open("get",a,!0);d.responseType=
c;d.send()})}};window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame,window.requestAnimationFrame||(window.requestAnimationFrame=function(a){window.setTimeout(a,17)}));(function(a){var b=function(a){var b=1*a[0],c=1*a[1],f=1*a[2],c=0>c?0:255<c?255:c,f=0>f?0:255<f?255:f;if(0===f)return[c,c,c];a=0;127.5>=c?a=c*(255+f)/255:(a=c*f/255,a=c+f-a);var d=2*c-a;if(0>b||360<=b)b=(b%360+360)%360;var m=b+
120;360<=m&&(m-=360);c=60>m?d+(a-d)*m/60:180>m?a:240>m?d+(a-d)*(240-m)/60:d;m=b;f=60>m?d+(a-d)*m/60:180>m?a:240>m?d+(a-d)*(240-m)/60:d;m=b-120;0>m&&(m+=360);b=60>m?d+(a-d)*m/60:180>m?a:240>m?d+(a-d)*(240-m)/60:d;return[0>c?0:255<c?255:c,0>f?0:255<f?255:f,0>b?0:255<b?255:b]},c=function(a){function m(a){var b;return 255*(0>(b=parseFloat(a))?0:100<b?100:b)/100}function h(a){var b;return 255*(0>(b=parseFloat(a))?0:1<b?1:b)}function e(a){var b;return 0>(b=parseInt(a,10))?0:255<b?255:b}function g(a){a=
parseFloat(k[1]);if(0>a||360<=a)a=(a%360+360)%360;return a}var k=null;if(!a)return null;var l;if(null!==(k=/^#([A-Fa-f0-9]{2})([A-Fa-f0-9]{2})([A-Fa-f0-9]{2})$/.exec(a)))return[parseInt(k[1],16),parseInt(k[2],16),parseInt(k[3],16),255];if(null!==(k=/^rgb\(\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*\)$/.exec(a)))return[m(k[1]),m(k[2]),m(k[3]),255];if(null!==(k=/^rgb\(\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*\)$/.exec(a)))return[e(k[1]),e(k[2]),
e(k[3]),255];if(null!==(k=/^rgba\(\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return[m(k[1]),m(k[2]),m(k[3]),h(k[4])];if(null!==(k=/^rgba\(\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return[e(k[1]),e(k[2]),e(k[3]),h(k[4])];if(null!==(k=/^#([A-Fa-f0-9]{1})([A-Fa-f0-9]{1})([A-Fa-f0-9]{1})$/.exec(a))){var n=parseInt(k[1],16);a=parseInt(k[2],16);l=parseInt(k[3],
16);return[n+(n<<4),a+(a<<4),l+(l<<4),255]}if(null!==(k=/^hsl\(\s*([\+\-]?\d+(?:\.\d+)?)\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*\)$/.exec(a)))return a=b([g(k[1]),m(k[3]),m(k[2])]),[a[0],a[1],a[2],255];if(null!==(k=/^hsla\(\s*([\+\-]?\d+(?:\.\d+)?)\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return a=b([g(k[1]),m(k[3]),m(k[2])]),[a[0],a[1],a[2],h(k[4])];d();a=a.toLowerCase();0<=a.indexOf("grey")&&(a=a.replace("grey",
"gray"));l=f[a];return"string"===typeof l?c(l):"transparent"===a?[0,0,0,0]:null};a.toGLColor=function(a,b,f,d){return null==a?[0,0,0,0]:"string"==typeof a?(a=c(a)||[0,0,0,0],b=1/255,a[0]*=b,a[1]*=b,a[2]*=b,a[3]*=b,a):"number"==typeof a&&"number"==typeof b&&"number"==typeof f?[a,b,f,"number"!=typeof d?1:d]:a.constructor==Array?[a[0]||0,a[1]||0,a[2]||0,"number"!=typeof a[3]?1:a[3]]:a||[0,0,0,0]};var f=null,d=function(){if(!f){var a="aliceblue f0f8ff antiquewhite faebd7 aqua 00ffff aquamarine 7fffd4 azure f0ffff beige f5f5dc bisque ffe4c4 black 000000 blanchedalmond ffebcd blue 0000ff blueviolet 8a2be2 brown a52a2a burlywood deb887 cadetblue 5f9ea0 chartreuse 7fff00 chocolate d2691e coral ff7f50 cornflowerblue 6495ed cornsilk fff8dc crimson dc143c cyan 00ffff darkblue 00008b darkcyan 008b8b darkgoldenrod b8860b darkgray a9a9a9 darkgreen 006400 darkkhaki bdb76b darkmagenta 8b008b darkolivegreen 556b2f darkorange ff8c00 darkorchid 9932cc darkred 8b0000 darksalmon e9967a darkseagreen 8fbc8f darkslateblue 483d8b darkslategray 2f4f4f darkturquoise 00ced1 darkviolet 9400d3 deeppink ff1493 deepskyblue 00bfff dimgray 696969 dodgerblue 1e90ff firebrick b22222 floralwhite fffaf0 forestgreen 228b22 fuchsia ff00ff gainsboro dcdcdc ghostwhite f8f8ff gold ffd700 goldenrod daa520 gray 808080 green 008000 greenyellow adff2f honeydew f0fff0 hotpink ff69b4 indianred cd5c5c indigo 4b0082 ivory fffff0 khaki f0e68c lavender e6e6fa lavenderblush fff0f5 lawngreen 7cfc00 lemonchiffon fffacd lightblue add8e6 lightcoral f08080 lightcyan e0ffff lightgoldenrodyellow fafad2 lightgray d3d3d3 lightgreen 90ee90 lightpink ffb6c1 lightsalmon ffa07a lightseagreen 20b2aa lightskyblue 87cefa lightslategray 778899 lightsteelblue b0c4de lightyellow ffffe0 lime 00ff00 limegreen 32cd32 linen faf0e6 magenta ff00ff maroon 800000 mediumaquamarine 66cdaa mediumblue 0000cd mediumorchid ba55d3 mediumpurple 9370d8 mediumseagreen 3cb371 mediumslateblue 7b68ee mediumspringgreen 00fa9a mediumturquoise 48d1cc mediumvioletred c71585 midnightblue 191970 mintcream f5fffa mistyrose ffe4e1 moccasin ffe4b5 navajowhite ffdead navy 000080 oldlace fdf5e6 olive 808000 olivedrab 6b8e23 orange ffa500 orangered ff4500 orchid da70d6 palegoldenrod eee8aa palegreen 98fb98 paleturquoise afeeee palevioletred d87093 papayawhip ffefd5 peachpuff ffdab9 peru cd853f pink ffc0cb plum dda0dd powderblue b0e0e6 purple 800080 rebeccapurple 663399 red ff0000 rosybrown bc8f8f royalblue 4169e1 saddlebrown 8b4513 salmon fa8072 sandybrown f4a460 seagreen 2e8b57 seashell fff5ee sienna a0522d silver c0c0c0 skyblue 87ceeb slateblue 6a5acd slategray 708090 snow fffafa springgreen 00ff7f steelblue 4682b4 tan d2b48c teal 008080 thistle d8bfd8 tomato ff6347 turquoise 40e0d0 violet ee82ee wheat f5deb3 white ffffff whitesmoke f5f5f5 yellow ffff00 yellowgreen 9acd32".split(" ");
f={};for(var b=0;b<a.length;b+=2)f[a[b]]="#"+a[b+1]}}})(n);n._toContext=function(a){return a&&a.getContext?a.getContext():a};n._isPowerOfTwo=function(a){if(Math.floor(a)!=a||0>=a)return!1;for(;1<a&&0==(a&1);)a>>=1;return 1==a};c.prototype.setParams=function(a){null!=a.ambient&&(this.ambient=n.toGLColor(a.ambient));if(null!=a.position){var b=a.position;this.position=[b[0],b[1],b[2],null==b[3]?0:b[3]]}null!=a.specular&&(this.specular=n.toGLColor(a.specular));null!=a.diffuse&&(this.diffuse=n.toGLColor(a.diffuse));
return this};a.MAX_LIGHTS=3;a._createNewLight=function(a){var b=new c;0!=a&&(b.diffuse=[0,0,0,0],b.specular=[0,0,0]);return b};a.prototype.getCount=function(){return this.lights.length};a.prototype.getLight=function(b){var c=this.lights.length;this.lights[b]||(this.lights[b]=a._createNewLight(b));if(2<=this.lights.length-c)for(;c<this.lights.length;c++)this.lights[c]||(this.lights[c]=a._createNewLight(c));return this.lights[b]};a.prototype.setParams=function(a,b){this.getLight(a).setParams(b);return this};
a.prototype.setDirectionalLight=function(a,b){return this.setParams(a,{position:[b[0],b[1],b[2],0]})};a.prototype.setPointLight=function(a,b){return this.setParams(a,{position:[b[0],b[1],b[2],1]})};d.prototype.copy=function(){return(new d(this.ambient.slice(0,this.ambient.length),this.diffuse.slice(0,this.diffuse.length),this.specular.slice(0,this.specular.length),this.shininess,this.emission.slice(0,this.emission.length))).setParams({texture:this.texture})};d.prototype.setParams=function(a){null!=
a.ambient&&(this.ambient=n.toGLColor(a.ambient));null!=a.diffuse&&(this.diffuse=n.toGLColor(a.diffuse));null!=a.specular&&(this.specular=n.toGLColor(a.specular));null!=a.emission&&(this.emission=n.toGLColor(a.emission));null!=a.shininess&&(this.shininess=a.shininess);null!=a.texture&&(a=a.texture,this.texture="string"==typeof a?new p(a):a);return this};d.fromColor=function(a,b,c,f){a=n.toGLColor(a,b,c,f);return new d(a,a)};d.fromTexture=function(a){return(new d).setParams({texture:a})};var p=function(a){this.image=
null;this.loadStatus=0;this.loadedTexture=null;this.name=a;this.width=0;this.clamp=!1;this.height=0};p.prototype.setClamp=function(a){this.clamp=a;return this};p.loadTexture=function(a,b){if(b&&b[a])return Promise.resolve(b[a]);var c=new p(a);b&&(b[a]=c);return c.loadImage().then(function(a){return a},function(a){return Promise.reject(a.name)})};p.fromUint8Array=function(a,b,c){if(0>b)throw Error("width less than 0");if(0>c)throw Error("height less than 0");if(a.length<b*c*4)throw Error("array too short for texture");
var f=new p("");f.image=a;f.width=Math.ceil(b);f.height=Math.ceil(c);f.loadStatus=2;return f};p.loadTga=function(a){return n.loadFileFromUrl(a,"arraybuffer").then(function(a){a=new DataView(a.data);a.getUint8(0);a.getUint8(1);var b=a.getUint8(2);if(2!=b&&3!=b)return Promise.reject(Error("unsupported image type"));var c=a.getUint16(8,!0),f=a.getUint16(10,!0);if(0!=c||0!=f)return Promise.reject(Error("unsupported origins"));c=a.getUint16(12,!0);f=a.getUint16(14,!0);if(0==c||0==f)return Promise.reject(Error("invalid width or height"));
var d=a.getUint8(16);a.getUint8(16);if(!(32==d&&2==b||8==d&&3==b))return Promise.reject(Error("unsupported pixelsize"));var h=c*f,e=new Uint8Array(4*h),m=18,g=0;if(32==d&&2==b)for(g=b=0;b<h;b++,g+=4)e[g+2]=a.getUint8(m),e[g+1]=a.getUint8(m+1),e[g]=a.getUint8(m+2),e[g+3]=a.getUint8(m+3),m+=4;else if(8==d&&3==b)for(g=b=0;b<h;b++,g+=4)d=a.getUint8(m),e[g]=d,e[g+1]=d,e[g+2]=d,e[g+3]=255,m++;return{width:c,height:f,image:e}})};p.prototype.loadImage=function(){if(null!==this.image)return Promise.resolve(this);
var a=this,b=this.name;a.loadStatus=1;return/\.tga$/i.test(b)?p.loadTga(b).then(function(b){a.image=b.image;a.width=b.width;a.height=b.height;a.loadStatus=2;return a},function(c){a.loadStatus=-1;return Promise.reject({name:b,error:c})}):new Promise(function(c,f){var d=new Image;d.onload=function(b){b=b.target;a.image=b;a.width=b.width;a.height=b.height;a.loadStatus=2;c(a)};d.onerror=function(c){a.loadStatus=-1;f({name:b,error:c})};d.src=b})};p.prototype.dispose=function(){null==this.loadedTexture&&
(this.loadedTexture.dispose(),this.loadedTexture=null)};e.prototype.getContext=function(){return this.context};e.prototype.getFormat=function(){for(var a=0,b=0;b<this.subMeshes.length;b++)a|=this.subMeshes[b].format;return a};e.prototype.draw=function(a){for(var b=0;b<this.subMeshes.length;b++)this.subMeshes[b].draw(a)};e.prototype.dispose=function(){for(var a=0;a<this.subMeshes.length;a++)this.subMeshes[a].dispose()};g.prototype.dispose=function(){null!=this.verts&&this.context.deleteBuffer(this.verts);
null!=this.faces&&this.context.deleteBuffer(this.faces);this.faces=this.verts=null};g.prototype.draw=function(a){function b(a,c,f,d,h,e){null!==c&&(a.enableVertexAttribArray(c),a.vertexAttribPointer(c,f,d,!1,h,e))}var c=a.getContext();if(null==this.verts||null==this.faces)throw Error("mesh buffer disposed");if(c!=this.context)throw Error("can't bind mesh: context mismatch");c.bindBuffer(c.ARRAY_BUFFER,this.verts);c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,this.faces);var f=this.format,d=Mesh.getStride(f),
h=[],e=a.get("position");h.push(e);b(c,e,3,c.FLOAT,4*d,0);var g=Mesh.normalOffset(f);0<=g?(e=a.get("normal"),h.push(e),b(c,e,3,c.FLOAT,4*d,4*g)):(e=a.get("normal"),null!==e&&c.disableVertexAttribArray(e));g=Mesh.colorOffset(f);0<=g?(a.setUniforms({useColorAttr:1}),e=a.get("colorAttr"),h.push(e),b(c,e,3,c.FLOAT,4*d,4*g)):(a.setUniforms({useColorAttr:0}),e=a.get("colorAttr"),null!==e&&c.disableVertexAttribArray(e));g=Mesh.texCoordOffset(f);0<=g?(e=a.get("uv"),h.push(e),b(c,e,2,c.FLOAT,4*d,4*g)):(e=
a.get("uv"),null!==e&&c.disableVertexAttribArray(e));c=a.getContext();if(null==this.verts||null==this.faces)throw Error("mesh buffer disposed");if(c!=this.context)throw Error("can't bind mesh: context mismatch");a=c.TRIANGLES;0!=(this.format&Mesh.LINES_BIT)&&(a=c.LINES);0!=(this.format&Mesh.POINTS_BIT)&&(a=c.POINTS);c.drawElements(a,this.facesLength,this.type,0)};g.prototype.primitiveCount=function(){return 0!=(this.format&Mesh.LINES_BIT)?Math.floor(this.facesLength/2):0!=(this.format&Mesh.POINTS_BIT)?
this.facesLength:Math.floor(this.facesLength/3)};e.prototype.vertexCount=function(){for(var a=0,b=0;b<this.subMeshes.length;b++)a+=this.subMeshes[b].numVertices;return a};e.prototype.primitiveCount=function(){for(var a=0,b=0;b<this.subMeshes.length;b++)a+=this.subMeshes[b].primitiveCount();return a};h.prototype.getContext=function(){return this.context};h.prototype.bind=function(a){if(a.getContext()!=this.context)throw Error("can't bind buffer: context mismatch");this.context.activeTexture(this.context.TEXTURE0+
this.textureUnit);this.context.bindFramebuffer(this.context.FRAMEBUFFER,this.buffer);this.context.framebufferTexture2D(this.context.FRAMEBUFFER,this.context.COLOR_ATTACHMENT0,this.context.TEXTURE_2D,this.colorTexture,0);this.context.framebufferRenderbuffer(this.context.FRAMEBUFFER,this.context.DEPTH_ATTACHMENT,this.context.RENDERBUFFER,this.depthbuffer)};h.prototype.unbind=function(){this.context.framebufferTexture2D(this.context.FRAMEBUFFER,this.context.COLOR_ATTACHMENT0,this.context.TEXTURE_2D,
null,0);this.context.framebufferRenderbuffer(this.context.FRAMEBUFFER,this.context.DEPTH_ATTACHMENT,this.context.RENDERBUFFER,null);this.context.bindFramebuffer(this.context.FRAMEBUFFER,null)};h.prototype.dispose=function(){null!=this.buffer&&this.context.deleteFramebuffer(this.buffer);null!=this.depthbuffer&&this.context.deleteRenderbuffer(this.depthbuffer);null!=this.colorTexture&&this.context.deleteTexture(this.colorTexture);this.colorTexture=this.depthbuffer=this.buffer=null};f.prototype.getContext=
function(){return this.context};f.prototype.getClearColor=function(){return this.clearColor.slice(0,4)};f.prototype._getDefines=function(){var a="";this.lightingEnabled&&(a+="#define SHADING\n");this.specularEnabled&&(a+="#define SPECULAR\n");return a};f.prototype._initProgramData=function(){(new LightsBinder(this.lightSource)).bind(this.program);this._updateMatrix()};f.prototype.useProgram=function(a){if(!a)throw Error("invalid program");a.use();this.program=a;this._initProgramData();return this};
f.prototype.disableLighting=function(){this.lightingEnabled=!1;var a=new ShaderProgram(this.context,this._getDefines()+ShaderProgram.getDefaultVertex(),this._getDefines()+ShaderProgram.getDefaultFragment());return this.useProgram(a)};f.prototype.setDimensions=function(a,b){if(0>a||0>b)throw Error("width or height negative");this.width=Math.ceil(a);this.height=Math.ceil(b);this.context.canvas.width=this.width+"";this.context.canvas.height=this.height+"";this.context.viewport(0,0,this.width,this.height);
"undefined"!=this.fbo&&this.fbo&&(this.fbo.dispose(),this.fbo=this.createBuffer())};f.prototype.getWidth=function(){return this.width};f.prototype.getHeight=function(){return this.height};f.prototype.getAspect=function(){return this.getWidth()/this.getHeight()};f.prototype.createBuffer=function(){return new h(this.context,this.getWidth(),this.getHeight())};f.prototype.getProjectionMatrix=function(){return this._projectionMatrix.slice(0,16)};f.prototype.getViewMatrix=function(){return this._viewMatrix.slice(0,
16)};f.prototype.setPerspective=function(a,b,c,f){return this.setProjectionMatrix(GLMath.mat4perspective(a,b,c,f))};f.prototype.setOrthoAspect=function(a,b,c,f,d,h,e){null==e&&(e=this.getAspect());0==e&&(e=1);return this.setProjectionMatrix(GLMath.mat4orthoAspect(a,b,c,f,d,h,e))};f.prototype.setOrtho2DAspect=function(a,b,c,f,d){return this.setOrthoAspect(a,b,c,f,-1,1,d)};f.prototype.setFrustum=function(a,b,c,f,d,e){return this.setProjectionMatrix(GLMath.mat4frustum(a,b,f,c,d,e))};f.prototype.setOrtho=
function(a,b,c,f,d,e){return this.setProjectionMatrix(GLMath.mat4ortho(a,b,c,f,d,e))};f.prototype.setOrtho2D=function(a,b,c,f){return this.setProjectionMatrix(GLMath.mat4ortho(a,b,c,f,-1,1))};f.prototype._setClearColor=function(){this.context.clearColor(this.clearColor[0],this.clearColor[1],this.clearColor[2],this.clearColor[3]);return this};f.prototype.setClearColor=function(a,b,c,f){this.clearColor=n.toGLColor(a,b,c,f);return this._setClearColor()};f.prototype.loadTexture=function(a){return p.loadTexture(a,
this.textureCache)};f.prototype.loadAndMapTexture=function(a){var b=this.context,c=null,c=a.constructor==p?a.loadImage():p.loadTexture(a,this.context,this.textureCache);return c.then(function(a){a.loadedTexture=new LoadedTexture(a,b);return a})};f.prototype.loadAndMapTextures=function(a,b,c){for(var f=[],d=0;d<a.length;d++)f.push(this.loadAndMapTexture(a[d]));return n.getPromiseResults(f,b,c)};f.prototype._setIdentityMatrices=function(){this._projectionMatrix=GLMath.mat4identity();this._viewMatrix=
GLMath.mat4identity();this._updateMatrix()};f.prototype._updateMatrix=function(){var a={view:this._viewMatrix,projection:this._projectionMatrix,viewMatrix:this._viewMatrix,projectionMatrix:this._projectionMatrix};if(null!=this.program.get("viewInvW")){var b=GLMath.mat4invert(this._viewMatrix);a.viewInvW=[b[12],b[13],b[14],b[15]]}this.program.setUniforms(a)};f.prototype.setProjectionMatrix=function(a){this._projectionMatrix=GLMath.mat4copy(a);this._updateMatrix();return this};f.prototype.setViewMatrix=
function(a){this._viewMatrix=GLMath.mat4copy(a);this._updateMatrix();return this};f.prototype.setLookAt=function(a,b,c){c=c||[0,1,0];b=b||[0,0,0];this._viewMatrix=GLMath.mat4lookat(a,b,c);this._updateMatrix();return this};f.prototype.addShape=function(a){this.shapes.push(a);return this};f.prototype.makeShape=function(a){a=new e(a,this.context);return new l(a)};f.prototype.removeShape=function(a){for(var b=0;b<this.shapes.length;b++)this.shapes[b]==a&&(this.shapes.splice(b,1),b--);return this};f.prototype.setDirectionalLight=
function(a,b,c,f){this.lightSource.setDirectionalLight(a,b).setParams(a,{diffuse:c,specular:f});(new LightsBinder(this.lightSource)).bind(this.program);return this};f.prototype.setLightParams=function(a,b){this.lightSource.setParams(a,b);(new LightsBinder(this.lightSource)).bind(this.program);return this};f.prototype.setAmbient=function(a,b,c,f){this.lightSource.sceneAmbient=n.toGLColor(a,b,c,f);this.lightSource.sceneAmbient=this.lightSource.sceneAmbient.slice(0,4);(new LightsBinder(this.lightSource)).bind(this.program);
return this};f.prototype.setPointLight=function(a,b,c,f){this.lightSource.setPointLight(a,b).setParams(a,{diffuse:c,specular:f});(new LightsBinder(this.lightSource)).bind(this.program);return this};f._isIdentityExceptTranslate=function(a){return 1==a[0]&&0==a[1]&&0==a[2]&&0==a[3]&&0==a[4]&&1==a[5]&&0==a[6]&&0==a[7]&&0==a[8]&&0==a[9]&&1==a[10]&&0==a[11]&&1==a[15]};f.prototype._setupMatrices=function(a,b){var c={},d=a.getMatrix(),e;null!=b.get("modelViewMatrix")&&(f._isIdentityExceptTranslate(this._viewMatrix)?
(e=d.slice(0,16),e[13]+=this._viewMatrix[13],e[14]+=this._viewMatrix[14],e[15]+=this._viewMatrix[15]):e=GLMath.mat4multiply(this._viewMatrix,d),c.modelViewMatrix=e);e=GLMath.mat4inverseTranspose3(d);c.world=d;c.modelMatrix=d;c.worldViewInvTrans3=e;c.normalMatrix=e;b.setUniforms(c)};f.prototype.render=function(){if("undefined"!=typeof this.fboFilter&&this.fboFilter){var a=this.program,b=this.getProjectionMatrix(),c=this.getViewMatrix();this.fbo.bind(this.program);this._renderInner();this.fbo.unbind();
this.useProgram(this.fboFilter);this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);this._setIdentityMatrices();this._renderShape(this.fboQuad,this.fboFilter);this.setProjectionMatrix(b);this.setViewMatrix(c);this.useProgram(a)}else this._renderInner();this.context.flush();return this};f.prototype._renderShape=function(a,b){if(a.constructor==k)for(var c=0;c<a.shapes.length;c++)this._renderShape(a.shapes[c],b);else this._setupMatrices(a,b),Binders.getMaterialBinder(a.material).bind(b),
a.bufferedMesh.draw(b)};f.prototype.useFilter=function(a){null==a?this.fboFilter=null:(this.fboFilter="string"==typeof a?ShaderProgram.makeEffect(this.context,a):a,"undefined"!=typeof this.fbo&&this.fbo||(this.fbo=this.createBuffer()),"undefined"!=typeof this.fboQuad&&this.fboQuad||(this.getWidth(),this.getHeight(),a=new Mesh([-1,1,0,0,1,-1,-1,0,0,0,1,1,0,1,1,1,-1,0,1,0],[0,1,2,2,1,3],Mesh.TEXCOORDS_BIT),this.fboQuad=this.makeShape(a).setMaterial(this.fbo)));return this};f.prototype._renderInner=
function(){this._updateMatrix();this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);for(var a=0;a<this.shapes.length;a++)this._renderShape(this.shapes[a],this.program);return this};k.prototype.addShape=function(a){a.parent=this;this.shapes.push(a);return this};k.prototype.getTransform=function(){return this.transform};k.prototype.getMatrix=function(){var a=this.getTransform(),b=a.isIdentity();if(null!=this.parent){var c=this.parent.getMatrix();mat=b?GLMath.mat4multiply(c,
a.getMatrix()):GLMath.mat4isIdentity(c)?a.getMatrix():c}else mat=a.getMatrix();return mat};k.prototype.setTransform=function(a){this.transform=a.copy();return this};k.prototype.vertexCount=function(){for(var a=0,b=0;b<this.shapes.length;b++)a+=this.shapes[b].vertexCount();return a};k.prototype.primitiveCount=function(){for(var a=0,b=0;b<this.shapes.length;b++)a+=this.shapes[b].primitiveCount();return a};f.prototype.vertexCount=function(){for(var a=0,b=0;b<this.shapes.length;b++)a+=this.shapes[b].vertexCount();
return a};f.prototype.primitiveCount=function(){for(var a=0,b=0;b<this.shapes.length;b++)a+=this.shapes[b].primitiveCount();return a};k.prototype.setPosition=function(a,b,c){this.transform.setPosition(a,b,c);return this};k.prototype.setQuaternion=function(a){this.transform.setQuaternion(a);return this};k.prototype.setScale=function(a,b,c){this.transform.setScale(a,b,c);return this};l.prototype.vertexCount=function(){return this.bufferedMesh?this.bufferedMesh.vertexCount():0};l.prototype.primitiveCount=
function(){return this.bufferedMesh?this.bufferedMesh.primitiveCount():0};l.prototype.setColor=function(a,b,c,f){this.material=d.fromColor(a,b,c,f);return this};l.prototype.setTexture=function(a){this.material=d.fromTexture(a);return this};l.prototype.setMaterial=function(a){this.material=a;return this};l.prototype.copy=function(){var a=new l(this.bufferedMesh);a.material=this.material.copy();a.transform=this.getTransform().copy();return a};l.prototype.getTransform=function(){return this.transform};
l.prototype.setTransform=function(a){this.transform=a.copy();return this};l.prototype.setScale=function(a,b,c){this.getTransform().setScale(a,b,c);return this};l.prototype.setPosition=function(a,b,c){this.getTransform().setPosition(a,b,c);return this};l.prototype.setQuaternion=function(a){this.getTransform().setQuaternion(a);return this};l.prototype.getMatrix=function(){var a=this.getTransform(),b=a.isIdentity();if(null!=this.parent){var c=this.parent.getMatrix();mat=b?c:GLMath.mat4isIdentity(c)?
a.getMatrix():GLMath.mat4multiply(c,a.getMatrix())}else mat=a.getMatrix();return mat};l.prototype.multQuaternion=function(a){this.getTransform().multQuaternion(a);return this};l.prototype.multRotation=function(a,b,c,f){this.getTransform().multRotation(a,b,c,f);return this};l.prototype.setRotation=function(a,b,c,f){this.getTransform().setOrientation(a,b,c,f);return this};b.BufferedMesh=e;b.ShapeGroup=k;b.Lights=a;b.FrameBuffer=h;b.LightSource=c;b.Texture=p;b.Material=d;b.Shape=l;b.Scene3D=f;b.GLUtil=
n}});function MaterialBinder(b){this.mshade=b;this.textureSize=[0,0]}
MaterialBinder.prototype.bind=function(b){if(!this.mshade)return this;b.setUniforms({textureSize:this.textureSize,mshin:this.mshade.shininess,ma:3==this.mshade.ambient.length?this.mshade.ambient:[this.mshade.ambient[0],this.mshade.ambient[1],this.mshade.ambient[2]],md:4==this.mshade.diffuse.length?this.mshade.diffuse:[this.mshade.diffuse[0],this.mshade.diffuse[1],this.mshade.diffuse[2],4>this.mshade.diffuse.length?1:this.mshade.diffuse[3]],ms:3==this.mshade.specular.length?this.mshade.specular:[this.mshade.specular[0],
this.mshade.specular[1],this.mshade.specular[2]],me:3==this.mshade.emission.length?this.mshade.emission:[this.mshade.emission[0],this.mshade.emission[1],this.mshade.emission[2]]});this.mshade.texture&&(new TextureBinder(this.mshade.texture)).bind(b);return this};
function LoadedTexture(b,c){this.context=c=GLUtil._toContext(c);this.textureUnit=0;this.loadedTexture=c.createTexture();c.activeTexture(c.TEXTURE0+this.textureUnit);c.pixelStorei(c.UNPACK_FLIP_Y_WEBGL,1);c.bindTexture(c.TEXTURE_2D,this.loadedTexture);"src"in b.image?c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,b.image):c.texImage2D(c.TEXTURE_2D,0,c.RGBA,b.width,b.height,0,c.RGBA,c.UNSIGNED_BYTE,b.image);GLUtil._isPowerOfTwo(b.width)&&GLUtil._isPowerOfTwo(b.height)?c.generateMipmap(c.TEXTURE_2D):
(c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR),c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE),c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE))}LoadedTexture.prototype.dispose=function(){this.loadedTexture&&this.context.deleteTexture(this.loadedTexture)};function FrameBufferMaterialBinder(b){this.fb=b}
FrameBufferMaterialBinder.prototype.bind=function(b){var c={};c.sampler=this.fb.textureUnit;c.textureSize=[this.fb.width,this.fb.height];b.setUniforms(c);b=b.getContext();b.activeTexture(b.TEXTURE0+this.fb.textureUnit);b.bindTexture(b.TEXTURE_2D,this.fb.colorTexture);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.NEAREST);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.NEAREST);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE)};
function TextureBinder(b){this.texture=b}
TextureBinder.prototype.bind=function(b){var c=this.texture,a=b.getContext();if(null!==c.image&&null===c.loadedTexture)c.loadedTexture=new LoadedTexture(c,a);else if(null===c.image&&null===c.loadedTexture&&0==c.loadStatus){var d=this;c.loadImage().then(function(a){d.bind(b)});return}if(null!==c.loadedTexture){var e={};null==c.anisotropic&&(c.anisotropic=a.getExtension("EXT_texture_filter_anisotropic")||a.getExtension("WEBKIT_EXT_texture_filter_anisotropic")||a.getExtension("MOZ_EXT_texture_filter_anisotropic"),
null==c.anisotropic?(c.anisotropic={},c.maxAnisotropy=1):c.maxAnisotropy=a.getParameter(c.anisotropic.MAX_TEXTURE_MAX_ANISOTROPY_EXT));e.sampler=c.loadedTexture.textureUnit;e.textureSize=[c.width,c.height];b.setUniforms(e);a.activeTexture(a.TEXTURE0+c.loadedTexture.textureUnit);a.bindTexture(a.TEXTURE_2D,c.loadedTexture.loadedTexture);"undefined"!=typeof c.anisotropic.TEXTURE_MAX_ANISOTROPY_EXT&&a.texParameteri(a.TEXTURE_2D,c.anisotropic.TEXTURE_MAX_ANISOTROPY_EXT,c.maxAnisotropy);a.texParameteri(a.TEXTURE_2D,
a.TEXTURE_MAG_FILTER,a.LINEAR);e=a.CLAMP_TO_EDGE;GLUtil._isPowerOfTwo(c.width)&&GLUtil._isPowerOfTwo(c.height)?(c.clamp||(e=a.REPEAT),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR_MIPMAP_LINEAR)):a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,e);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,e)}};function LightsBinder(b){this.lights=b}
LightsBinder.prototype.bind=function(b){var c=this.lights;if(!c||!b)return this;var a={};a.sceneAmbient=c.sceneAmbient.slice(0,3);for(var d=0;d<c.lights.length;d++){var e=c.lights[d];a["lights["+d+"].diffuse"]=[e.diffuse[0],e.diffuse[1],e.diffuse[2],3<e.diffuse.length?e.diffuse[3]:1];a["lights["+d+"].specular"]=[e.specular[0],e.specular[1],e.specular[2],3<e.specular.length?e.specular[3]:1];a["lights["+d+"].position"]=c.lights[d].position}for(d=c.lights.length;d<Lights.MAX_LIGHTS;d++)a["lights["+d+
"].diffuse"]=[0,0,0,1],a["lights["+d+"].specular"]=[0,0,0,1],a["lights["+d+"].position"]=[0,0,0,0];b.setUniforms(a);return this};var Binders={getMaterialBinder:function(b){if(b){if(b instanceof Material)return new MaterialBinder(b);if(b instanceof Texture)return new TextureBinder(b);if(b instanceof FrameBuffer)return new FrameBufferMaterialBinder(b)}return{bind:function(b){}}}};
function Transform(){this.scale=[1,1,1];this.position=[0,0,0];this.rotation=GLMath.quatIdentity();this._matrixDirty=this.complexMatrix=!1;this._isIdentity=!0;this.matrix=GLMath.mat4identity()}Transform.prototype.reset=function(){this.matrix=GLMath.mat4identity();this.position=[0,0,0];this.scale=[1,1,1];this.rotation=GLMath.quatIdentity();this._matrixDirty=this.complexMatrix=!1;this._isIdentity=!0;return this};
Transform.prototype.setMatrix=function(b){this._matrixDirty=!1;this.complexMatrix=!0;this.matrix=b.slice(0,16);this.position=[this.matrix[12],this.matrix[13],this.matrix[14]];this.rotation=GLMath.quatFromMat4(this.matrix);this.rotation=GLMath.quatNormInPlace(this.rotation);this.scale=[this.matrix[0],this.matrix[5],this.matrix[10]];this._isIdentity=1==b[0]&&0==b[1]&&0==b[2]&&0==b[3]&&0==b[4]&&1==b[5]&&0==b[6]&&0==b[7]&&0==b[8]&&0==b[9]&&1==b[10]&&0==b[11]&&0==b[12]&&0==b[13]&&0==b[14]&&1==b[15];return this};
Transform.prototype.isIdentity=function(){if(this._matrixDirty)if(this.complexMatrix)this.getMatrix();else return 0==this.position[0]&&0==this.position[1]&&0==this.position[2]&&1==this.scale[0]&&1==this.scale[1]&&1==this.scale[2]&&GLMath.quatIsIdentity(this.rotation);return this._isIdentity};
Transform.prototype.resetTransform=function(){this.matrix=GLMath.mat4identity();this.position=[0,0,0];this.scale=[1,1,1];this._isIdentity=!0;this.rotation=GLMath.quatIdentity();this._matrixDirty=this.complexMatrix=!1;return this};
Transform.prototype.setScale=function(b,c,a){if(this.complexMatrix)return this;this.scale=null!=b&&null==c&&null==a?"number"!=typeof b?[b[0],b[1],b[2]]:[b,b,b]:[b,c,a];this._isIdentity=this._isIdentity&&1==this.scale[0]&&1==this.scale[1]&&1==this.scale[2];this._matrixDirty=!0;return this};
Transform.prototype.setPosition=function(b,c,a){if(this.complexMatrix)return this;this.position=null!=b&&null==c&&null==a?"number"!=typeof b?[b[0],b[1],b[2]]:[b,b,b]:[b,c,a];this._isIdentity=this._isIdentity&&0==this.position[0]&&0==this.position[1]&&0==this.position[2];this._matrixDirty=!0;return this};
Transform.prototype.movePosition=function(b,c,a){if(this.complexMatrix)return this;null!=b&&null==c&&null==a?"number"!=typeof b?(this.position[0]+=b[0],this.position[1]+=b[1],this.position[2]+=b[2]):(this.position[0]+=b,this.position[1]+=b,this.position[2]+=b):(this.position[0]+=b,this.position[1]+=c,this.position[2]+=a);this._isIdentity=this._isIdentity&&0==this.position[0]&&0==this.position[1]&&0==this.position[2];this._matrixDirty=!0;return this};
Transform.prototype.setQuaternion=function(b){if(this.complexMatrix)return this;this.rotation=b.slice(0,4);GLMath.quatNormInPlace(this.rotation);this._matrixDirty=!0;return this};Transform.prototype.setOrientation=function(b,c,a,d){return this.setQuaternion(GLMath.quatFromAxisAngle(b,c,a,d))};Transform.prototype.multQuaternion=function(b){if(this.complexMatrix)return this;this.rotation=GLMath.quatNormInPlace(GLMath.quatMultiply(this.rotation,b));this._matrixDirty=!0;return this};
Transform.prototype.multOrientation=function(b,c,a,d){return this.multQuaternion(GLMath.quatFromAxisAngle(b,c,a,d))};
Transform.prototype.getMatrix=function(){if(this._matrixDirty)if(this._matrixDirty=!1,GLMath.quatIsIdentity(this.rotation))this.matrix=[this.scale[0],0,0,0,0,this.scale[1],0,0,0,0,this.scale[2],0,this.position[0],this.position[1],this.position[2],1],this._isIdentity=0==this.position[0]&&0==this.position[1]&&0==this.position[2]&&1==this.scale[0]&&1==this.scale[1]&&1==this.scale[2];else{this.matrix=[1,0,0,0,0,1,0,0,0,0,1,0,this.position[0],this.position[1],this.position[2],1];this.matrix=GLMath.mat4multiply(this.matrix,
GLMath.quatToMat4(this.rotation));GLMath.mat4scaleInPlace(this.matrix,this.scale);var b=this.matrix;this._isIdentity=1==b[0]&&0==b[1]&&0==b[2]&&0==b[3]&&0==b[4]&&1==b[5]&&0==b[6]&&0==b[7]&&0==b[8]&&0==b[9]&&1==b[10]&&0==b[11]&&0==b[12]&&0==b[13]&&0==b[14]&&1==b[15]}else if(this._isIdentity)return GLMath.mat4identity();return this.matrix.slice(0,16)};
Transform.prototype.copy=function(){var b=new Transform;b.scale=this.scale.slice(0,this.scale.length);b.position=this.position.slice(0,this.scale.length);b.complexMatrix=this.complexMatrix;b._matrixDirty=this._matrixDirty;b.matrix=this.matrix.slice(0,this.matrix.length);return b};function Mesh(b,c,a){this.subMeshes=null!=b?[new SubMesh(b,c,a)]:[];this._elementsDefined=0;this.currentMode=-1;this.normal=[0,0,0];this.color=[0,0,0];this.texCoord=[0,0]}
Mesh._primitiveType=function(b){return b==Mesh.LINES||b==Mesh.LINE_STRIP?Mesh.LINES:b==Mesh.POINTS?Mesh.POINTS:Mesh.TRIANGLES};Mesh._isCompatibleMode=function(b,c){return b==c||Mesh._primitiveType(b)==Mesh._primitiveType(c)?!0:!1};Mesh._recalcNormalsStart=function(b,c,a,d,e,g){for(a=0;a<b.length;a+=d)if(b[a+e]=0,b[a+e+1]=0,b[a+e+2]=0,!g){var h=[b[a],b[a+1],b[a+2]];c[h]?c[h].push(a+e):c[h]=[a+e]}};
Mesh._recalcNormalsFinish=function(b,c,a,d,e,g){if(!g)for(var h in c)if((g=c[h])&&g.constructor==Array&&2<=g.length){var f=g[0];for(a=1;a<g.length;a++)b[f]+=b[g[a]],b[f+1]+=b[g[a]+1],b[f+2]+=b[g[a]+2];for(a=1;a<g.length;a++)b[g[a]]=b[f],b[g[a]+1]=b[f+1],b[g[a]+2]=b[f+2]}for(a=0;a<b.length;a+=d)if(h=b[a+e],g=b[a+e+1],f=b[a+e+2],c=Math.sqrt(h*h+g*g+f*f))c=1/c,b[a+e]=h*c,b[a+e+1]=g*c,b[a+e+2]=f*c};
Mesh._recalcNormals=function(b,c,a,d,e,g){g=g?1:-1;var h={},f;Mesh._recalcNormalsStart(b,h,c,a,d,e);for(var k=0;k<c.length;k+=3){var l=c[k]*a,n=c[k+1]*a,p=c[k+2]*a;f=[b[n]-b[p],b[n+1]-b[p+1],b[n+2]-b[p+2]];var m=[b[l]-b[p],b[l+1]-b[p+1],b[l+2]-b[p+2]],q=f[1]*m[2]-f[2]*m[1],r=f[2]*m[0]-f[0]*m[2],m=f[0]*m[1]-f[1]*m[0];f=Math.sqrt(q*q+r*r+m*m);0!=f&&(f=1/f,f*=g,q*=f,r*=f,m*=f,b[l+d]+=q,b[l+d+1]+=r,b[l+d+2]+=m,b[n+d]+=q,b[n+d+1]+=r,b[n+d+2]+=m,b[p+d]+=q,b[p+d+1]+=r,b[p+d+2]+=m)}Mesh._recalcNormalsFinish(b,
h,c,a,d,e)};Mesh._recalcNormalsLines=function(b,c,a,d,e,g){g=g?1:-1;var h={},f;Mesh._recalcNormalsStart(b,h,c,a,d,e);for(var k=0;k<c.length;k+=2){var l=c[k]*a,n=c[k+1]*a;f=[b[n],b[n+1],b[n+2]];var p=[b[l],b[l+1],b[l+2]],m=f[1]*p[2]-f[2]*p[1],q=f[2]*p[0]-f[0]*p[2],p=f[0]*p[1]-f[1]*p[0];f=Math.sqrt(m*m+q*q+p*p);0!=f&&(f=1/f,f*=g,m*=f,q*=f,p*=f,b[l+d]+=m,b[l+d+1]+=q,b[l+d+2]+=p,b[n+d]+=m,b[n+d+1]+=q,b[n+d+2]+=p)}Mesh._recalcNormalsFinish(b,h,c,a,d,e)};
Mesh.prototype.mode=function(b){if(0>b)throw Error("invalid mode");if(-1!=this.currentMode&&Mesh._isCompatibleMode(this.currentMode,b))this.subMeshes[this.subMeshes.length-1].newPrimitive();else{var c=0,a=Mesh._primitiveType(b);a==Mesh.LINES?c|=Mesh.LINES_BIT:a==Mesh.POINTS&&(c|=Mesh.POINTS_BIT);this.subMeshes.push(new SubMesh([],[],c))}this.currentMode=b;return this};
Mesh.prototype.merge=function(b){for(var c=this.subMeshes[this.subMeshes.length-1],a=c?c.attributeBits&Mesh.PRIMITIVES_BITS:0,d=0;d<b.subMeshes.length;d++){var e=b.subMeshes[d];if(0!=e.indices.length)if(!c||(e.attributeBits&Mesh.PRIMITIVES_BITS)!=a||196605<c.vertices.length+e.vertices.length||c.attributeBits!=e.attributeBits)c=new SubMesh(e.vertices.slice(0,e.vertices.length),e.indices.slice(0,e.indices.length),e.attributeBits),this.subMeshes.push(c),a=c.attributeBits&Mesh.PRIMITIVES_BITS;else{var g=
c.vertexCount(),d=c.indices.length;c.vertices.push.apply(c.vertices,e.vertices);for(c.indices.push.apply(c.indices,e.indices);d<c.indices.length;d++)c.indices[d]+=g}}c.newPrimitive();return this};Mesh.prototype.normal3=function(b,c,a){this.normal[0]=b;this.normal[1]=c;this.normal[2]=a;this._elementsDefined|=Mesh.NORMALS_BIT;return this};Mesh.prototype.transform=function(b){for(var c=0;c<this.subMeshes.length;c++)this.subMeshes[c].transform(b);return this};
Mesh.prototype.color3=function(b,c,a){"string"==typeof b?(b=GLUtil.toGLColor(b),this.color[0]=b[0],this.color[1]=b[1],this.color[2]=b[2]):"number"==typeof b&&"number"==typeof c&&"number"==typeof a?(this.color[0]=b,this.color[1]=c,this.color[2]=a):(this.color[0]=b[0],this.color[1]=b[1],this.color[2]=b[2]);this._elementsDefined|=Mesh.COLORS_BIT;return this};Mesh.prototype.texCoord2=function(b,c){this.texCoord[0]=b;this.texCoord[1]=c;this._elementsDefined|=Mesh.TEXCOORDS_BIT;return this};
Mesh.prototype.vertex3=function(b,c,a){0==this.subMeshes.length&&this.subMeshes.push(new SubMesh);var d=this.subMeshes[this.subMeshes.length-1];null!=b&&null==c&&null==a?"number"!=typeof b?d.vertex3(b[0],b[1],b[2],this):d.vertex3(b,b,b,this):d.vertex3(b,c,a,this);return this};Mesh.prototype.vertex2=function(b,c){return null!=b&&null==c&&null==z?"number"!=typeof b?this.vertex3(b[0],b[1],0):this.vertex3(b,b,0):this.vertex3(b,c,0)};
Mesh.prototype.setColor3=function(b,c,a){var d=b;"string"==typeof b&&(b=GLUtil.toGLColor(b),d=b[0],c=b[1],a=b[2]);for(b=0;b<this.subMeshes.length;b++)this.subMeshes[b].setColor3(d,c,a);return this};Mesh.prototype.recalcNormals=function(b,c){for(var a=0;a<this.subMeshes.length;a++)(this.subMeshes[a].attributeBits&Mesh.PRIMITIVES_BITS)!=Mesh.POINTS_BIT&&this.subMeshes[a].recalcNormals(b,c);return this};
Mesh.prototype.normalizeNormals=function(){for(var b=0;b<this.subMeshes.length;b++){var c=this.subMeshes[b].getStride(),a=this.subMeshes[b].vertices,d=Mesh.normalOffset(this.subMeshes[b].attributeBits);if(!(0>d))for(b=0;b<a.length;b+=c){var e=a[b+d],g=a[b+d+1],h=a[b+d+2],e=Math.sqrt(e*e+g*g+h*h);0!=e&&(e=1/e,a[b+d]*=e,a[b+d+1]*=e,a[b+d+2]*=e)}}return this};Mesh.prototype.toWireFrame=function(){for(var b=new Mesh,c=0;c<this.subMeshes.length;c++)b.subMeshes.push(this.subMeshes[c].toWireFrame());return b};
Mesh.prototype.setVertex=function(b,c,a,d){if(0>b)return this;"undefined"==typeof a&&"undefined"==typeof d&&(a=c[1],d=c[2],c=c[0]);for(var e=0,g=0;g<this.subMeshes.length;g++){var h=this.subMeshes[g],f=h.vertexCount(),f=e+f;if(b<f){b-=e;b*=h.getStride();h.vertices[b]=c;h.vertices[b+1]=a;h.vertices[b+2]=d;break}e=f}return this};
Mesh.prototype.setVertexNormal=function(b,c,a,d){if(0>b)return this;var e=0;"undefined"==typeof a&&"undefined"==typeof d&&(a=c[1],d=c[2],c=c[0]);for(var g=0;g<this.subMeshes.length;g++){var h=this.subMeshes[g],f=h.vertexCount(),f=e+f;if(b<f){b-=e;h._rebuildVertices(Mesh.NORMALS_BIT);b*=h.getStride();b+=Mesh.normalOffset(h.attributeBits);h.vertices[b]=c;h.vertices[b+1]=a;h.vertices[b+2]=d;break}e=f}return this};
Mesh.prototype.getVertex=function(b){if(0>b)return null;for(var c=0,a=0;a<this.subMeshes.length;a++){var d=this.subMeshes[a],e=d.vertexCount(),e=c+e;if(b<e)return b-=c,b*=d.getStride(),d.vertices.slice(b,b+3);c=e}return null};
Mesh.prototype.getVertexNormal=function(b){for(var c=0,a=0;a<this.subMeshes.length;a++){var d=this.subMeshes[a],e=d.vertexCount(),e=c+e;if(b<e)return 0!=(d.attributeBits&Mesh.NORMALS_BIT)?(b-=c,b*=d.getStride(),b+=Mesh.normalOffset(d.attributeBits),d.vertices.slice(b,b+3)):[0,0,0];c=e}return null};Mesh.prototype.vertexCount=function(){for(var b=0,c=0;c<this.subMeshes.length;c++)b+=this.subMeshes[c].vertexCount();return b};
function SubMesh(b,c,a){this.vertices=b||[];this.indices=c||[];this.startIndex=0;b=a&Mesh.PRIMITIVES_BITS;if(0!=b&&b!=Mesh.LINES_BIT&&b!=Mesh.POINTS_BIT)throw Error("invalid format");this.attributeBits=null==a?0:a;this.vertexCount=function(){return this.vertices.length/this.getStride()};this.getStride=function(){return Mesh.getStride(this.attributeBits)};this.newPrimitive=function(a){this.startIndex=this.vertices.length;return this};this._rebuildVertices=function(a){var b=this.attributeBits;a=b|a&
Mesh.ATTRIBUTES_BITS;if(a!=b){for(var c=this.getStride(),h=[],f=0;f<this.vertices.length;f+=c){var k=f+3;h.push(this.vertices[f],this.vertices[f+1],this.vertices[f+2]);if(0!=(a&Mesh.NORMALS_BIT))if(0!=(b&Mesh.NORMALS_BIT)){var l=this.vertices[k],n=this.vertices[k+1],p=this.vertices[k+2],k=k+3;h.push(l,n,p)}else h.push(0,0,0);0!=(a&Mesh.COLORS_BIT)&&(0!=(b&Mesh.COLORS_BIT)?(l=this.vertices[k],n=this.vertices[k+1],p=this.vertices[k+2],k+=3,h.push(l,n,p)):h.push(0,0,0));0!=(a&Mesh.TEXCOORDS_BIT)&&(0!=
(b&Mesh.TEXCOORDS_BIT)?h.push(this.vertices[k],this.vertices[k+1]):h.push(0,0))}this.vertices=h;this.attributeBits=a}};this._setTriangle=function(a,b,c,h,f){var k=c*b,l=h*b,n=f*b,p=0,m=this.vertices;for(a-=b;0<=a&&16>p;a-=b,p++){for(var q=7,r=0;r<b&&0!=q;r++)0!=(q&1)&&m[k+r]!=m[a+r]&&(q&=-2),0!=(q&2)&&m[l+r]!=m[a+r]&&(q&=-3),0!=(q&4)&&m[n+r]!=m[a+r]&&(q&=-5);if(0!=(q&1)){c=a/b;k=c*b;break}if(0!=(q&2)){h=a/b;l=h*b;break}if(0!=(q&4)){f=a/b;n=f*b;break}}m[k]==m[l]&&m[k+1]==m[l+1]&&m[k+2]==m[l+2]||m[k]==
m[n]&&m[k+1]==m[n+1]&&m[k+2]==m[n+2]||m[l]==m[n]&&m[l+1]==m[n+1]&&m[l+2]==m[n+2]||this.indices.push(c,h,f)};this.vertex3=function(a,b,c,h){var f=h.currentMode;if(-1==f)throw Error("mode() not called");this._rebuildVertices(h._elementsDefined);var k=this.vertices.length;this.vertices.push(a,b,c);0!=(this.attributeBits&Mesh.NORMALS_BIT)&&this.vertices.push(h.normal[0],h.normal[1],h.normal[2]);0!=(this.attributeBits&Mesh.COLORS_BIT)&&this.vertices.push(h.color[0],h.color[1],h.color[2]);0!=(this.attributeBits&
Mesh.TEXCOORDS_BIT)&&this.vertices.push(h.texCoord[0],h.texCoord[1]);a=this.getStride();f==Mesh.QUAD_STRIP&&this.vertices.length-this.startIndex>=4*a&&0==(this.vertices.length-this.startIndex)%(2*a)?(f=this.vertices.length/a-4,this._setTriangle(k,a,f,f+1,f+2),this._setTriangle(k,a,f+2,f+1,f+3)):f==Mesh.QUADS&&0==(this.vertices.length-this.startIndex)%(4*a)?(f=this.vertices.length/a-4,this._setTriangle(k,a,f,f+1,f+2),this._setTriangle(k,a,f,f+2,f+3)):f==Mesh.TRIANGLES&&0==(this.vertices.length-this.startIndex)%
(3*a)?(f=this.vertices.length/a-3,this._setTriangle(k,a,f,f+1,f+2)):f==Mesh.LINES&&0==(this.vertices.length-this.startIndex)%(2*a)?(f=this.vertices.length/a-2,this.indices.push(f,f+1)):f==Mesh.TRIANGLE_FAN&&this.vertices.length-this.startIndex>=3*a?(f=this.vertices.length/a-2,b=this.startIndex/a,this._setTriangle(k,a,b,f,f+1)):f==Mesh.LINE_STRIP&&this.vertices.length-this.startIndex>=2*a?(f=this.vertices.length/a-2,this.indices.push(f,f+1)):f==Mesh.POINTS?(f=this.vertices.length/a-1,this.indices.push(f)):
f==Mesh.TRIANGLE_STRIP&&this.vertices.length-this.startIndex>=3*a&&(f=this.vertices.length/a-3,b=this.startIndex/a,0==(f-b&1)?this._setTriangle(k,a,f,f+1,f+2):this._setTriangle(k,a,f+1,f,f+2));return this}}SubMesh.prototype.makeRedundant=function(){for(var b=[],c=this.getStride(),a=this.indices.length,d=0;d<a;d++){var e=this.indices[d];if(b[e]){for(var g=e*c,h=this.vertices.length/c,f=0;f<c;f++)this.vertices.push(this.vertices[g+f]);this.indices[d]=h}b[e]=!0}return this};
SubMesh.prototype.toWireFrame=function(){function b(a,b,c,d){if(c<d){var h=c;c=d;d=h}(h=b[c])?0>h.indexOf(d)&&(h.push(d),a.push(c,d)):(b[c]=[d],a.push(c,d))}if(0!=(this.attributeBits&Mesh.PRIMITIVES_BITS))return this;for(var c=[],a={},d=0;d<this.indices.length;d+=3){var e=this.indices[d],g=this.indices[d+1],h=this.indices[d+2];b(c,a,e,g);b(c,a,g,h);b(c,a,h,e)}return new SubMesh(this.vertices,c,this.attributeBits|Mesh.LINES_BIT)};
SubMesh._isIdentityInUpperLeft=function(b){return 1==b[0]&&0==b[1]&&0==b[2]&&0==b[4]&&1==b[5]&&0==b[6]&&0==b[8]&&0==b[9]&&1==b[10]?!0:!1};
SubMesh.prototype.transform=function(b){var c=this.getStride(),a=this.vertices,d=!SubMesh._isIdentityInUpperLeft(b),e=Mesh.normalOffset(this.attributeBits),g=null;0<=e&&d&&(g=GLMath.mat4inverseTranspose3(b));for(var h=0;h<a.length;h+=c){var f=GLMath.mat4transform(b,a[h],a[h+1],a[h+2],1);a[h]=f[0];a[h+1]=f[1];a[h+2]=f[2];0<=e&&d&&(f=GLMath.mat3transform(g,a[h+e],a[h+e+1],a[h+e+2]),GLMath.vec3normInPlace(f),a[h+e]=f[0],a[h+e+1]=f[1],a[h+e+2]=f[2])}return this};
Mesh.prototype.reverseWinding=function(){for(var b=0;b<this.subMeshes.length;b++)this.subMeshes[b].reverseWinding();return this};SubMesh.prototype.reverseWinding=function(){if(0!=(this.attributeBits&Mesh.PRIMITIVES_BITS))return this;for(var b=0;b<this.indices.length;b+=3){var c=this.indices[b+2];this.indices[b+2]=this.indices[b+1];this.indices[b+1]=c}return this};
SubMesh.prototype.recalcNormals=function(b,c){var a=0!=(this.attributeBits&Mesh.ATTRIBUTES_BITS&~Mesh.NORMALS_BIT);this._rebuildVertices(Mesh.NORMALS_BIT);(a||b)&&this.makeRedundant();0!=(this.attributeBits&Mesh.LINES_BIT)?Mesh._recalcNormalsLines(this.vertices,this.indices,this.getStride(),3,b,c):Mesh._recalcNormals(this.vertices,this.indices,this.getStride(),3,b,c);return this};
SubMesh.prototype.setColor3=function(b,c,a){this._rebuildVertices(Mesh.COLORS_BIT);for(var d=this.getStride(),e=Mesh.colorOffset(this.attributeBits);e<this.vertices.length;e+=d)this.vertices[e]=b,this.vertices[e+1]=c,this.vertices[e+2]=a;return this};Mesh.getStride=function(b){return[3,6,6,9,5,8,8,11][b&Mesh.ATTRIBUTES_BITS]};Mesh.normalOffset=function(b){return[-1,3,-1,3,-1,3,-1,3][b&Mesh.ATTRIBUTES_BITS]};Mesh.colorOffset=function(b){return[-1,-1,3,6,-1,-1,3,6][b&Mesh.ATTRIBUTES_BITS]};
Mesh.texCoordOffset=function(b){return[-1,-1,-1,-1,3,6,6,9][b&Mesh.ATTRIBUTES_BITS]};Mesh.ATTRIBUTES_BITS=255;Mesh.PRIMITIVES_BITS=768;Mesh.NORMALS_BIT=1;Mesh.COLORS_BIT=2;Mesh.TEXCOORDS_BIT=4;Mesh.LINES_BIT=256;Mesh.POINTS_BIT=512;Mesh.TRIANGLES=4;Mesh.QUAD_STRIP=8;Mesh.QUADS=7;Mesh.LINES=1;Mesh.TRIANGLE_FAN=6;Mesh.TRIANGLE_STRIP=5;Mesh.LINE_STRIP=3;Mesh.POINTS=0;this.Mesh=Mesh;
(function(b){function c(a){this.order=a;this.n=this.order-1}function a(a){this.order=a.length;if(0>=this.order)throw Error("no control points");this.k=a[0].length;this.points=a;this.evaluator=new c(this.order)}function d(b,c,d){if("undefined"==typeof c&&"undefined"==typeof d)this.uoffset=0,this.umul=1;else{if(c==d)throw Error("u1 and u2 can't be equal");this.uoffset=c;this.umul=1/(d-c)}this.evaluator=new a(b);this.k=this.evaluator.k}function e(b,c,d,e,g){if("undefined"==typeof c&&"undefined"==typeof d&&
"undefined"==typeof e&&"undefined"==typeof g)this.uoffset=0,this.umul=1,this.voffset=0,this.vmul=1;else{if(c==d)throw Error("u1 and u2 can't be equal");if(e==g)throw Error("v1 and v2 can't be equal");this.uoffset=c;this.umul=1/(d-c);this.voffset=e;this.vmul=1/(g-e)}this.evaluator=new a(b);this.k=this.evaluator.k}function g(){this.vertexCurve=this.texCoordCurve=this.normalCurve=this.colorCurve=null}c._binomial=[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1],[1,5,10,10,5,1],[1,6,15,20,15,6,1],[1,7,21,35,35,
21,7,1],[1,8,28,56,70,56,28,8,1],[1,9,36,84,126,126,84,36,9,1],[1,10,45,120,210,252,210,120,45,10,1],[1,11,55,165,330,462,462,330,165,55,11,1],[1,12,66,220,495,792,924,792,495,220,66,12,1],[1,13,78,286,715,1287,1716,1716,1287,715,286,78,13,1],[1,14,91,364,1001,2002,3003,3432,3003,2002,1001,364,91,14,1],[1,15,105,455,1365,3003,5005,6435,6435,5005,3003,1365,455,105,15,1],[1,16,120,560,1820,4368,8008,11440,12870,11440,8008,4368,1820,560,120,16,1],[1,17,136,680,2380,6188,12376,19448,24310,24310,19448,
12376,6188,2380,680,136,17,1],[1,18,153,816,3060,8568,18564,31824,43758,48620,43758,31824,18564,8568,3060,816,153,18,1],[1,19,171,969,3876,11628,27132,50388,75582,92378,92378,75582,50388,27132,11628,3876,969,171,19,1],[1,20,190,1140,4845,15504,38760,77520,125970,167960,184756,167960,125970,77520,38760,15504,4845,1140,190,20,1]];c._factorial=function(a){for(var b=1;1<a;a--)b*=a;return b};c.prototype.getFactor=function(a,b){if(0==b)return Math.pow(1-u,this.n-b);if(b==this.n-1)return Math.pow(u,b)*Math.pow(1-
u,this.n-b);if(this.n<c._binomial.length){var d=Math.pow(u,b)*Math.pow(1-u,this.n-b);return d*c._factorial(this.n)/(c._factorial(b)*c._factorial(this.n-b))}d=Math.pow(u,b)*Math.pow(1-u,this.n-b);return d*c._binomial[this.n][b]};c.prototype.getFactors=function(a,b){for(var c=0;c<this.order;c++)b[c]=this.getFactor(a,c)};a.prototype.evaluate=function(a,b){for(var c=0;c<this.k;c++){for(var d=0,e=0;e<this.order;e++)d+=this.points[e][c]*this.evaluator.getFactor(a,e);b[c]=d}};d.prototype.evaluate=function(a){var b=
[];this.evaluator.evaluate((a-this.uoffset)*this.umul,b);return b};e.prototype.evaluate=function(a,b,c){c=[];this.evaluator.evaluate((a-this.uoffset)*this.umul,(b-this.voffset)*this.vmul,c);return c};g.prototype.vertex=function(a){this.vertexCurve=a;return this};g.prototype.normal=function(a){this.normalCurve=a;return this};g.prototype.color=function(a){this.colorCurve=a;return this};g.prototype.texCoord=function(a){this.texCoordCurve=a;return this};g.prototype.vertexBezier=function(a,b,c){this.vertexCurve=
new d(a,b,c);if(3!=this.vertexCurve.k)throw Error("unsupported vertex length");return this};g.prototype.normalBezier=function(a,b,c){this.normalCurve=new d(a,b,c);if(3!=this.normalCurve.k)throw Error("invalid normal length");return this};g.prototype.texCoordBezier=function(a,b,c){this.texCoordCurve=new d(a,b,c);if(1!=this.texCoordCurve.k&&2!=this.texCoordCurve.k)throw Error("unsupported texcoord length");return this};g.prototype.colorBezier=function(a,b,c){this.colorCurve=new d(a,b,c);if(3!=this.colorCurve.k)throw Error("unsupported color length");
return this};g.prototype.evalOne=function(a,b){var c=null,d=null,e=null;this.colorCurve&&(c=this.colorCurve.evaluate(b));this.texCoordCurve&&(e=this.texCoordCurve.evaluate(b),1==e.length&&e.push(0));this.normalCurve&&(d=this.normalCurve.evaluate(b));if(this.vertexCurve){var g=c?a.color.slice(0,3):null,m=d?a.normal.slice(0,3):null,q=e?a.texCoord.slice(0,3):null;c&&a.color3(c[0],c[1],c[2]);d&&a.normal3(d[0],d[1],d[2]);e&&a.texCoord3(e[0],e[1],e[2]);c=this.vertexCurve.evaluate(b);a.vertex3(c[0],c[1],
c[2]);g&&a.color3(g[0],g[1],g[2]);m&&a.normal3(m[0],m[1],m[2]);q&&a.texCoord3(q[0],q[1],q[2])}return this};g.prototype.evalCurve=function(a,b,c,d,e){"undefined"==typeof c&&(c=24);if(0>=c)throw Error("invalid n");"undefined"==typeof d&&"undefined"==typeof e&&(d=0,e=1);null==b&&(b=Mesh.LINES);e=(e-d)/c;if(b==Mesh.POINTS)a.mode(Mesh.POINTS);else if(b==Mesh.LINES)a.mode(Mesh.LINE_STRIP);else return this;for(b=0;b<=c;b++)this.evalOne(a,d+b*e);return this};this.SurfaceEval=function(){this.vertexSurface=
this.texCoordSurface=this.normalSurface=this.colorSurface=null;this.autoNormal=!1};SurfaceEval.prototype.setAutoNormal=function(a){this.autoNormal=!!a;return this};SurfaceEval.prototype.vertex=function(a){this.vertexSurface=a;return this};SurfaceEval.prototype.normal=function(a){this.normalSurface=a;return this};SurfaceEval.prototype.color=function(a){this.colorSurface=a;return this};SurfaceEval.prototype.texCoord=function(a){this.texCoordSurface=a;return this};SurfaceEval.prototype.vertexBezier=
function(a,b,c,d,g){this.vertexSurface=new e(a,b,c,d,g);if(3!=this.vertexSurface.k)throw Error("unsupported vertex length");return this};SurfaceEval.prototype.normalBezier=function(a,b,c,d,g){this.normalSurface=new e(a,b,c,d,g);if(3!=this.normalSurface.k)throw Error("invalid normal length");return this};SurfaceEval.prototype.texCoordBezier=function(a,b,c,d,g){this.texCoordSurface=new e(a,b,c,d,g);if(1!=this.texCoordSurface.k&&2!=this.texCoordSurface.k)throw Error("unsupported texcoord length");return this};
SurfaceEval.prototype.colorBezier=function(a,b,c,d,g){this.colorSurface=new e(a,b,c,d,g);if(3!=this.colorSurface.k)throw Error("unsupported color length");return this};SurfaceEval.prototype.evalOne=function(a,b,c){var d=null,e=null,g=null;this.colorSurface&&(d=this.colorSurface.evaluate(b,c));this.texCoordSurface&&(g=this.texCoordSurface.evaluate(b,c),1==g.length&&g.push(0));this.normalSurface&&!this.autoNormal&&(e=this.normalSurface.evaluate(b,c));if(this.vertexSurface){var m=d?a.color.slice(0,3):
null,q=e||this.autoNormal?a.normal.slice(0,3):null,r=g?a.texCoord.slice(0,3):null;d&&a.color3(d[0],d[1],d[2]);d=this.vertexSurface.evaluate(b,c);this.autoNormal?(e=this.vertexSurface.evaluate(b+.001,c),b=this.vertexSurface.evaluate(b,c+.001),GLMath.vec3subInPlace(b,d),GLMath.vec3subInPlace(e,d),GLMath.vec3scaleInPlace(e,1E3),GLMath.vec3scaleInPlace(b,1E3),GLMath.vec3normInPlace(e),GLMath.vec3normInPlace(b),0==GLMath.vec3length(e)?e=b:0!=GLMath.vec3length(b)&&(e=GLMath.vec3cross(e,b),GLMath.vec3normInPlace(e)),
a.normal3(e[0],e[1],e[2])):e&&a.normal3(e[0],e[1],e[2]);g&&a.texCoord3(g[0],g[1],g[2]);a.vertex3(d[0],d[1],d[2]);m&&a.color3(m[0],m[1],m[2]);q&&a.normal3(q[0],q[1],q[2]);r&&a.texCoord3(r[0],r[1],r[2])}return this};SurfaceEval.prototype.evalSurface=function(a,b,c,d,e,g,m,q){"undefined"==typeof c&&(c=24);"undefined"==typeof d&&(d=24);if(0>=c)throw Error("invalid un");if(0>=d)throw Error("invalid vn");null==b&&(b=Mesh.TRIANGLES);"undefined"==typeof m&&"undefined"==typeof q&&(m=0,q=1);"undefined"==typeof e&&
"undefined"==typeof g&&(e=0,g=1);g=(g-e)/c;q=(q-m)/d;if(b==Mesh.TRIANGLES)for(b=0;b<d;b++){a.mode(Mesh.TRIANGLE_STRIP);for(var r=0;r<=c;r++){var v=r*g+e;this.evalOne(a,v,b*q+m);this.evalOne(a,v,(b+1)*q+m)}}else if(b==Mesh.POINTS)for(a.mode(Mesh.POINTS),b=0;b<=d;b++)for(r=0;r<=c;r++)v=r*g+e,this.evalOne(a,v,b*q+m);else if(b==Mesh.LINES){for(b=0;b<=d;b++)for(a.mode(Mesh.LINE_STRIP),r=0;r<=c;r++)v=r*g+e,this.evalOne(a,v,b*q+m);for(b=0;b<=c;b++)for(a.mode(Mesh.LINE_STRIP),r=0;r<=d;r++)this.evalOne(a,
b*g+e,r*q+m)}return this}})(this);"undefined"==typeof Meshes&&(Meshes={});
Meshes.createBox=function(b,c,a,d){b*=.5;c*=.5;a*=.5;b=[-b,-c,a,-1,0,0,1,0,-b,c,a,-1,0,0,1,1,-b,c,-a,-1,0,0,0,1,-b,-c,-a,-1,0,0,0,0,b,-c,-a,1,0,0,1,0,b,c,-a,1,0,0,1,1,b,c,a,1,0,0,0,1,b,-c,a,1,0,0,0,0,b,-c,-a,0,-1,0,1,0,b,-c,a,0,-1,0,1,1,-b,-c,a,0,-1,0,0,1,-b,-c,-a,0,-1,0,0,0,b,c,a,0,1,0,1,0,b,c,-a,0,1,0,1,1,-b,c,-a,0,1,0,0,1,-b,c,a,0,1,0,0,0,-b,-c,-a,0,0,-1,1,0,-b,c,-a,0,0,-1,1,1,b,c,-a,0,0,-1,0,1,b,-c,-a,0,0,-1,0,0,b,-c,a,0,0,1,1,0,b,c,a,0,0,1,1,1,-b,c,a,0,0,1,0,1,-b,-c,a,0,0,1,0,0];if(d)for(d=0;d<
b.length;d+=8)b[d+3]=-b[d+3],b[d+4]=-b[d+4],b[d+5]=-b[d+5];return new Mesh(b,[0,1,2,0,2,3,4,5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23],Mesh.NORMALS_BIT|Mesh.TEXCOORDS_BIT)};
Meshes.createCylinder=function(b,c,a,d,e,g,h){var f=new Mesh;null==d&&(d=32);null==e&&(e=1);if(2>=d)throw Error("too few slices");if(1>e)throw Error("too few stacks");if(0>a)throw Error("negative height");if(0>=b&&0>=c||0==a)return f;for(var k=h?-1:1,l=[0,1],n=[0],p=GLMath.PiTimes2,m=1;m<d;m++){var q=1*m/d,r=p*q;l.push(Math.sin(r),Math.cos(r));n.push(q)}l.push(0,1);n.push(1);d*=2;if(0<a)for(p=0,q=b,m=0,b==c?r=0:(m=Math.atan2(b-c,a),r=Math.sin(m)*k,k*=Math.cos(m)),m=0;m<e;m++){var v=p,w=(m+1)/e,x=
a*v,H=a*w,B=q,D=b+(c-b)*w,p=w,q=D;f.mode(Mesh.TRIANGLE_STRIP);f.texCoord2(1,v);f.normal3(0,k,r);f.vertex3(0,B,x);f.texCoord2(1,w);f.normal3(0,k,r);f.vertex3(0,D,H);for(var A=2,K=1;A<=d;A+=2,K++){var y=n[K],t,C;t=l[A];C=l[A+1];f.texCoord2(1-y,v);f.normal3(t*k,C*k,r);f.vertex3(t*B,C*B,x);f.texCoord2(1-y,w);f.normal3(t*k,C*k,r);f.vertex3(t*D,C*D,H)}}return g?f.recalcNormals(g,h):f};
Meshes.createClosedCylinder=function(b,c,a,d,e,g,h){e=Meshes.createCylinder(b,c,a,d,e,g,h);b=Meshes.createDisk(0,b,d,2,!h).reverseWinding();c=Meshes.createDisk(0,c,d,2,h);c.transform(GLMath.mat4translated(0,0,a));return e.merge(b).merge(c)};Meshes.createDisk=function(b,c,a,d,e){return Meshes.createPartialDisk(b,c,a,d,0,360,e)};
Meshes.createPartialDisk=function(b,c,a,d,e,g,h){var f=new Mesh;null==a&&(a=32);null==d&&(d=1);null==e&&(e=0);null==g&&(g=360);if(2>=a)throw Error("too few slices");if(1>d)throw Error("too few loops");if(b>c)throw Error("inner greater than outer");0>b&&(b=0);0>c&&(c=0);if(0==c||0==g)return f;var k=360==g&&0==e,l=0>g?-1:1;0>g&&(g=-g);g%=360;0==g&&(g=360);var n=[],p=[],m=GLMath.PiTimes2;g=360==g?m:g*GLMath.PiDividedBy180;e*=GLMath.PiDividedBy180;0>l&&(g=-g);for(l=0;l<=a;l++){var q=1*l/a,r=e+g*q,r=0>
r?m- -r%m:r%m;n.push(Math.sin(r),Math.cos(r));p.push(q)}k&&(n[0]=0,n[1]=1,n[n.length-1]=1,n[n.length-2]=0,p[0]=0,p[p.length-1]=1);a*=2;e=c-b;k=b;h?f.normal3(0,0,-1):f.normal3(0,0,1);for(l=0;l<d;l++)if(h=k,p=b+(l+1)/d*e,m=h/c,g=p/c,k=p,q=0==l&&0==b,f.mode(q?Mesh.TRIANGLE_FAN:Mesh.TRIANGLE_STRIP),q)for(q=a,r=a/2;0<=q;q-=2,r--){var v,w;v=n[q];w=n[q+1];q==a&&(f.texCoord2(.5*(1+v*m),.5*(1+w*m)),f.vertex3(v*h,w*h,0));f.texCoord2(.5*(1+v*g),.5*(1+w*g));f.vertex3(v*p,w*p,0)}else for(r=q=0;q<=a;q+=2,r++)v=
n[q],w=n[q+1],f.texCoord2(.5*(1+v*g),.5*(1+w*g)),f.vertex3(v*p,w*p,0),f.texCoord2(.5*(1+v*m),.5*(1+w*m)),f.vertex3(v*h,w*h,0);return f};
Meshes.createTorus=function(b,c,a,d,e,g){var h=new Mesh;null==d&&(d=16);null==a&&(a=16);if(3>d)throw Error("crosswise is less than 3");if(3>a)throw Error("lengthwise is less than 3");if(0>b||0>c)throw Error("inner or outer is less than 0");if(0==c||0==b)return h;for(var f=GLMath.PiTimes2,k=[],l=[],n=0;n<=d;n++){var p=n*f/d;k.push(Math.sin(p),Math.cos(p))}for(n=0;n<=a;n++)p=n*f/a,l.push(Math.sin(p),Math.cos(p));for(f=0;f<a;f++){var m=f/a,q=(f+1)/a,r=l[2*f],v=l[2*f+1],w=l[2*f+2],x=l[2*f+3];h.mode(Mesh.TRIANGLE_STRIP);
for(n=0;n<=d;n++){var p=n/d,H=k[2*n],B=k[2*n+1],D=B*(c+x*b),A=H*(c+x*b),K=w*b,y=x*B,t=x*H,C=w;h.normal3(y,t,C);h.texCoord2(p,q);h.vertex3(D,A,K);D=B*(c+v*b);A=H*(c+v*b);K=r*b;y=v*B;t=v*H;C=r;h.normal3(y,t,C);h.texCoord2(p,m);h.vertex3(D,A,K)}}return e?h.recalcNormals(e,g):h};
Meshes.createPlane=function(b,c,a,d,e){var g=new Mesh;null==b&&(b=1);null==c&&(c=1);null==a&&(a=1);null==d&&(d=1);if(0>b||0>c)throw Error("width or height is less than 0");if(0>=d||0>=a)throw Error("widthDiv or heightDiv is 0 or less");if(0==b||0==c)return g;var h=.5*-b,f=.5*-c;e?g.normal3(0,0,-1):g.normal3(0,0,1);for(e=0;e<d;e++){g.mode(Mesh.TRIANGLE_STRIP);var k=e/d,l=(e+1)/d,n=f+c*k,p=f+c*l;g.texCoord2(0,l);g.vertex3(h,p,0);g.texCoord2(0,k);g.vertex3(h,n,0);for(var m=0;m<a;m++){var q=(m+1)/a,r=
h+b*q;g.texCoord2(q,l);g.vertex3(r,p,0);g.texCoord2(q,k);g.vertex3(r,n,0)}}return g};Meshes.createSphere=function(b,c,a,d,e){return Meshes._createCapsule(b,0,c,a,1,d,e)};Meshes.createCapsule=function(b,c,a,d,e,g,h){null==d&&(d=8);if(1>d)throw Error("too few stacks");return Meshes._createCapsule(b,c,a,2*d,e,g,h)};
Meshes._createCapsule=function(b,c,a,d,e,g,h){function f(a,b,c,d,e,f){a.normal3(c*b,d*b,e*b);a.vertex3(c,d,e+f)}var k=new Mesh;null==a&&(a=16);null==d&&(d=16);null==e&&(e=1);null==b&&(b=1);null==c&&(c=1);if(2>d)throw Error("too few stacks");if(2>=a)throw Error("too few slices");if(1>e&&0<c)throw Error("too few middle stacks");if(0>c)throw Error("negative length");if(0>b)throw Error("negative radius");if(0==b)return k;for(var l=.5*c,n=d/2,p=h?-1:1,m=[0,1],q=[],r=[],v=[0],w=GLMath.PiTimes2,x=1;x<a;x++){var H=
1*x/a,B=w*H;m.push(Math.sin(B),Math.cos(B));v.push(H)}m.push(0,1);v.push(1);w=2*b;w/=w+c;H=[];for(x=1;x<d;x++){var D=1*x/d,B=Math.PI*D,A=Math.sin(B);q.push(A);H.push(-Math.cos(B));r.push(D)}q.push(0);r.push(1);H.push(1);a*=2;for(var B=-1,K=D=0,x=0;x<d;x++){var y=H[x],t=r[x],A=b*B,C=b*y,I=x<n?-l:l,L=D,F=b*q[x],O=K,P=t;0<c&&(O=x<n?K*w:1-(1-K)*w,P=x<n?t*w:1-(1-t)*w);B=y;K=t;D=F;x==d-1||0==x?k.mode(Mesh.TRIANGLES):(k.mode(Mesh.TRIANGLE_STRIP),k.texCoord2(1,O),f(k,p,0,L,A,I),k.texCoord2(1,P),f(k,p,0,F,
C,I));for(var N=0,Q=0,G=1,y=2,t=1;y<=a;y+=2,t++){var M=v[t],E,J;x==d-1?(E=N+.5*(M-N),k.texCoord2(1-N,O),f(k,p,Q*L,G*L,A,I),k.texCoord2(1-E,P),f(k,p,0,F,C,I),E=m[y],J=m[y+1],k.texCoord2(1-M,O),f(k,p,E*L,J*L,A,I),Q=E,G=J,N=M):0==x?(E=N+.5*(M-N),k.texCoord2(1-E,O),f(k,p,0,L,A,I),k.texCoord2(1-N,P),f(k,p,Q*F,G*F,C,I),E=m[y],J=m[y+1],k.texCoord2(1-M,P),f(k,p,E*F,J*F,C,I),Q=E,G=J,N=M):(E=m[y],J=m[y+1],k.texCoord2(1-M,O),f(k,p,E*L,J*L,A,I),k.texCoord2(1-M,P),f(k,p,E*F,J*F,C,I))}if(x+1==n&&0<c)for(I=.5*w,
L=2*l,N=1-I,Q=1-w,G=0;G<e;G++){var A=-l+(0==G?0:L*G/e),R=G==e-1?l:-l+L*(G+1)/e,O=I+(0==G?0:Q*G/e),P=G==e-1?N:I+Q*(G+1)/e;k.mode(Mesh.TRIANGLE_STRIP);k.texCoord2(1,O);f(k,p,0,F,C,A);k.texCoord2(1,P);f(k,p,0,F,C,R);y=2;for(t=1;y<=a;y+=2,t++)M=v[t],E=m[y],J=m[y+1],k.texCoord2(1-M,O),f(k,p,E*F,J*F,C,A),k.texCoord2(1-M,P),f(k,p,E*F,J*F,C,R)}}return g?k.recalcNormals(g,h):k.normalizeNormals()};this.Meshes=Meshes;
var ShaderProgram=function(b,c,a){b=b.getContext?b.getContext():b;null==c&&(c=ShaderProgram.getDefaultVertex());null==a&&(a=ShaderProgram.getDefaultFragment());this.program=ShaderProgram._compileShaders(b,c,a);this.attributes={};this.context=b;this.actives={};this.uniformValues={};this.uniformTypes={};this.savedUniforms={};if(null!=this.program){this.attributes=[];var d=null;c={};a=b.getProgramParameter(this.program,b.ACTIVE_ATTRIBUTES);for(var e=0;e<a;++e)if(d=b.getActiveAttrib(this.program,e),null!==
d){var d=d.name,g=b.getAttribLocation(this.program,d);0<=g&&(this.attributes.push(g),c[d]=g)}a=b.getProgramParameter(this.program,b.ACTIVE_UNIFORMS);for(e=0;e<a;++e)g=b.getActiveUniform(this.program,e),null!==g&&(d=g.name,c[d]=b.getUniformLocation(this.program,d),this.uniformTypes[d]=g.type);this.actives=c}};ShaderProgram.prototype.dispose=function(){this.program&&this.context.deleteProgram(this.program);this.program=this.context=null;this.actives={};this.attributes={};this.uniformTypes={}};
ShaderProgram.prototype.getContext=function(){return this.context};ShaderProgram.prototype.get=function(b){b=this.actives[b];return null==b?null:b};ShaderProgram.prototype.getUniform=function(b){var c="string"==typeof b?this.get(b):b;if(null==c||"number"==typeof c)return null;b=this.uniformValues[b];return null==b?this.context.getUniform(this.program,c):b instanceof Array?b.slice(0,b.length):b};
ShaderProgram.prototype.use=function(){this.context.useProgram(this.program);this.setUniforms(this.savedUniforms);this.savedUniforms={};return this};ShaderProgram.prototype._log=function(b,c){};ShaderProgram.prototype._saveIfNotCurrent=function(b,c,a){this._log(c,b);null==a&&(a=this.context.getParameter(this.context.CURRENT_PROGRAM)==this.program);a||(this.savedUniforms[c]="number"==typeof b?b:b.slice(0,b.length),this.uniformValues[c]=null);return a};
ShaderProgram.prototype._setUniform=function(b,c,a){a=null;b=b[c];var d=this.get(c);if(null===d)return a;var e=this.uniformValues[c];if("number"==typeof b){var g=!1;null==e?(this.uniformValues[c]=e=b,g=!0):e!=b&&(e=b,this.uniformValues[c]=b,g=!0);if(g)if(this.uniformTypes[c]==this.context.FLOAT){if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform1f(d,e)}else{if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform1i(d,e)}}else if(3==b.length)if(!e){this.uniformValues[c]=
e=b.slice(0,b.length);if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform3fv(d,e)}else{if(e[0]!=b[0]||e[1]!=b[1]||e[2]!=b[2]){e[0]=b[0];e[1]=b[1];e[2]=b[2];if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform3fv(d,e)}}else if(2==b.length)if(!e){this.uniformValues[c]=e=b.slice(0,b.length);if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform2fv(d,e)}else{if(e[0]!=b[0]||e[1]!=b[1]){e[0]=b[0];e[1]=b[1];if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform2fv(d,
e)}}else if(4==b.length)if(!e){this.uniformValues[c]=e=b.slice(0,b.length);if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform4fv(d,e)}else{if(e[0]!=b[0]||e[1]!=b[1]||e[2]!=b[2]||e[3]!=b[3]){e[0]=b[0];e[1]=b[1];e[2]=b[2];e[3]=b[3];if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniform4fv(d,e)}}else if(16==b.length)if(!e){this.uniformValues[c]=e=b.slice(0,b.length);if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniformMatrix4fv(d,!1,e)}else{if(ShaderProgram._copyIfDifferent(b,
e,16)){if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniformMatrix4fv(d,!1,e)}}else if(9==b.length)if(!e){this.uniformValues[c]=e=b.slice(0,b.length);if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniformMatrix3fv(d,!1,e)}else if(ShaderProgram._copyIfDifferent(b,e,9)){if(!(a=this._saveIfNotCurrent(e,c,a)))return a;this.context.uniformMatrix3fv(d,!1,e)}return a};
ShaderProgram.prototype.setUniforms=function(b){var c=null;if("undefined"!==typeof Object.keys)for(var a=Object.keys(b),d=0;d<a.length;d++)var e=a[d],c=this._setUniform(b,e,c);else for(e in b)c=this._setUniform(b,e,c);return this};ShaderProgram._copyIfDifferent=function(b,c,a){for(var d=0;d<a;d++)if(b[d]!=c[d]){c[d]=b[d];for(d+=1;d<a;d++)c[d]=b[d];return!0}return!1};
ShaderProgram._compileShaders=function(b,c,a){function d(a,b,c){var d=a.createShader(b);a.shaderSource(d,c);a.compileShader(d);if(!a.getShaderParameter(d,a.COMPILE_STATUS)){c=c.split("\n");for(var e=0;e<c.length;e++)c[e]="/* "+(e+1)+" */   "+c[e];console.log(c.join("\n"));console.log((b==a.VERTEX_SHADER?"vertex: ":"fragment: ")+a.getShaderInfoLog(d));return null}return d}c=c&&0!=c.length?d(b,b.VERTEX_SHADER,c):null;a=a&&0!=a.length?d(b,b.FRAGMENT_SHADER,a):null;var e=null;null!==c&&null!==a&&(e=b.createProgram(),
b.attachShader(e,c),b.attachShader(e,a),b.linkProgram(e),b.getProgramParameter(e,b.LINK_STATUS)||(console.log("link: "+b.getProgramInfoLog(e)),b.deleteProgram(e),e=null),b.detachShader(e,c),b.detachShader(e,a));null!==c&&b.deleteShader(c);null!==a&&b.deleteShader(a);return e};ShaderProgram.fragmentShaderHeader=function(){return"#ifdef GL_ES\n#ifndef GL_FRAGMENT_PRECISION_HIGH\nprecision mediump float;\n#else\nprecision highp float;\n#endif\n#endif\n"};
ShaderProgram.makeEffectFragment=function(b){var c=ShaderProgram.fragmentShaderHeader(),c=c+"uniform sampler2D sampler;\nuniform vec2 textureSize;\nvarying vec2 uvVar;\nvarying vec3 colorAttrVar;\n"+b;return c+="\n\nvoid main(){\n // normalize coordinates to 0..1\n vec2 uv=gl_FragCoord.xy/textureSize.xy;\n gl_FragColor=textureEffect(sampler,uv,textureSize);\n}"};ShaderProgram.makeEffect=function(b,c){return new ShaderProgram(b,ShaderProgram.getBasicVertex(),ShaderProgram.makeEffectFragment(c))};
ShaderProgram.getInvertEffect=function(b){return ShaderProgram.makeEffect(b,"vec4 textureEffect(sampler2D sampler, vec2 uvCoord, vec2 textureSize){\n vec4 color=texture2D(sampler,uvCoord);\n vec4 ret; ret.xyz=vec3(1.0,1.0,1.0)-color.xyz; ret.w=color.w; return ret;\n}")};ShaderProgram.getEdgeDetectEffect=function(b){return ShaderProgram.makeEffect(b,"float luma(vec3 color) {\n return 0.2126 * color.r + 0.7152 * color.g + 0.0722 * color.b;\n}\nconst vec4 edge_color=vec4(0.,0,0,1);\nconst vec4 back_color=vec4(1.,1,1,1);\nvec4 textureEffect(sampler2D sampler, vec2 uvCoord, vec2 textureSize){\nfloat dx = 1.0 / float(textureSize.x);\nfloat dy = 1.0 / float(textureSize.y);\nfloat s00 = luma(texture2D(sampler, uvCoord + vec2(-dx,dy)).rgb);\nfloat s10 = luma(texture2D(sampler, uvCoord + vec2(-dx,0.0)).rgb);\nfloat s20 = luma(texture2D(sampler, uvCoord + vec2(-dx,-dy)).rgb);\nfloat s01 = luma(texture2D(sampler, uvCoord + vec2(0.0,dy)).rgb);\nfloat s21 = luma(texture2D(sampler, uvCoord + vec2(0.0,-dy)).rgb);\nfloat s02 = luma(texture2D(sampler, uvCoord + vec2(dx, dy)).rgb);\nfloat s12 = luma(texture2D(sampler, uvCoord + vec2(dx, 0.0)).rgb);\nfloat s22 = luma(texture2D(sampler, uvCoord + vec2(dx, -dy)).rgb);\nfloat sx = s00 + 2.0 * s10 + s20 - (s02 + 2.0 * s12 + s22);\nfloat sy = s00 + 2.0 * s01 + s02 - (s20 + 2.0 * s21 + s22);\nfloat dist = sx * sx + sy * sy;\nif(dist > 0.4) {\nreturn edge_color;\n} else {\nreturn back_color;\n}}")};
ShaderProgram.getBasicVertex=function(){};ShaderProgram.getDefaultVertex=function(){return"attribute vec3 position;\nattribute vec3 normal;\nattribute vec2 uv;\nattribute vec3 colorAttr;\nuniform mat4 world;\nuniform mat4 view;\nuniform mat4 projection;\nvarying vec2 uvVar;\nvarying vec3 colorAttrVar;\n#ifdef SHADING\nuniform mat3 worldViewInvTrans3; /* internal */\nvarying vec4 worldPositionVar;\nvarying vec3 transformedNormalVar;\n#endif\nvoid main(){\nvec4 positionVec4;\npositionVec4.w=1.0;\npositionVec4.xyz=position;\ngl_PointSize=1.0;\ngl_Position=((projection*view)*world)*positionVec4;\ncolorAttrVar=colorAttr;\nuvVar=uv;\n#ifdef SHADING\ntransformedNormalVar=normalize(worldViewInvTrans3*normal);\nworldPositionVar=world*positionVec4;\n#endif\n}"};
ShaderProgram.getDefaultFragment=function(){for(var b=ShaderProgram.fragmentShaderHeader()+"uniform vec4 md;\n#ifdef SHADING\nstruct light {\n vec4 position; /* source light direction */\n vec4 diffuse; /* source light diffuse color */\n#ifdef SPECULAR\n vec4 specular; /* source light specular color */\n#endif\n};\nconst int MAX_LIGHTS = "+Lights.MAX_LIGHTS+"; /* internal */\nuniform vec3 sceneAmbient;\nuniform light lights[MAX_LIGHTS];\nuniform vec3 ma;\nuniform vec3 me;\n#ifdef SPECULAR\nuniform vec3 ms;\nuniform float mshin;\nuniform vec4 viewInvW;\n#endif\n#endif\nuniform sampler2D sampler;\nuniform vec2 textureSize;\nuniform float useColorAttr;\nvarying vec2 uvVar;\nvarying vec3 colorAttrVar;\n#ifdef SHADING\nvarying vec4 worldPositionVar;\nvarying vec3 transformedNormalVar;\nvec4 calcLightPower(light lt, vec4 vertexPosition){\n vec3 sdir;\n float attenuation;\n if(lt.position.w == 0.0){ /* directional light */\n  sdir=normalize((lt.position).xyz);\n  attenuation=1.0;\n } else { /* point light */\n  vec3 vertexToLight=(lt.position-vertexPosition).xyz;\n  float dist=length(vertexToLight);\n  if(dist==0.0){\n   sdir=vertexToLight;\n   attenuation=1.0;\n  } else {\n   sdir=vertexToLight/dist; /* normalizes vertexToLight */\n   attenuation=(1.0/dist);\n  }\n }\n return vec4(sdir,attenuation);\n}\n#endif\nvoid main(){\n vec4 tmp;\n float useTexture=sign(textureSize.x+textureSize.y);\n tmp.w=1.0;\n tmp.xyz=colorAttrVar;\n vec4 baseColor=mix(mix(\n#ifdef SHADING\n   vec4(1.0,1.0,1.0,md.a), /*when textures are not used*/\n#else\n   md, /*when textures are not used*/\n#endif\n   texture2D(sampler,uvVar), /*when textures are used*/\n   useTexture), tmp, useColorAttr);\n#ifdef SHADING\n#define SET_LIGHTPOWER(i)  lightPower[i]=calcLightPower(lights[i],worldPositionVar)\n#define ADD_DIFFUSE(i)  lightedColor+=vec3(lights[i].diffuse)*max(lightCosines[i],0.0)*lightPower[i].w*materialDiffuse;\nvec4 lightPower["+
Lights.MAX_LIGHTS+"];\nfloat lightCosines["+Lights.MAX_LIGHTS+"];\n",b=b+"if(baseColor.a==0.0)discard;\nvec3 materialAmbient=mix(ma,baseColor.rgb,sign(useColorAttr+useTexture)); /* ambient*/\nvec3 lightedColor=sceneAmbient*materialAmbient; /* ambient*/\n // diffuse\n vec3 materialDiffuse=vec3(md)*baseColor.rgb;\n",c=0;c<Lights.MAX_LIGHTS;c++)b+="SET_LIGHTPOWER("+c+");\n",b+="lightCosines["+c+"]=dot(transformedNormalVar,lightPower["+c+"].xyz);\n";for(c=0;c<Lights.MAX_LIGHTS;c++)b+="ADD_DIFFUSE("+c+
");\n";b+="#ifdef SPECULAR\nbool spectmp;\n// specular reflection\nif((ms.x*ms.y*ms.z)!=0.0){\nvec3 viewDirection=normalize((viewInvW-worldPositionVar).xyz);\nfloat specular;\n";for(c=0;c<Lights.MAX_LIGHTS;c++)b+="  spectmp = lightCosines["+c+"] >= 0.0;\n  if (spectmp) {\n  vec3 lightSpecular=vec3(lights["+c+"].specular);\n    specular=dot (-lightPower["+c+"].xyz - (2.0 * dot (transformedNormalVar, -lightPower["+c+"].xyz)*\n transformedNormalVar), viewDirection);\n    specular=max(specular,0.0);\n    specular=pow(specular,mshin);\n    lightedColor+=ms*specular*lightPower["+
c+"].w*lightSpecular;\n  }\n";b+="}\n#endif\n";return b+=" // emission\n lightedColor+=me;\n baseColor=vec4(lightedColor,baseColor.a);\n#endif\n gl_FragColor=baseColor;\n}"};
