/*
 CC0-1.0
 CC0-1.0
*/
function p(b){if(!b.Promise){var d=function(a){this.W=0;this.ab=this.ua=null;this.Ja={Kb:[],Vb:[]};this.sa=[];a&&this.ac(a)};d.resolve=function(a){return new this(function(c){c(a)})};d.reject=function(a){return new this(function(c,b){b(a)})};d.s=d.T=function(a){return new this(function(c,b){var d=0,e=[];a.forEach(function(a,h){d++;a.then(function(a){e[h]=a;d--;d||c(e)},function(a){d=1/0;b(a)})})})};d.G=function(a){return new this(function(c,b){a.forEach(function(a){a.then(c,b)})})};d.prototype.then=
function(a,c){this.Ja.Kb.push(a);this.Ja.Vb.push(c);var b=new d;this.sa.push(b);0<this.W&&this.f();return b};d.prototype.fb=function(a){0==this.W&&(this.W=1,this.ua=a,this.sa.length&&this.f())};d.prototype.reject=function(a){if(0!=this.W)return this;this.W=2;this.ua=a;this.sa.length&&this.f();return this};d.prototype.resolve=function(a){if(a==this)this.reject(new TypeError("Promise resolved by its own instance"));else if(a instanceof this.constructor)a.hc(this);else if(null===a||"object"!=typeof a&&
"function"!=typeof a)this.fb(a);else{try{var c=a.then}catch(b){this.reject(b);return}if("function"==typeof c){var d=!1,e=function(a){d||(d=!0,this.resolve(a))},g=function(a){d||(d=!0,this.reject(a))};try{c.call(a,e.bind(this),g.bind(this))}catch(h){d||this.reject(h)}}else this.fb(a)}};d.prototype.hc=function(a){this.then(function(c){a.resolve(c)},function(c){a.reject(c)})};d.prototype["catch"]=function(a){return this.then(null,a)};d.prototype.f=function(){this.ab||(this.ab=setTimeout(this.G.bind(this),
0))};d.prototype.G=function(){for(this.ab=null;this.sa.length;){var a=this.Ja.Kb.shift(),c=this.Ja.Vb.shift();this.s(1==this.W?a:c)}};d.prototype.s=function(a){var c=this.sa.shift();if("function"!=typeof a)1==this.W?c.fb(this.ua):c.reject(this.ua);else try{var b=a(this.ua);c.resolve(b)}catch(d){c.reject(d)}};d.prototype.ac=function(a){try{a(this.resolve.bind(this),this.reject.bind(this))}catch(c){this.reject(c)}};b.Promise=d}}
"function"===typeof define&&define.amd?define(["exports"],p):"object"===typeof exports?p(exports):p(this);
function aa(b){if(!b.hd){var d={Da:function(a,c){return[a[1]*c[2]-a[2]*c[1],a[2]*c[0]-a[0]*c[2],a[0]*c[1]-a[1]*c[0]]},na:function(a,c){return a[0]*c[0]+a[1]*c[1]+a[2]*c[2]},od:function(a,c){return[a[0]+c[0],a[1]+c[1],a[2]+c[2]]},vd:function(a,c){return[a[0]-c[0],a[1]-c[1],a[2]-c[2]]},pd:function(a,c){var b=c[1],d=c[2];a[0]+=c[0];a[1]+=b;a[2]+=d;return a},xd:function(a,c){var b=c[1],d=c[2];a[0]-=c[0];a[1]-=b;a[2]-=d;return a},td:function(a,c){var b=c[1],d=c[2];a[0]*=c[0];a[1]*=b;a[2]*=d;return a},
cd:function(a,c){a[0]*=c;a[1]*=c;a[2]*=c;return a},ud:function(a,c){return d.cd([a[0],a[1],a[2]],c)},sd:function(a,c,b){return[a[0]+(c[0]-a[0])*b,a[1]+(c[1]-a[1])*b,a[2]+(c[2]-a[2])*b]},ed:function(a,c){return a[0]*c[0]+a[1]*c[1]+a[2]*c[2]+a[3]*c[3]},Yb:function(a,c){a[0]*=c;a[1]*=c;a[2]*=c;a[3]*=c;return a},zd:function(a,c,b){return[a[0]+(c[0]-a[0])*b,a[1]+(c[1]-a[1])*b,a[2]+(c[2]-a[2])*b,a[3]+(c[3]-a[3])*b]},Ea:function(a){var c=a[0],b=a[1],d=a[2];len=Math.sqrt(c*c+b*b+d*d);0!=len&&(len=1/len,a[0]*=
len,a[1]*=len,a[2]*=len);return a},Xb:function(a){var c=a[0],b=a[1],d=a[2],e=a[3];len=Math.sqrt(c*c+b*b+d*d+e*e);0!=len&&(len=1/len,a[0]*=len,a[1]*=len,a[2]*=len,a[3]*=len);return a},bd:function(a){return d.Ea([a[0],a[1],a[2]])},gd:function(a){return d.Xb([a[0],a[1],a[2],a[3]])},ad:function(a){var c=a[0],b=a[1];a=a[2];return Math.sqrt(c*c+b*b+a*a)},fd:function(a){var c=a[0],b=a[1],d=a[2];a=a[3];return Math.sqrt(c*c+b*b+d*d+a*a)},f:function(){return[1,0,0,0,1,0,0,0,1]},G:function(){return[1,0,0,0,
0,1,0,0,0,0,1,0,0,0,0,1]},vb:function(){return[0,0,0,1]},Mb:function(a){return a.slice(0,16)},rd:function(a){return a.slice(0,3)},dd:function(a){return a.slice(0,4)},qd:function(a,c){a[0]=c[0];a[1]=c[1];a[2]=c[2];return a},yd:function(a,c){a[0]=c[0];a[1]=c[1];a[2]=c[2];a[3]=c[3];return a},Ob:function(a){return 1==a[0]&&0==a[1]&&0==a[2]&&0==a[3]&&0==a[4]&&1==a[5]&&0==a[6]&&0==a[7]&&0==a[8]&&0==a[9]&&1==a[10]&&0==a[11]&&0==a[12]&&0==a[13]&&0==a[14]&&1==a[15]},zc:function(a){var c=a[0]*a[10],b=a[0]*
a[11],d=a[0]*a[5],e=a[0]*a[6],g=a[0]*a[7],h=a[0]*a[9],l=a[10]*a[12],m=a[10]*a[13],n=a[10]*a[15],q=a[11]*a[12],r=a[11]*a[13],t=a[11]*a[14],w=a[1]*a[4],v=a[1]*a[6],u=a[1]*a[7],D=a[1]*a[8],E=a[2]*a[4],I=a[2]*a[5],A=a[2]*a[7],V=a[2]*a[8],B=a[2]*a[9],x=a[3]*a[4],N=a[3]*a[5],H=a[3]*a[6],K=a[3]*a[8],F=a[3]*a[9],O=a[4]*a[9],P=a[5]*a[8],M=a[6]*a[8],S=a[6]*a[9],G=a[7]*a[8],L=a[7]*a[9],C=w-d,J=v-I,X=u-N,ba=E-e,d=d-w,v=I-v,I=A-H,w=x-g,u=N-u,A=H-A,e=e-E,E=g-x,g=a[9]*a[12]*A+l*X+q*v+a[8]*a[13]*I+m*w+r*e+a[8]*a[14]*
u+a[9]*a[14]*E+t*C+a[8]*a[15]*J+a[9]*a[15]*ba+n*d;if(0==g)return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];g=1/g;x=[];x[0]=a[6]*r-a[7]*m+L*a[14]-a[5]*t-S*a[15]+a[5]*n;x[1]=a[3]*m-a[2]*r-F*a[14]+a[1]*t+B*a[15]-a[1]*n;x[2]=a[13]*I+a[14]*u+a[15]*J;x[3]=a[9]*A+a[10]*X+a[11]*v;x[4]=a[7]*l-a[6]*q-G*a[14]+a[4]*t+M*a[15]-a[4]*n;x[5]=a[2]*q-a[3]*l+a[14]*(K-b)+a[15]*(c-V);x[6]=a[12]*A+a[14]*E+a[15]*ba;x[7]=a[8]*I+a[10]*w+a[11]*e;x[8]=a[5]*q-L*a[12]+G*a[13]-a[4]*r+a[15]*(O-P);x[9]=F*a[12]-a[1]*q+a[13]*(b-K)+a[15]*(D-
h);x[10]=a[12]*X+a[13]*w+a[15]*d;x[11]=a[8]*u+a[9]*E+a[11]*C;x[12]=S*a[12]-a[5]*l-M*a[13]+a[4]*m+a[14]*(P-O);x[13]=a[1]*l-B*a[12]+a[13]*(V-c)+a[14]*(h-D);x[14]=a[12]*v+a[13]*e+a[14]*C;x[15]=a[8]*J+a[9]*ba+a[10]*d;for(a=0;16>a;a++)x[a]*=g;return x},Sb:function(a){return[-a[0],-a[1],-a[2],a[3]]},xb:function(a){var c=1/d.kb(a,a);return d.Yb(d.Sb(a),c)},wb:function(a){return d.lb(d.Sb(a))},Ub:function(a){return 0==a[0]&&0==a[1]&&0==a[2]&&1==a[3]},Kc:function(a){var c,b,d,e,g,h,l,m,n;c=2*a[0];b=2*a[1];
d=2*a[2];e=c*a[0];g=c*a[1];h=c*a[2];l=b*a[1];m=d*a[1];n=d*a[2];c*=a[3];b*=a[3];a=d*a[3];return[1-(l+n),g+a,h-b,0,g-a,1-(e+n),m+c,0,h+b,m-c,1-(e+l),0,0,0,0,1]},kd:function(a){var c=a[3],b=1-c*c;return 0<b?(b=1/Math.sqrt(b),[a[0]*b,a[1]*b,a[2]*b,Math.acos(c)*d.Ab]):[0,1,0,0]},ub:function(a,c){var b=d.Da(a,c),f=Math.sqrt(d.na(a,a))*Math.sqrt(d.na(c,c));0==f&&(f=1);b[3]=f+d.na(a,c);return d.lb(b)},Tb:function(a,c,b,f){var e;"undefined"!=typeof b&&"undefined"!=typeof f?(e=c,c=f,f=(0<=a&&360>a?a:a%360+
(0>a?360:0))*d.D):"undefined"==typeof c?(e=a[0],b=a[1],c=a[2],f=(0<=a&&360>a?a:a%360+(0>a?360:0))*d.D):(e=c[0],b=c[1],c=c[2],f=(0<=a&&360>a?a:a%360+(0>a?360:0))*d.D);a=Math.cos(f);f=Math.sin(f);e=d.Ea([e,b,c]);e=[e[0],e[1],e[2],a];e[0]*=f;e[1]*=f;e[2]*=f;return e},Ic:function(a,c,b,f){var e,g;null==f&&(f=d.pa);if(0>f||6<=f)throw Error("invalid mode");a.constructor==Array?(b=(0<=a[2]&&360>a[2]?a[2]:a[2]%360+(0>a[2]?360:0))*d.D,e=(0<=a[0]&&360>a[0]?a[0]:a[0]%360+(0>a[0]?360:0))*d.D,g=(0<=a[1]&&360>
a[1]?a[1]:a[1]%360+(0>a[1]?360:0))*d.D):(b=(0<=b&&360>b?b:b%360+(0>b?360:0))*d.D,e=(0<=a&&360>a?a:a%360+(0>a?360:0))*d.D,g=(0<=c&&360>c?c:c%360+(0>c?360:0))*d.D);a=Math.sin(e);e=Math.cos(e);c=Math.sin(g);g=Math.cos(g);var h=Math.sin(b);b=Math.cos(b);if(f==d.Ha||f==d.Ya){var l=[h*c,b*c,h*g,b*g];f==d.Ha&&(l[0]=-l[0]);f=[l[3]*a+l[0]*e,l[1]*e+l[2]*a,l[2]*e-l[1]*a,l[3]*e-l[0]*a]}else f==d.Za||f==d.Ia?(l=[b*a,h*a,h*e,b*e],f==d.Ia&&(l[1]=-l[1]),f=[l[0]*g-l[2]*c,l[3]*c+l[1]*g,l[2]*g+l[0]*c,l[3]*g-l[1]*c]):
(l=[g*a,c*e,c*a,g*e],f==d.pa&&(l[2]=-l[2]),f=[l[0]*b+l[1]*h,l[1]*b-l[0]*h,l[3]*h+l[2]*b,l[3]*b-l[2]*h]);return f},Lc:function(a,c){var b=a[3],f,e,g,h=1;null==c&&(c=d.pa);if(0>c||6<=c)throw Error("invalid mode");c==d.pa?(f=a[1],e=a[0],g=a[2],h=-1):c==d.Ha?(f=a[2],e=a[1],g=a[0],h=-1):c==d.Ya?(f=a[1],e=a[2],g=a[0]):c==d.Za?(f=a[2],e=a[0],g=a[1]):c==d.Ia?(f=a[0],e=a[2],g=a[1],h=-1):(f=a[0],e=a[1],g=a[2]);var l=e*e,m=Math.atan2(2*(b*f-h*e*g),1-2*(f*f+l)),n=2*(b*e+h*f*g);1<n&&(n=1);-1>n&&(n=-1);n=Math.asin(n);
e=Math.atan2(2*(b*g-h*f*e),1-2*(l+g*g));m*=d.Fa;n*=d.Fa;e*=d.Fa;if(1E-6>Math.abs(n-90)||1E-6>Math.abs(n+90))e=0,m=Math.atan2(f,b)*d.Fa,isNaN(m)&&(m=0);b=[];c==d.pa?(b[0]=n,b[1]=m,b[2]=e):c==d.Ha?(b[0]=e,b[1]=n,b[2]=m):c==d.Ya?(b[0]=e,b[1]=m,b[2]=n):c==d.Za?(b[0]=n,b[1]=e,b[2]=m):c==d.Ia?(b[0]=m,b[1]=e,b[2]=n):(b[0]=m,b[1]=n,b[2]=e);return b},zb:function(a,c,b){var f=d.kb(a,c),e=c;0>f&&(e=[-c[0],-c[1],-c[2],-c[3]],f=d.kb(a,e));c=0;if(-1<f)if(1>f){if(c=Math.acos(f),0==c)return e.slice(0,4)}else return e.slice(0,
4);else c=Math.PI;var g=1/Math.sin(c),f=Math.sin((1-b)*c)*g;b=Math.sin(b*c)*g;return[a[0]*f+e[0]*b,a[1]*f+e[1]*b,a[2]*f+e[2]*b,a[3]*f+e[3]*b]},yb:function(a,c,b,f,e){return d.Jc(a,d.Tb(c,b,f,e))},nd:function(a,c){var b=d.Da(a,c);b[0]+=c[0]*a[3];b[1]+=c[1]*a[3];b[2]+=c[2]*a[3];var f=d.Da(b,a),e=a[0]*c[0]+a[1]*c[1]+a[2]*c[2];return[a[0]*e+b[0]*a[3]-f[0],a[1]*e+b[1]*a[3]-f[1],a[2]*e+b[2]*a[3]-f[2],1]},Zb:function(a){var c=[],b=a[1],d=a[2],e=a[4],g=a[6],h=a[8],l=a[9],m=a[0]+a[5]+a[10];0<=m?(a=.5*Math.sqrt(m+
1),m=.25/a,c[0]=(g-l)*m,c[1]=(h-d)*m,c[2]=(b-e)*m,c[3]=a):a[0]>a[5]&&a[0]>a[10]?(a=.5*Math.sqrt(1+a[0]-a[5]-a[10]),m=.25/a,c[0]=a,c[1]=(e+b)*m,c[2]=(d+h)*m,c[3]=(g-l)*m):a[5]>a[10]?(a=.5*Math.sqrt(1+a[5]-a[0]-a[10]),m=.25/a,c[0]=(e+b)*m,c[1]=a,c[2]=(l+g)*m,c[3]=(h-d)*m):(a=.5*Math.sqrt(1+a[10]-a[0]-a[5]),m=.25/a,c[0]=(h+d)*m,c[1]=(l+g)*m,c[2]=a,c[3]=(b-e)*m);return c},jb:function(a){return[a[0],a[1],a[2],a[4],a[5],a[6],a[8],a[9],a[10]]},rb:function(a){return mat4transposeInPlace(a.slice(0,16))},tb:function(a){var c=
a[1];a[1]=a[4];a[4]=c;c=a[2];a[2]=a[8];a[8]=c;c=a[3];a[3]=a[12];a[12]=c;c=a[6];a[6]=a[9];a[9]=c;c=a[7];a[7]=a[13];a[13]=c;c=a[11];a[11]=a[14];a[14]=c;return a},Nb:function(a){if(0==a[1]&&0==a[2]&&0==a[4]&&0==a[6]&&0==a[8]&&0==a[9])return 1==a[0]&&1==a[5]&&1==a[10]?[1,0,0,0,1,0,0,0,1]:0!=a[0]*a[5]*a[10]?[1/a[0],0,0,0,1/a[5],0,0,0,1/a[10]]:[1,0,0,0,1,0,0,0,1];a=[a[0],a[1],a[2],a[4],a[5],a[6],a[8],a[9],a[10]];var c=a[0]*a[4]*a[8]+a[3]*a[7]*a[2]+a[6]*a[1]*a[5]-a[6]*a[4]*a[2]-a[3]*a[1]*a[8]-a[0]*a[7]*
a[5];if(0==c)return[1,0,0,0,1,0,0,0,1];c=1/c;return[(-a[5]*a[7]+a[4]*a[8])*c,(a[5]*a[6]-a[3]*a[8])*c,(-a[4]*a[6]+a[3]*a[7])*c,(a[2]*a[7]-a[1]*a[8])*c,(-a[2]*a[6]+a[0]*a[8])*c,(a[1]*a[6]-a[0]*a[7])*c,(-a[2]*a[4]+a[1]*a[5])*c,(a[2]*a[3]-a[0]*a[5])*c,(-a[1]*a[3]+a[0]*a[4])*c]},Ra:function(a,c,b,d){var e;"undefined"!=typeof b&&"undefined"!=typeof d?(e=c,c=d):(e=c[0],b=c[1],c=c[2]);return[a[0]*e,a[1]*e,a[2]*e,a[3]*e,a[4]*b,a[5]*b,a[6]*b,a[7]*b,a[8]*c,a[9]*c,a[10]*c,a[11]*c,a[12],a[13],a[14],a[15]]},Sa:function(a,
c,b){return"undefined"!=typeof c&&"undefined"!=typeof b?[a,0,0,0,0,c,0,0,0,0,b,0,0,0,0,1]:[a[0],0,0,0,0,a[1],0,0,0,0,a[2],0,0,0,0,1]},Ec:function(a,c,b,d,e){var g;"undefined"!=typeof b&&"undefined"!=typeof d&&"undefined"!=typeof e?(g=c,c=e):(g=c[0],b=c[1],d=c[2],c=c[3]);return[g*a[0]+b*a[4]+d*a[8]+c*a[12],g*a[1]+b*a[5]+d*a[9]+c*a[13],g*a[2]+b*a[6]+d*a[10]+c*a[14],g*a[3]+b*a[7]+d*a[11]+c*a[15]]},yc:function(a,c,b,d){var e;"undefined"!=typeof b&&"undefined"!=typeof d?(e=c,c=d):(e=c[0],b=c[1],c=c[2]);
return[e*a[0]+b*a[3]+c*a[6],e*a[1]+b*a[4]+c*a[7],e*a[2]+b*a[5]+c*a[8]]},Fc:function(a,c,b){var d;"undefined"!=typeof c&&"undefined"!=typeof b?(d=a,a=b):(d=a[0],c=a[1],a=a[2]);return[1,0,0,0,0,1,0,0,0,0,1,0,d,c,a,1]},ob:function(a,c,b,d){var e;"undefined"!=typeof b&&"undefined"!=typeof d?(e=c,c=d):(e=c[0],b=c[1],c=c[2]);return[a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],a[11],a[0]*e+a[4]*b+a[8]*c+a[12],a[1]*e+a[5]*b+a[9]*c+a[13],a[2]*e+a[6]*b+a[10]*c+a[14],a[3]*e+a[7]*b+a[11]*c+a[15]]},
Cc:function(a,c,b,f){a=1/Math.tan((0<=a&&360>a?a:a%360+(0>a?360:0))*d.D);var e;e=1/(b-f);return[a/c,0,0,0,0,a,0,0,0,0,e*(b+f),-1,0,0,e*b*f*2,0]},T:function(a,c,b){b||(b=[0,1,0]);c||(c=[0,0,0]);c=[c[0]-a[0],c[1]-a[1],c[2]-a[2]];var f=d.ad(c);if(1E-6>f)return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];f=1/f;c[0]*=f;c[1]*=f;c[2]*=f;b=d.bd(b);b=d.Da(c,b);d.Ea(b);f=d.Da(b,c);d.Ea(f);c[0]=-c[0];c[1]=-c[1];c[2]=-c[2];return[b[0],f[0],c[0],0,b[1],f[1],c[1],0,b[2],f[2],c[2],0,-d.na(a,b),-d.na(a,f),-d.na(a,c),1]},Pb:function(a,
c,b,d,e,g){var h=1/(c-a),l=1/(d-b),m=1/(g-e);return[2*h,0,0,0,0,2*l,0,0,0,0,-2*m,0,-(a+c)*h,-(d+b)*l,-(e+g)*m,1]},ya:function(a,c,b,f){return d.Cc(d.Ab*Math.atan2(Math.tan((0<=a&&360>a?a:a%360+(0>a?360:0))*d.D),c),c,b,f)},Ac:function(a,c,b,f){return d.Ac(a,c,b,f,-1,1)},ja:function(a,c,b,f,e){return d.Bc(a,c,b,f,-1,1,e)},Bc:function(a,c,b,f,e,g,h){h/=Math.abs(c-a)/Math.abs(f-b);return 1>h?d.Pb(a,c,b/h,f/h,e,g):d.Pb(a*h,c*h,b,f,e,g)},s:function(a,c,b,d,e,g){var h=2*e,l=1/(c-a),m=1/(d-b),n=1/(g-e);return[h*
l,0,0,0,0,h*m,0,0,(a+c)*l,(d+b)*m,-(g+e)*n,-1,0,0,-(h*g)*n,0]},Dc:function(a,c,b,d){var e;"undefined"!=typeof b&&"undefined"!=typeof d?(e=c,c=d):(e=c[0],b=c[1],c=c[2]);a[0]*=e;a[1]*=e;a[2]*=e;a[3]*=e;a[4]*=b;a[5]*=b;a[6]*=b;a[7]*=b;a[8]*=c;a[9]*=c;a[10]*=c;a[11]*=c;return a},Ua:function(a,c){for(var b=[],d=0;16>d;d+=4)for(var e=0;4>e;e++)b[d+e]=c[d]*a[e]+c[d+1]*a[e+4]+c[d+2]*a[e+8]+c[d+3]*a[e+12];return b},Jc:function(a,c){return[a[3]*c[0]+a[0]*c[3]+a[1]*c[2]-a[2]*c[1],a[3]*c[1]+a[1]*c[3]+a[2]*c[0]-
a[0]*c[2],a[3]*c[2]+a[2]*c[3]+a[0]*c[1]-a[1]*c[0],a[3]*c[3]-a[0]*c[0]-a[1]*c[1]-a[2]*c[2]]},za:function(a,c,b,f,e){var g,h;"undefined"!=typeof f&&"undefined"!=typeof e?(g=b,h=f,b=e,e=(0<=c&&360>c?c:c%360+(0>c?360:0))*d.N):"undefined"==typeof b?(g=c[0],h=c[1],b=c[2],e=c[3],e=(0<=e&&360>e?e:e%360+(0>e?360:0))*d.N):(g=b[0],h=b[1],b=b[2],e=(0<=c&&360>c?c:c%360+(0>c?360:0))*d.N);c=Math.cos(e);var l=Math.sin(e);if(1==g&&0==h&&0==b)return[a[0],a[1],a[2],a[3],c*a[4]+a[8]*l,c*a[5]+a[9]*l,c*a[6]+a[10]*l,c*
a[7]+a[11]*l,c*a[8]-l*a[4],c*a[9]-l*a[5],c*a[10]-l*a[6],c*a[11]-l*a[7],a[12],a[13],a[14],a[15]];if(0==g&&1==h&&0==b)return[c*a[0]-l*a[8],c*a[1]-l*a[9],c*a[2]-l*a[10],c*a[3]-l*a[11],a[4],a[5],a[6],a[7],c*a[8]+a[0]*l,c*a[9]+a[1]*l,c*a[10]+a[2]*l,c*a[11]+a[3]*l,a[12],a[13],a[14],a[15]];if(0==g&&0==h&&1==b)return[c*a[0]+a[4]*l,c*a[1]+a[5]*l,c*a[2]+a[6]*l,c*a[3]+a[7]*l,c*a[4]-l*a[0],c*a[5]-l*a[1],c*a[6]-l*a[2],c*a[7]-l*a[3],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15]];if(0==g&&0==h&&0==b)return a.slice(0,
16);e=1/Math.sqrt(g*g+h*h+b*b);g*=e;h*=e;b*=e;var m=h*h;f=1-c;var n=g*h,q=h*b;e=g*l;h=h*l;var r=b*l,l=f*q,t=f*n,w=f*g*b;g=c+f*g*g;n=t+r;q=w-h;m=c+f*m;r=t-r;t=l+e;b=c+f*b*b;c=w+h;e=l-e;return[a[0]*g+a[4]*n+a[8]*q,a[1]*g+a[5]*n+a[9]*q,a[10]*q+a[2]*g+a[6]*n,a[11]*q+a[3]*g+a[7]*n,a[0]*r+a[4]*m+a[8]*t,a[1]*r+a[5]*m+a[9]*t,a[10]*t+a[2]*r+a[6]*m,a[11]*t+a[3]*r+a[7]*m,a[0]*c+a[4]*e+a[8]*b,a[1]*c+a[5]*e+a[9]*b,a[10]*b+a[2]*c+a[6]*e,a[11]*b+a[3]*c+a[7]*e,a[12],a[13],a[14],a[15]]},Qa:function(a,b,k,f){var e;
"undefined"!=typeof k&&"undefined"!=typeof f?(e=b,b=f,f=(0<=a&&360>a?a:a%360+(0>a?360:0))*d.N):"undefined"==typeof b?(e=a[0],k=a[1],b=a[2],f=a[3],f=(0<=f&&360>f?f:f%360+(0>f?360:0))*d.N):(e=b[0],k=b[1],b=b[2],f=(0<=a&&360>a?a:a%360+(0>a?360:0))*d.N);a=Math.cos(f);var g=Math.sin(f);if(1==e&&0==k&&0==b)return[1,0,0,0,0,a,g,0,0,-g,a,0,0,0,0,1];if(0==e&&1==k&&0==b)return[a,0,-g,0,0,1,0,0,g,0,a,0,0,0,0,1];if(0==e&&0==k&&1==b)return[a,g,0,0,-g,a,0,0,0,0,1,0,0,0,0,1];if(0==e&&0==k&&0==b)return[1,0,0,0,0,
1,0,0,0,0,1,0,0,0,0,1];f=1/Math.sqrt(e*e+k*k+b*b);e*=f;k*=f;b*=f;f=e*e;var h=k*k,l=b*b,m=e*b,n=k*b,q=e*g,r=k*g,g=b*g,t=1-a;e=t*e*k;k=t*m;b=t*n;return[a+t*f,e+g,k-r,0,e-g,a+t*h,b+q,0,k+r,b-q,a+t*l,0,0,0,0,1]}};d.kb=d.ed;d.lb=d.Xb;d.Gd=d.gd;d.Fd=d.fd;d.Hd=d.Yb;d.Ed=d.dd;d.Ga=6.283185307179586;d.ld=1.5707963267948966;d.N=.017453292519943295;d.D=.008726646259971648;d.Ab=114.59155902616465;d.Fa=57.29577951308232;d.Ha=0;d.Ya=1;d.Za=2;d.Ia=3;d.pa=4;d.wd=5;d.Id=d.Lc;d.Hc=d.Ic;b.GLMath=d}}
"function"==typeof define&&define.amd?define(["exports"],aa):"object"==typeof exports?aa(exports):aa(this);
function ca(b){function d(a,b,c,d){this.A=b||[0,0,0,1];this.position=a?[a[0],a[1],a[2],1]:[0,0,1,0];this.h=c||[1,1,1,1];this.m=d||[1,1,1]}function a(){this.v=[new d];this.Oc=[.2,.2,.2]}function c(a,b,c,d,e){null!=a&&(a=m.toGLColor(a));null!=b&&(b=m.toGLColor(b));null!=c&&(c=m.toGLColor(c));null!=e&&(e=m.toGLColor(e));this.Va=null==d?0:Math.min(Math.max(0,d),128);this.A=a?a.slice(0,3):[.2,.2,.2];this.h=b?b.slice(0,b.length):[.8,.8,.8,1];this.m=c?c.slice(0,3):[0,0,0];this.M=e?e.slice(0,3):[0,0,0];this.ca=
null}function k(a,b){this.b=[];this.context=m.bb(b);for(var c=0;c<a.b.length;c++){var d=a.b[c];0!=d.c.length&&this.b.push(new f(d,this.context))}}function f(a,b){var c=b.createBuffer(),d=b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,c);b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,d);b.bufferData(b.ARRAY_BUFFER,new Float32Array(a.a),b.STATIC_DRAW);var e=b.UNSIGNED_SHORT;65536<=a.a.length||65536<=a.c.length?(e=b.UNSIGNED_INT,b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint32Array(a.c),b.STATIC_DRAW)):256>=a.a.length&&
256>=a.c.length?(e=b.UNSIGNED_BYTE,b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint8Array(a.c),b.STATIC_DRAW)):b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint16Array(a.c),b.STATIC_DRAW);this.oa=c;this.ga=d;this.Gc=a.a.length/a.C();this.tc=a.c.length;this.type=e;this.format=a.i;this.context=b}function e(a,b,c){if(0>b||0>c)throw Error("width or height negative");this.context=a;this.U=1;this.buffer=a.createFramebuffer();this.X=a.createTexture();this.width=Math.ceil(b);this.height=Math.ceil(c);this.context.activeTexture(this.context.TEXTURE0+
this.U);this.context.bindTexture(this.context.TEXTURE_2D,this.X);this.context.pixelStorei(this.context.UNPACK_FLIP_Y_WEBGL,1);this.context.texImage2D(this.context.TEXTURE_2D,0,this.context.RGBA,this.width,this.height,0,this.context.RGBA,this.context.UNSIGNED_BYTE,null);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_MAG_FILTER,this.context.NEAREST);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_MIN_FILTER,this.context.NEAREST);this.context.texParameteri(this.context.TEXTURE_2D,
this.context.TEXTURE_WRAP_S,this.context.CLAMP_TO_EDGE);this.context.texParameteri(this.context.TEXTURE_2D,this.context.TEXTURE_WRAP_T,this.context.CLAMP_TO_EDGE);this.wa=this.context.createRenderbuffer();b=this.context.getParameter(a.FRAMEBUFFER_BINDING);this.context.bindFramebuffer(a.FRAMEBUFFER,this.buffer);this.context.bindRenderbuffer(a.RENDERBUFFER,this.wa);this.context.renderbufferStorage(a.RENDERBUFFER,a.DEPTH_COMPONENT16,this.width,this.height);this.context.bindFramebuffer(a.FRAMEBUFFER,
b)}function g(b){var c=b;"function"==typeof b.getContext&&(HTMLCanvasElement&&c.constructor==HTMLCanvasElement?c=m.Cd(b):c=m.bb(c));this.context=c;this.Vc=this.xc=!0;this.o=new y(c,this.Db()+da(),this.Db()+ea());this.w=[];this.Cb=g.CCW;this.Ka=0;this.clearColor=[0,0,0,1];this.Oa=null;this.ra=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];this.F=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];this.da=1;this.gc=!0;this.ib=new a;this.width=Math.ceil(1*this.context.canvas.clientWidth);this.height=Math.ceil(1*this.context.canvas.clientHeight);
this.context.canvas.width=this.width;this.context.canvas.height=this.height;this.context.viewport(0,0,this.width,this.height);this.context.enable(c.BLEND);this.context.blendFunc(c.SRC_ALPHA,c.ONE_MINUS_SRC_ALPHA);this.context.enable(this.context.DEPTH_TEST);this.context.depthFunc(this.context.LEQUAL);this.context.disable(this.context.CULL_FACE);this.context.clearDepth(1);this.Gb();this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);this.useProgram(this.o)}function h(){this.w=
[];this.parent=null;this.transform=new Q}function l(a){if(null==a)throw Error("mesh is null");this.Ma=a;this.transform=new Q;this.Aa=new c;this.parent=null}if(!b.jd){window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame,window.requestAnimationFrame||(window.requestAnimationFrame=function(a){window.setTimeout(function(){a(window.performance.now())},17)}));window.performance||(window.performance=
{});window.performance.now||(window.performance.now=function(){return 1E3*(new Date).getTime()-window.performance.ec},window.performance.ec=1E3*(new Date).getTime());var m={renderLoop:function(a){function b(c){window.requestAnimationFrame(b);a(c)}a(window.performance.now());window.requestAnimationFrame(b)},createCanvasElement:function(a,b,c){var d=document.createElement("canvas");a&&a.appendChild(d);if(null==b)d.width=Math.ceil(d.clientWidth)+"";else{if(0>b)throw Error("width negative");d.width=Math.ceil(b)+
""}if(null==c)d.height=Math.ceil(d.clientHeight)+"";else{if(0>c)throw Error("height negative");d.height=Math.ceil(c)+""}return d},createCanvas:function(a,b,c){null==a&&(a=Math.ceil(window.innerWidth));null==b&&(b=Math.ceil(window.innerHeight));return m.createCanvasElement(c,a,b)},get3DOr2DContext:function(a){if(!a||!a.getContext)return null;var b=null,c={antialias:!0,preserveDrawingBuffer:!0};try{b=a.getContext("webgl",c)}catch(d){b=null}if(!b)try{b=a.getContext("experimental-webgl",c)}catch(e){b=
null}if(!b)try{b=a.getContext("moz-webgl",c)}catch(f){b=null}if(!b)try{b=a.getContext("webkit-3d",c)}catch(g){b=null}if(!b)try{b=a.getContext("2d",c)}catch(k){b=null}m.is3DContext(b)&&b.getExtension("OES_element_index_uint");return b},get3DContext:function(a,b){var c=m.get3DOr2DContext(a),d=null;!c&&window.WebGLShader?d="Failed to initialize graphics support required by this page.":window.WebGLShader&&!m.is3DContext(c)?d="This page requires WebGL, but it failed to start. Your computer might not support WebGL.":
c&&m.is3DContext(c)||(d="This page requires a WebGL-supporting browser.");return d?((b||window.alert)(d),null):c},is3DContext:function(a){return a&&"compileShader"in a},getPromiseResults:function(a,b,c){if(!a||0==a.length)return Promise.resolve({Ca:[],xa:[],Wb:[]});for(var d={Ca:[],xa:[],Wb:[]},e=[],f=0;f<a.length;f++){var g=f;e.push(a[f].then(function(a){b&&b(a);d.Ca[g]=a;return!0},function(a){c&&c(a);d.xa[g]=a;return!1}))}return Promise.all(e).then(function(a){for(var b=0;b<d.Ca.length;b++)"undefined"==
typeof d.Ca[b]&&(d.Ca.splice(b,1),--b);for(b=0;b<d.xa.length;b++)"undefined"==typeof d.xa[b]&&(d.xa.splice(b,1),--b);d.Wb=a;return Promise.resolve(d)})},loadFileFromUrl:function(a,b){var c=b||"text";return new Promise(function(b,d){var e=new XMLHttpRequest;e.onreadystatechange=function(e){e=e.target;if(4==e.readyState)if(200<=e.status&&300>e.status){var f=e.response;f||("xml"==c?f=e.responseXML:"json"==c?f=(e.Jd||JSON.parse(e.responseText))+"":"arraybuffer"==c?f=e.response:f=e.responseText+"");b({url:a,
data:f})}else d({url:a})};e.onerror=function(b){d({url:a,error:b})};e.open("get",a,!0);e.responseType=c;e.send()})},f:function(a,b,c){if(null==a.time)return a.time=b,a.Z=b,0;null==a.Z&&(a.Z=b);return 1*(b-a.time)%c/c},s:function(a,b){if(null==a.time)return a.time=b,a.Z=b,0;if(null==a.Z)return a.Z=b,0;var c=b-a.Z;a.Z=b;return 60*c/1E3}};(function(a){function b(){if(!e){var a="aliceblue f0f8ff antiquewhite faebd7 aqua 00ffff aquamarine 7fffd4 azure f0ffff beige f5f5dc bisque ffe4c4 black 000000 blanchedalmond ffebcd blue 0000ff blueviolet 8a2be2 brown a52a2a burlywood deb887 cadetblue 5f9ea0 chartreuse 7fff00 chocolate d2691e coral ff7f50 cornflowerblue 6495ed cornsilk fff8dc crimson dc143c cyan 00ffff darkblue 00008b darkcyan 008b8b darkgoldenrod b8860b darkgray a9a9a9 darkgreen 006400 darkkhaki bdb76b darkmagenta 8b008b darkolivegreen 556b2f darkorange ff8c00 darkorchid 9932cc darkred 8b0000 darksalmon e9967a darkseagreen 8fbc8f darkslateblue 483d8b darkslategray 2f4f4f darkturquoise 00ced1 darkviolet 9400d3 deeppink ff1493 deepskyblue 00bfff dimgray 696969 dodgerblue 1e90ff firebrick b22222 floralwhite fffaf0 forestgreen 228b22 fuchsia ff00ff gainsboro dcdcdc ghostwhite f8f8ff gold ffd700 goldenrod daa520 gray 808080 green 008000 greenyellow adff2f honeydew f0fff0 hotpink ff69b4 indianred cd5c5c indigo 4b0082 ivory fffff0 khaki f0e68c lavender e6e6fa lavenderblush fff0f5 lawngreen 7cfc00 lemonchiffon fffacd lightblue add8e6 lightcoral f08080 lightcyan e0ffff lightgoldenrodyellow fafad2 lightgray d3d3d3 lightgreen 90ee90 lightpink ffb6c1 lightsalmon ffa07a lightseagreen 20b2aa lightskyblue 87cefa lightslategray 778899 lightsteelblue b0c4de lightyellow ffffe0 lime 00ff00 limegreen 32cd32 linen faf0e6 magenta ff00ff maroon 800000 mediumaquamarine 66cdaa mediumblue 0000cd mediumorchid ba55d3 mediumpurple 9370d8 mediumseagreen 3cb371 mediumslateblue 7b68ee mediumspringgreen 00fa9a mediumturquoise 48d1cc mediumvioletred c71585 midnightblue 191970 mintcream f5fffa mistyrose ffe4e1 moccasin ffe4b5 navajowhite ffdead navy 000080 oldlace fdf5e6 olive 808000 olivedrab 6b8e23 orange ffa500 orangered ff4500 orchid da70d6 palegoldenrod eee8aa palegreen 98fb98 paleturquoise afeeee palevioletred d87093 papayawhip ffefd5 peachpuff ffdab9 peru cd853f pink ffc0cb plum dda0dd powderblue b0e0e6 purple 800080 rebeccapurple 663399 red ff0000 rosybrown bc8f8f royalblue 4169e1 saddlebrown 8b4513 salmon fa8072 sandybrown f4a460 seagreen 2e8b57 seashell fff5ee sienna a0522d silver c0c0c0 skyblue 87ceeb slateblue 6a5acd slategray 708090 snow fffafa springgreen 00ff7f steelblue 4682b4 tan d2b48c teal 008080 thistle d8bfd8 tomato ff6347 turquoise 40e0d0 violet ee82ee wheat f5deb3 white ffffff whitesmoke f5f5f5 yellow ffff00 yellowgreen 9acd32".split(" ");
e={};for(var c=0;c<a.length;c+=2)e[a[c]]="#"+a[c+1]}}function c(a){function f(a){var b;return 255*(0>(b=parseFloat(a))?0:100<b?100:b)/100}function g(a){var b;return 255*(0>(b=parseFloat(a))?0:1<b?1:b)}function q(a){var b;return 0>(b=parseInt(a,10))?0:255<b?255:b}function k(){var a=parseFloat(h[1]);if(0>a||360<=a)a=(a%360+360)%360;return a}var h=null;if(!a)return null;var l;if(null!==(h=/^#([A-Fa-f0-9]{2})([A-Fa-f0-9]{2})([A-Fa-f0-9]{2})$/.exec(a)))return[parseInt(h[1],16),parseInt(h[2],16),parseInt(h[3],
16),255];if(null!==(h=/^rgb\(\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*\)$/.exec(a)))return[f(h[1]),f(h[2]),f(h[3]),255];if(null!==(h=/^rgb\(\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*\)$/.exec(a)))return[q(h[1]),q(h[2]),q(h[3]),255];if(null!==(h=/^rgba\(\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?%)\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return[f(h[1]),f(h[2]),f(h[3]),g(h[4])];if(null!==(h=/^rgba\(\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+)\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return[q(h[1]),
q(h[2]),q(h[3]),g(h[4])];if(null!==(h=/^#([A-Fa-f0-9]{1})([A-Fa-f0-9]{1})([A-Fa-f0-9]{1})$/.exec(a))){var m=parseInt(h[1],16);a=parseInt(h[2],16);l=parseInt(h[3],16);return[m+(m<<4),a+(a<<4),l+(l<<4),255]}if(null!==(h=/^hsl\(\s*([\+\-]?\d+(?:\.\d+)?)\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*\)$/.exec(a)))return a=d([k(),f(h[3]),f(h[2])]),[a[0],a[1],a[2],255];if(null!==(h=/^hsla\(\s*([\+\-]?\d+(?:\.\d+)?)\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)%\s*,\s*([\+\-]?\d+(?:\.\d+)?)\s*\)$/.exec(a)))return a=
d([k(),f(h[3]),f(h[2])]),[a[0],a[1],a[2],g(h[4])];b();a=a.toLowerCase();0<=a.indexOf("grey")&&(a=a.replace("grey","gray"));l=e[a];return"string"===typeof l?c(l):"transparent"===a?[0,0,0,0]:null}function d(a){var b=1*a[0],c=1*a[1],e=1*a[2],c=0>c?0:255<c?255:c,e=0>e?0:255<e?255:e;if(0===e)return[c,c,c];a=0;127.5>=c?a=c*(255+e)/255:(a=c*e/255,a=c+e-a);var f=2*c-a;if(0>b||360<=b)b=(b%360+360)%360;var g=b+120;360<=g&&(g-=360);c=60>g?f+(a-f)*g/60:180>g?a:240>g?f+(a-f)*(240-g)/60:f;g=b;e=60>g?f+(a-f)*g/
60:180>g?a:240>g?f+(a-f)*(240-g)/60:f;g=b-120;0>g&&(g+=360);b=60>g?f+(a-f)*g/60:180>g?a:240>g?f+(a-f)*(240-g)/60:f;return[0>c?0:255<c?255:c,0>e?0:255<e?255:e,0>b?0:255<b?255:b]}a.toGLColor=function(a,b,d,e){return null==a?[0,0,0,0]:"string"==typeof a?(a=c(a)||[0,0,0,0],b=1/255,a[0]*=b,a[1]*=b,a[2]*=b,a[3]*=b,a):"number"==typeof a&&"number"==typeof b&&"number"==typeof d?[a,b,d,"number"!=typeof e?1:e]:a.constructor==Array?[a[0]||0,a[1]||0,a[2]||0,"number"!=typeof a[3]?1:a[3]]:a||[0,0,0,0]};var e=null})(m);
m.bb=function(a){return a&&a.getContext?a.getContext():a};m.La=function(a){if(Math.floor(a)!=a||0>=a)return!1;for(;1<a&&0==(a&1);)a>>=1;return 1==a};d.prototype.ba=function(a){null!=a.ambient&&(this.A=m.toGLColor(a.A));if(null!=a.position){var b=a.position;this.position=[b[0],b[1],b[2],null==b[3]?0:b[3]]}null!=a.specular&&(this.m=m.toGLColor(a.m));null!=a.diffuse&&(this.h=m.toGLColor(a.h));return this};a.V=3;a.f=function(a){var b=new d;0!=a&&(b.h=[0,0,0,0],b.m=[0,0,0]);return b};a.prototype.uc=function(b){var c=
this.v.length;this.v[b]||(this.v[b]=a.f(b));if(2<=this.v.length-c)for(;c<this.v.length;c++)this.v[c]||(this.v[c]=a.f(c));return this.v[b]};a.prototype.ba=function(a,b){this.uc(a).ba(b);return this};a.prototype.qb=function(a,b){return this.ba(a,{position:[b[0],b[1],b[2],0]})};c.prototype.va=function(){return(new c(this.A.slice(0,this.A.length),this.h.slice(0,this.h.length),this.m.slice(0,this.m.length),this.Va,this.M.slice(0,this.M.length))).ba({texture:this.ca})};c.prototype.ba=function(a){null!=
a.ambient&&(this.A=m.toGLColor(a.A));null!=a.diffuse&&(this.h=m.toGLColor(a.h));null!=a.specular&&(this.m=m.toGLColor(a.m));null!=a.emission&&(this.M=m.toGLColor(a.M));null!=a.shininess&&(this.Va=a.Va);null!=a.texture&&(a=a.texture,"string"==typeof a?this.ca=new n(a):this.ca=a);return this};c.f=function(a){a=m.toGLColor(a,void 0,void 0,void 0);return new c(a,a)};c.s=function(a){return(new c).ba({texture:a})};var n=function(a){this.I=null;this.$=0;this.u=null;this.name=a;this.width=0;this.ic=!1;this.height=
0};n.G=function(a,b){if(b&&b[a])return Promise.resolve(b[a]);var c=new n(a);b&&(b[a]=c);return c.Lb().then(function(a){return a},function(a){return Promise.reject(a.name)})};n.s=function(a,b,c){if(0>b)throw Error("width less than 0");if(0>c)throw Error("height less than 0");if(a.length<b*c*4)throw Error("array too short for texture");var d=new n("");d.I=a;d.width=Math.ceil(b);d.height=Math.ceil(c);d.$=2;return d};n.f=function(a){return m.Dd(a,"arraybuffer").then(function(a){a=new DataView(a.data);
a.getUint8(0);a.getUint8(1);var b=a.getUint8(2);if(2!=b&&3!=b)return Promise.reject(Error("unsupported image type"));var c=a.getUint16(8,!0),d=a.getUint16(10,!0);if(0!=c||0!=d)return Promise.reject(Error("unsupported origins"));c=a.getUint16(12,!0);d=a.getUint16(14,!0);if(0==c||0==d)return Promise.reject(Error("invalid width or height"));var e=a.getUint8(16);a.getUint8(16);if(!(32==e&&2==b||8==e&&3==b))return Promise.reject(Error("unsupported pixelsize"));var f=c*d,g=new Uint8Array(4*f),q=18,k=0;
if(32==e&&2==b)for(k=b=0;b<f;b++,k+=4)g[k+2]=a.getUint8(q),g[k+1]=a.getUint8(q+1),g[k]=a.getUint8(q+2),g[k+3]=a.getUint8(q+3),q+=4;else if(8==e&&3==b)for(k=b=0;b<f;b++,k+=4)e=a.getUint8(q),g[k]=e,g[k+1]=e,g[k+2]=e,g[k+3]=255,q++;return{width:c,height:d,image:g}})};n.prototype.Lb=function(){if(null!==this.I)return Promise.resolve(this);var a=this,b=this.name;a.$=1;return/\.tga$/i.test(b)?n.f(b).then(function(b){a.I=b.I;a.width=b.width;a.height=b.height;a.$=2;return a},function(c){a.$=-1;return Promise.reject({name:b,
error:c})}):new Promise(function(c,d){var e=new Image;e.onload=function(b){b=b.target;a.I=b;a.width=b.width;a.height=b.height;a.$=2;c(a)};e.onerror=function(c){a.$=-1;d({name:b,error:c})};e.src=b})};n.prototype.S=function(){null==this.u&&(this.u.S(),this.u=null)};k.prototype.getContext=function(){return this.context};k.prototype.eb=function(a){for(var b=0;b<this.b.length;b++)this.b[b].eb(a)};k.prototype.S=function(){for(var a=0;a<this.b.length;a++)this.b[a].S()};f.prototype.S=function(){null!=this.oa&&
this.context.deleteBuffer(this.oa);null!=this.ga&&this.context.deleteBuffer(this.ga);this.ga=this.oa=null};f.prototype.eb=function(a){function b(a,c,d,e,f,g){null!==c&&(a.enableVertexAttribArray(c),a.vertexAttribPointer(c,d,e,!1,f,g))}var c=a.getContext();if(null==this.oa||null==this.ga)throw Error("mesh buffer disposed");if(c!=this.context)throw Error("can't bind mesh: context mismatch");c.bindBuffer(c.ARRAY_BUFFER,this.oa);c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,this.ga);var d=this.format,e=R.C(d),
f=[],g=a.get("position");f.push(g);b(c,g,3,c.FLOAT,4*e,0);var k=R.Sa(d);0<=k?(g=a.get("normal"),f.push(g),b(c,g,3,c.FLOAT,4*e,4*k)):(g=a.get("normal"),null!==g&&c.disableVertexAttribArray(g));k=R.yb(d);0<=k?(T(a,{useColorAttr:1}),g=a.get("colorAttr"),f.push(g),b(c,g,3,c.FLOAT,4*e,4*k)):(T(a,{useColorAttr:0}),g=a.get("colorAttr"),null!==g&&c.disableVertexAttribArray(g));k=R.zb(d);0<=k?(g=a.get("uv"),f.push(g),b(c,g,2,c.FLOAT,4*e,4*k)):(g=a.get("uv"),null!==g&&c.disableVertexAttribArray(g));c=a.getContext();
if(null==this.oa||null==this.ga)throw Error("mesh buffer disposed");if(c!=this.context)throw Error("can't bind mesh: context mismatch");a=c.TRIANGLES;0!=(this.format&R.ya)&&(a=c.LINES);0!=(this.format&R.za)&&(a=c.POINTS);c.drawElements(a,this.tc,this.type,0)};k.prototype.L=function(){for(var a=0,b=0;b<this.b.length;b++)a+=this.b[b].Gc;return a};e.prototype.getContext=function(){return this.context};e.prototype.bind=function(a){if(a.getContext()!=this.context)throw Error("can't bind buffer: context mismatch");
this.context.activeTexture(this.context.TEXTURE0+this.U);this.context.bindFramebuffer(this.context.FRAMEBUFFER,this.buffer);this.context.framebufferTexture2D(this.context.FRAMEBUFFER,this.context.COLOR_ATTACHMENT0,this.context.TEXTURE_2D,this.X,0);this.context.framebufferRenderbuffer(this.context.FRAMEBUFFER,this.context.DEPTH_ATTACHMENT,this.context.RENDERBUFFER,this.wa)};e.prototype.Zc=function(){this.context.framebufferTexture2D(this.context.FRAMEBUFFER,this.context.COLOR_ATTACHMENT0,this.context.TEXTURE_2D,
null,0);this.context.framebufferRenderbuffer(this.context.FRAMEBUFFER,this.context.DEPTH_ATTACHMENT,this.context.RENDERBUFFER,null);this.context.bindFramebuffer(this.context.FRAMEBUFFER,null)};e.prototype.S=function(){null!=this.buffer&&this.context.deleteFramebuffer(this.buffer);null!=this.wa&&this.context.deleteRenderbuffer(this.wa);null!=this.X&&this.context.deleteTexture(this.X);this.X=this.wa=this.buffer=null};g.prototype.getContext=function(){return this.context};g.s=0;g.BACK=1;g.FRONT=2;g.FRONT_AND_BACK=
3;g.CCW=0;g.CW=1;g.prototype.cullFace=function(a){this.Ka=a==g.BACK||a==g.FRONT||a==g.FRONT_AND_BACK?a:0;return this};g.prototype.bc=function(){this.Ka==g.BACK?(this.context.enable(this.context.CULL_FACE),this.context.cullFace(this.context.BACK)):this.Ka==g.FRONT?(this.context.enable(this.context.CULL_FACE),this.context.cullFace(this.context.FRONT)):this.Ka==g.FRONT_AND_BACK?(this.context.enable(this.context.CULL_FACE),this.context.cullFace(this.context.FRONT_AND_BACK)):this.context.disable(this.context.CULL_FACE);
this.Cb==g.CW?this.context.frontFace(this.context.CW):this.context.frontFace(this.context.CCW)};g.prototype.frontFace=function(a){this.Cb=a==g.CW?a:0;return this};g.prototype.Db=function(){var a="";this.xc&&(a+="#define SHADING\n");this.Vc&&(a+="#define SPECULAR\n");return a};g.prototype.$b=function(){(new fa(this.ib)).bind(this.o);this.ta()};g.prototype.useProgram=function(a){if(!a)throw Error("invalid program");a.use();this.o=a;this.$b();return this};g.prototype.Rc=function(a,b){if(0>a||0>b)throw Error("width or height negative");
this.width=Math.ceil(a);this.height=Math.ceil(b);this.context.canvas.width=this.width*this.da;this.context.canvas.height=this.height*this.da;this.context.viewport(0,0,this.width*this.da,this.height*this.da);"undefined"!=typeof this.ia&&this.ia&&(this.ia.S(),this.ia=this.createBuffer(),this.Jb&&this.Jb.Sc(this.ia))};g.prototype.createBuffer=function(){return new e(this.context,this.width,this.height)};g.prototype.vc=function(){return this.ra.slice(0,16)};g.prototype.wc=function(){return this.F.slice(0,
16)};g.prototype.Gb=function(){this.context.clearColor(this.clearColor[0],this.clearColor[1],this.clearColor[2],this.clearColor[3]);return this};g.prototype.Pc=function(a,b,c){this.clearColor=m.toGLColor(a,b,c,1);return this.Gb()};g.prototype.cc=function(){this.ra=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];this.F=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];this.ta()};g.prototype.ta=function(){var a={view:this.F,projection:this.ra,viewMatrix:this.F,projectionMatrix:this.ra};if(null!=this.o.get("viewInvW")){var b=GLMath.zc(this.F);
a.viewInvW=[b[12],b[13],b[14],b[15]]}T(this.o,a)};g.prototype.Tc=function(a){this.ra=GLMath.Mb(a);this.ta()};g.prototype.Uc=function(a){this.F=GLMath.Mb(a);this.ta()};g.prototype.Hb=function(a){this.w.push(a);return this};g.prototype.Ta=function(a){a=new k(a,this.context);return new l(a)};g.prototype.qb=function(a,b,c,d){this.ib.qb(a,b).ba(a,{diffuse:c,specular:d});(new fa(this.ib)).bind(this.o);return this};g.f=function(a){return 1==a[0]&&0==a[1]&&0==a[2]&&0==a[3]&&0==a[4]&&1==a[5]&&0==a[6]&&0==
a[7]&&0==a[8]&&0==a[9]&&1==a[10]&&0==a[11]&&1==a[15]};g.prototype.dc=function(a,b){var c={},d=a.B(),e;null!=b.get("modelViewMatrix")&&(g.f(this.F)?(e=d.slice(0,16),e[13]+=this.F[13],e[14]+=this.F[14],e[15]+=this.F[15]):e=GLMath.Ua(this.F,d),c.modelViewMatrix=e);e=GLMath.Nb(d);c.world=d;c.modelMatrix=d;c.worldViewInvTrans3=e;c.normalMatrix=e;T(b,c)};g.prototype.Mc=function(){if(this.gc){var a=this.context.canvas;a.height==Math.ceil(a.clientHeight)*this.da&&a.width==Math.ceil(a.clientWidth)*this.da||
this.Rc(a.clientWidth,a.clientHeight)}this.bc();if("undefined"!=typeof this.Oa&&this.Oa){var a=this.o,b=this.vc(),c=this.wc();this.ia.bind(this.o);this.Fb();this.ia.Zc();this.useProgram(this.Oa);this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);this.cc();this.$a(this.Jb,this.Oa);this.Tc(b);this.Uc(c);this.useProgram(a)}else this.Fb();this.context.flush()};g.prototype.$a=function(a,b){if(a.constructor==h)for(var c=0;c<a.w.length;c++)this.$a(a.w[c],b);else this.dc(a,b),
ga(a.Aa).bind(b),a.Ma.eb(b)};g.prototype.Fb=function(){this.ta();this.context.clear(this.context.COLOR_BUFFER_BIT|this.context.DEPTH_BUFFER_BIT);for(var a=0;a<this.w.length;a++)this.$a(this.w[a],this.o)};h.prototype.Hb=function(a){a.parent=this;this.w.push(a);return this};h.prototype.Y=function(){return this.transform};h.prototype.B=function(){var a=this.Y(),b=ha(a);if(null!=this.parent){var c=this.parent.B();mat=b?GLMath.Ua(c,a.B()):GLMath.Ob(c)?a.B():c}else mat=a.B();return mat};h.prototype.L=function(){for(var a=
0,b=0;b<this.w.length;b++)a+=this.w[b].L();return a};g.prototype.L=function(){for(var a=0,b=0;b<this.w.length;b++)a+=this.w[b].L();return a};h.prototype.setPosition=function(a,b,c){this.transform.setPosition(a,b,c);return this};h.prototype.la=function(a){this.transform.la(a);return this};h.prototype.Ba=function(a,b,c){this.transform.Ba(a,b,c);return this};l.prototype.L=function(){return this.Ma?this.Ma.L():0};l.prototype.Qc=function(a){this.Aa=c.f(a);return this};l.prototype.Sc=function(a){this.Aa=
a};l.prototype.va=function(){var a=new l(this.Ma);a.Aa=this.Aa.va();a.transform=this.Y().va();return a};l.prototype.Y=function(){return this.transform};l.prototype.Ba=function(a,b,c){this.Y().Ba(a,b,c);return this};l.prototype.setPosition=function(a,b,c){this.Y().setPosition(a,b,c);return this};l.prototype.la=function(a){this.Y().la(a);return this};l.prototype.B=function(){var a=this.Y(),b=ha(a);if(null!=this.parent){var c=this.parent.B();mat=b?c:GLMath.Ob(c)?a.B():GLMath.Ua(c,a.B())}else mat=a.B();
return mat};b.BufferedMesh=k;b.ShapeGroup=h;b.Lights=a;b.FrameBuffer=e;b.LightSource=d;b.Texture=n;b.Material=c;b.Shape=l;b.Scene3D=g;b.GLUtil=m}}"function"===typeof define&&define.amd?define(["exports"],ca):"object"===typeof exports?ca(exports):ca(this);function ia(b){this.g=b;this.Xc=[0,0]}
ia.prototype.bind=function(b){if(!this.g)return this;T(b,{textureSize:this.Xc,mshin:this.g.Va,ma:3==this.g.A.length?this.g.A:[this.g.A[0],this.g.A[1],this.g.A[2]],md:4==this.g.h.length?this.g.h:[this.g.h[0],this.g.h[1],this.g.h[2],4>this.g.h.length?1:this.g.h[3]],ms:3==this.g.m.length?this.g.m:[this.g.m[0],this.g.m[1],this.g.m[2]],me:3==this.g.M.length?this.g.M:[this.g.M[0],this.g.M[1],this.g.M[2]]});this.g.ca&&(new ja(this.g.ca)).bind(b);return this};
function ka(b,d){this.context=d=GLUtil.bb(d);this.U=0;this.u=d.createTexture();d.activeTexture(d.TEXTURE0+this.U);d.pixelStorei(d.UNPACK_FLIP_Y_WEBGL,1);d.bindTexture(d.TEXTURE_2D,this.u);"src"in b.I?d.texImage2D(d.TEXTURE_2D,0,d.RGBA,d.RGBA,d.UNSIGNED_BYTE,b.I):d.texImage2D(d.TEXTURE_2D,0,d.RGBA,b.width,b.height,0,d.RGBA,d.UNSIGNED_BYTE,b.I);GLUtil.La(b.width)&&GLUtil.La(b.height)?d.generateMipmap(d.TEXTURE_2D):(d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR),d.texParameteri(d.TEXTURE_2D,
d.TEXTURE_WRAP_S,d.CLAMP_TO_EDGE),d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,d.CLAMP_TO_EDGE))}ka.prototype.S=function(){this.u&&this.context.deleteTexture(this.u)};function la(b){this.ha=b}
la.prototype.bind=function(b){var d={};d.sampler=this.ha.U;d.textureSize=[this.ha.width,this.ha.height];T(b,d);b=b.getContext();b.activeTexture(b.TEXTURE0+this.ha.U);b.bindTexture(b.TEXTURE_2D,this.ha.X);this.ha.X&&(b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.NEAREST),b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.NEAREST),b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE),b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE))};function ja(b){this.ca=b}
ja.prototype.bind=function(b){var d=this.ca,a=b.getContext();if(null!==d.I&&null===d.u)d.u=new ka(d,a);else if(null===d.I&&null===d.u&&0==d.$){var c=this;d.Lb().then(function(){c.bind(b)});return}if(null!==d.u){var k={};null==d.ea&&(d.ea=a.getExtension("EXT_texture_filter_anisotropic")||a.getExtension("WEBKIT_EXT_texture_filter_anisotropic")||a.getExtension("MOZ_EXT_texture_filter_anisotropic"),null==d.ea?(d.ea={},d.Qb=1):d.Qb=a.getParameter(d.ea.MAX_TEXTURE_MAX_ANISOTROPY_EXT));k.sampler=d.u.U;k.textureSize=
[d.width,d.height];T(b,k);a.activeTexture(a.TEXTURE0+d.u.U);a.bindTexture(a.TEXTURE_2D,d.u.u);"undefined"!=typeof d.ea.TEXTURE_MAX_ANISOTROPY_EXT&&a.texParameteri(a.TEXTURE_2D,d.ea.TEXTURE_MAX_ANISOTROPY_EXT,d.Qb);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);k=a.CLAMP_TO_EDGE;GLUtil.La(d.width)&&GLUtil.La(d.height)?(d.ic||(k=a.REPEAT),a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR_MIPMAP_LINEAR)):a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,
a.TEXTURE_WRAP_S,k);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,k)}};function fa(b){this.v=b}
fa.prototype.bind=function(b){var d=this.v;if(!d||!b)return this;var a={};a.sceneAmbient=d.Oc.slice(0,3);for(var c=0;c<d.v.length;c++){var k=d.v[c];a["lights["+c+"].diffuse"]=[k.h[0],k.h[1],k.h[2],3<k.h.length?k.h[3]:1];a["lights["+c+"].specular"]=[k.m[0],k.m[1],k.m[2],3<k.m.length?k.m[3]:1];a["lights["+c+"].position"]=d.v[c].position}for(c=d.v.length;c<Lights.V;c++)a["lights["+c+"].diffuse"]=[0,0,0,1],a["lights["+c+"].specular"]=[0,0,0,1],a["lights["+c+"].position"]=[0,0,0,0];T(b,a);return this};
function ga(b){if(b){if(b instanceof Material)return new ia(b);if(b instanceof Texture)return new ja(b);if(b instanceof FrameBuffer)return new la(b)}return{bind:function(){}}}function Q(){this.scale=[1,1,1];this.position=[0,0,0];this.rotation=[0,0,0,1];this.P=this.fa=!1;this.O=!0;this.J=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
function ha(b){if(b.P)if(b.fa)b.B();else return 0==b.position[0]&&0==b.position[1]&&0==b.position[2]&&1==b.scale[0]&&1==b.scale[1]&&1==b.scale[2]&&GLMath.Ub(b.rotation);return b.O}Q.prototype.Ba=function(b,d,a){if(this.fa)return this;this.scale=null!=b&&null==d&&null==a?"number"!=typeof b?[b[0],b[1],b[2]]:[b,b,b]:[b,d,a];this.O=this.O&&1==this.scale[0]&&1==this.scale[1]&&1==this.scale[2];this.P=!0;return this};
Q.prototype.setPosition=function(b,d,a){if(this.fa)return this;this.position=null!=b&&null==d&&null==a?"number"!=typeof b?[b[0],b[1],b[2]]:[b,b,b]:[b,d,a];this.O=this.O&&0==this.position[0]&&0==this.position[1]&&0==this.position[2];this.P=!0;return this};Q.prototype.la=function(b){if(this.fa)return this;this.rotation=b.slice(0,4);GLMath.lb(this.rotation);this.P=!0;return this};Q.prototype.setOrientation=function(b,d,a,c){return this.la(GLMath.Tb(b,d,a,c))};
Q.prototype.B=function(){if(this.P)if(this.P=!1,GLMath.Ub(this.rotation))this.J=[this.scale[0],0,0,0,0,this.scale[1],0,0,0,0,this.scale[2],0,this.position[0],this.position[1],this.position[2],1],this.O=0==this.position[0]&&0==this.position[1]&&0==this.position[2]&&1==this.scale[0]&&1==this.scale[1]&&1==this.scale[2];else{this.J=[1,0,0,0,0,1,0,0,0,0,1,0,this.position[0],this.position[1],this.position[2],1];this.J=GLMath.Ua(this.J,GLMath.Kc(this.rotation));GLMath.Dc(this.J,this.scale);var b=this.J;
this.O=1==b[0]&&0==b[1]&&0==b[2]&&0==b[3]&&0==b[4]&&1==b[5]&&0==b[6]&&0==b[7]&&0==b[8]&&0==b[9]&&1==b[10]&&0==b[11]&&0==b[12]&&0==b[13]&&0==b[14]&&1==b[15]}else if(this.O)return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];return this.J.slice(0,16)};Q.prototype.va=function(){var b=new Q;b.scale=this.scale.slice(0,this.scale.length);b.position=this.position.slice(0,this.scale.length);b.fa=this.fa;b.P=this.P;b.J=this.J.slice(0,this.J.length);return b};
function R(b,d,a){this.b=null!=b?[new U(b,d,a)]:[];this.qa=0;this.Na=-1;this.ka=[0,0,0];this.color=[0,0,0];this.Wa=[0,0]}R.Ra=function(b){return b==R.LINES||b==R.rb?R.LINES:b==R.POINTS?R.POINTS:R.TRIANGLES};R.vb=function(b,d){return b==d||R.Ra(b)==R.Ra(d)?!0:!1};R.ob=function(b,d,a,c){for(var k=0;k<b.length;k+=a)if(b[k+3]=0,b[k+3+1]=0,b[k+3+2]=0,!c){var f=[b[k],b[k+1],b[k+2]];d[f]?d[f].push(k+3):d[f]=[k+3]}};
R.jb=function(b,d,a,c){if(!c)for(var k in d){var f=d[k];if(f&&f.constructor==Array&&2<=f.length){var e=f[0];for(c=1;c<f.length;c++)b[e]+=b[f[c]],b[e+1]+=b[f[c]+1],b[e+2]+=b[f[c]+2];for(c=1;c<f.length;c++)b[f[c]]=b[e],b[f[c]+1]=b[e+1],b[f[c]+2]=b[e+2]}}for(c=0;c<b.length;c+=a)if(k=b[c+3],f=b[c+3+1],e=b[c+3+2],d=Math.sqrt(k*k+f*f+e*e))d=1/d,b[c+3]=k*d,b[c+3+1]=f*d,b[c+3+2]=e*d};
R.wb=function(b,d,a,c,k){k=k?1:-1;var f={},e;R.ob(b,f,a,c);for(var g=0;g<d.length;g+=3){var h=d[g]*a,l=d[g+1]*a,m=d[g+2]*a;e=[b[l]-b[m],b[l+1]-b[m+1],b[l+2]-b[m+2]];var n=[b[h]-b[m],b[h+1]-b[m+1],b[h+2]-b[m+2]],q=e[1]*n[2]-e[2]*n[1],r=e[2]*n[0]-e[0]*n[2],n=e[0]*n[1]-e[1]*n[0];e=Math.sqrt(q*q+r*r+n*n);0!=e&&(e=1/e,e*=k,q*=e,r*=e,n*=e,b[h+3]+=q,b[h+3+1]+=r,b[h+3+2]+=n,b[l+3]+=q,b[l+3+1]+=r,b[l+3+2]+=n,b[m+3]+=q,b[m+3+1]+=r,b[m+3+2]+=n)}R.jb(b,f,a,c)};
R.xb=function(b,d,a,c,k){k=k?1:-1;var f={},e;R.ob(b,f,a,c);for(var g=0;g<d.length;g+=2){var h=d[g]*a,l=d[g+1]*a;e=[b[l],b[l+1],b[l+2]];var m=[b[h],b[h+1],b[h+2]],n=e[1]*m[2]-e[2]*m[1],q=e[2]*m[0]-e[0]*m[2],m=e[0]*m[1]-e[1]*m[0];e=Math.sqrt(n*n+q*q+m*m);0!=e&&(e=1/e,e*=k,n*=e,q*=e,m*=e,b[h+3]+=n,b[h+3+1]+=q,b[h+3+2]+=m,b[l+3]+=n,b[l+3+1]+=q,b[l+3+2]+=m)}R.jb(b,f,a,c)};
R.prototype.mode=function(b){if(0>b)throw Error("invalid mode");if(-1!=this.Na&&R.vb(this.Na,b))this.b[this.b.length-1].Rb();else{var d=0,a=R.Ra(b);a==R.LINES?d|=R.ya:a==R.POINTS&&(d|=R.za);this.b.push(new U([],[],d))}this.Na=b;return this};
function ma(b,d){for(var a=b.b[b.b.length-1],c=a?a.i&R.T:0,k=0;k<d.b.length;k++){var f=d.b[k];if(0!=f.c.length)if(!a||(f.i&R.T)!=c||196605<a.a.length+f.a.length||a.i!=f.i)a=new U(f.a.slice(0,f.a.length),f.c.slice(0,f.c.length),f.i),b.b.push(a),c=a.i&R.T;else{var e=a.L(),k=a.c.length;a.a.push.apply(a.a,f.a);for(a.c.push.apply(a.c,f.c);k<a.c.length;k++)a.c[k]+=e}}a.Rb();return b}function W(b,d,a,c){b.ka[0]=d;b.ka[1]=a;b.ka[2]=c;b.qa|=R.f}
R.prototype.transform=function(b){for(var d=0;d<this.b.length;d++)this.b[d].transform(b);return this};function Y(b,d,a){b.Wa[0]=d;b.Wa[1]=a;b.qa|=R.ja}R.prototype.l=function(b,d,a){0==this.b.length&&this.b.push(new U);var c=this.b[this.b.length-1];null!=b&&null==d&&null==a?"number"!=typeof b?c.l(b[0],b[1],b[2],this):c.l(b,b,b,this):c.l(b,d,a,this);return this};R.prototype.mb=function(b,d){for(var a=0;a<this.b.length;a++)(this.b[a].i&R.T)!=R.za&&this.b[a].mb(b,d);return this};
function na(b){for(var d=0;d<b.b.length;d++){var a=b.b[d].C(),c=b.b[d].a,k=R.Sa(b.b[d].i);if(!(0>k))for(d=0;d<c.length;d+=a){var f=c[d+k],e=c[d+k+1],g=c[d+k+2],f=Math.sqrt(f*f+e*e+g*g);0!=f&&(f=1/f,c[d+k]*=f,c[d+k+1]*=f,c[d+k+2]*=f)}}return b}R.prototype.L=function(){for(var b=0,d=0;d<this.b.length;d++)b+=this.b[d].L();return b};
function U(b,d,a){this.a=b||[];this.c=d||[];this.H=0;b=a&R.T;if(0!=b&&b!=R.ya&&b!=R.za)throw Error("invalid format");this.i=null==a?0:a;this.L=function(){return this.a.length/this.C()};this.C=function(){return R.C(this.i)};this.Rb=function(){this.H=this.a.length};this.Eb=function(a){var b=this.i;a=b|a&R.G;if(a!=b){for(var d=this.C(),e=[],g=0;g<this.a.length;g+=d){var h=g+3;e.push(this.a[g],this.a[g+1],this.a[g+2]);if(0!=(a&R.f))if(0!=(b&R.f)){var l=this.a[h],m=this.a[h+1],n=this.a[h+2],h=h+3;e.push(l,
m,n)}else e.push(0,0,0);0!=(a&R.Qa)&&(0!=(b&R.Qa)?(l=this.a[h],m=this.a[h+1],n=this.a[h+2],h+=3,e.push(l,m,n)):e.push(0,0,0));0!=(a&R.ja)&&(0!=(b&R.ja)?e.push(this.a[h],this.a[h+1]):e.push(0,0))}this.a=e;this.i=a}};this.R=function(a,b,d,e,g){var h=d*b,l=e*b,m=g*b,n=0,q=this.a;for(a=a-b;0<=a&&16>n;a-=b,n++){for(var r=7,t=0;t<b&&0!=r;t++)0!=(r&1)&&q[h+t]!=q[a+t]&&(r&=-2),0!=(r&2)&&q[l+t]!=q[a+t]&&(r&=-3),0!=(r&4)&&q[m+t]!=q[a+t]&&(r&=-5);if(0!=(r&1)){d=a/b;h=d*b;break}if(0!=(r&2)){e=a/b;l=e*b;break}if(0!=
(r&4)){g=a/b;m=g*b;break}}q[h]==q[l]&&q[h+1]==q[l+1]&&q[h+2]==q[l+2]||q[h]==q[m]&&q[h+1]==q[m+1]&&q[h+2]==q[m+2]||q[l]==q[m]&&q[l+1]==q[m+1]&&q[l+2]==q[m+2]||this.c.push(d,e,g)};this.l=function(a,b,d,e){var g=e.Na;if(-1==g)throw Error("mode() not called");this.Eb(e.qa);var h=this.a.length;this.a.push(a,b,d);0!=(this.i&R.f)&&this.a.push(e.ka[0],e.ka[1],e.ka[2]);0!=(this.i&R.Qa)&&this.a.push(e.color[0],e.color[1],e.color[2]);0!=(this.i&R.ja)&&this.a.push(e.Wa[0],e.Wa[1]);a=this.C();g==R.ub&&this.a.length-
this.H>=4*a&&0==(this.a.length-this.H)%(2*a)?(g=this.a.length/a-4,this.R(h,a,g,g+1,g+2),this.R(h,a,g+2,g+1,g+3)):g==R.Zb&&0==(this.a.length-this.H)%(4*a)?(g=this.a.length/a-4,this.R(h,a,g,g+1,g+2),this.R(h,a,g,g+2,g+3)):g==R.TRIANGLES&&0==(this.a.length-this.H)%(3*a)?(g=this.a.length/a-3,this.R(h,a,g,g+1,g+2)):g==R.LINES&&0==(this.a.length-this.H)%(2*a)?(g=this.a.length/a-2,this.c.push(g,g+1)):g==R.tb&&this.a.length-this.H>=3*a?(g=this.a.length/a-2,b=this.H/a,this.R(h,a,b,g,g+1)):g==R.rb&&this.a.length-
this.H>=2*a?(g=this.a.length/a-2,this.c.push(g,g+1)):g==R.POINTS?(g=this.a.length/a-1,this.c.push(g)):g==R.s&&this.a.length-this.H>=3*a&&(g=this.a.length/a-3,b=this.H/a,0==(g-b&1)?this.R(h,a,g,g+1,g+2):this.R(h,a,g+1,g,g+2));return this}}
U.prototype.transform=function(b){var d=this.C(),a=this.a,c=!(1==b[0]&&0==b[1]&&0==b[2]&&0==b[4]&&1==b[5]&&0==b[6]&&0==b[8]&&0==b[9]&&1==b[10]),k=R.Sa(this.i),f=null;0<=k&&c&&(f=GLMath.Nb(b));for(var e=0;e<a.length;e+=d){var g=GLMath.Ec(b,a[e],a[e+1],a[e+2],1);a[e]=g[0];a[e+1]=g[1];a[e+2]=g[2];0<=k&&c&&(g=GLMath.yc(f,a[e+k],a[e+k+1],a[e+k+2]),GLMath.Ea(g),a[e+k]=g[0],a[e+k+1]=g[1],a[e+k+2]=g[2])}return this};R.prototype.nb=function(){for(var b=0;b<this.b.length;b++)this.b[b].nb();return this};
U.prototype.nb=function(){if(0!=(this.i&R.T))return this;for(var b=0;b<this.c.length;b+=3){var d=this.c[b+2];this.c[b+2]=this.c[b+1];this.c[b+1]=d}return this};U.prototype.mb=function(b,d){var a=0!=(this.i&R.G&~R.f);this.Eb(R.f);if(a||b)for(var a=[],c=this.C(),k=this.c.length,f=0;f<k;f++){var e=this.c[f];if(a[e]){for(var g=e*c,h=this.a.length/c,l=0;l<c;l++)this.a.push(this.a[g+l]);this.c[f]=h}a[e]=!0}0!=(this.i&R.ya)?R.xb(this.a,this.c,this.C(),b,d):R.wb(this.a,this.c,this.C(),b,d);return this};
R.C=function(b){return[3,6,6,9,5,8,8,11][b&R.G]};R.Sa=function(b){return[-1,3,-1,3,-1,3,-1,3][b&R.G]};R.yb=function(b){return[-1,-1,3,6,-1,-1,3,6][b&R.G]};R.zb=function(b){return[-1,-1,-1,-1,3,6,6,9][b&R.G]};R.G=255;R.T=768;R.f=1;R.Qa=2;R.ja=4;R.ya=256;R.za=512;R.TRIANGLES=4;R.ub=8;R.Zb=7;R.LINES=1;R.tb=6;R.s=5;R.rb=3;R.POINTS=0;this.Mesh=R;"undefined"==typeof Meshes&&(Meshes={});
Meshes.jc=function(){var b,d,a;a=d=b=1;return new R([-b,-d,a,-1,0,0,1,0,-b,d,a,-1,0,0,1,1,-b,d,-a,-1,0,0,0,1,-b,-d,-a,-1,0,0,0,0,b,-d,-a,1,0,0,1,0,b,d,-a,1,0,0,1,1,b,d,a,1,0,0,0,1,b,-d,a,1,0,0,0,0,b,-d,-a,0,-1,0,1,0,b,-d,a,0,-1,0,1,1,-b,-d,a,0,-1,0,0,1,-b,-d,-a,0,-1,0,0,0,b,d,a,0,1,0,1,0,b,d,-a,0,1,0,1,1,-b,d,-a,0,1,0,0,1,-b,d,a,0,1,0,0,0,-b,-d,-a,0,0,-1,1,0,-b,d,-a,0,0,-1,1,1,b,d,-a,0,0,-1,0,1,b,-d,-a,0,0,-1,0,0,b,-d,a,0,0,1,1,0,b,d,a,0,0,1,1,1,-b,d,a,0,0,1,0,1,-b,-d,a,0,0,1,0,0],[0,1,2,0,2,3,4,
5,6,4,6,7,8,9,10,8,10,11,12,13,14,12,14,15,16,17,18,16,18,19,20,21,22,20,22,23],R.f|R.ja)};
Meshes.lc=function(){var b=void 0,d=void 0,a=new R;null==b&&(b=32);null==d&&(d=1);if(2>=b)throw Error("too few slices");if(1>d)throw Error("too few stacks");for(var c=[0,1],k=[0],f=GLMath.Ga,e=1;e<b;e++){var g=1*e/b,h=f*g;c.push(Math.sin(h),Math.cos(h));k.push(g)}c.push(0,1);k.push(1);b*=2;f=0;g=1;for(e=0;e<d;e++){var h=f,l=(e+1)/d,m=2*h,n=2*l,q=g,r=1+0*l,f=l,g=r;a.mode(R.s);Y(a,1,h);W(a,0,1,0);a.l(0,q,m);Y(a,1,l);W(a,0,1,0);a.l(0,r,n);for(var t=2,w=1;t<=b;t+=2,w++){var v=k[w],u,D;u=c[t];D=c[t+1];
Y(a,1-v,h);W(a,1*u,1*D,0);a.l(u*q,D*q,m);Y(a,1-v,l);W(a,1*u,1*D,0);a.l(u*r,D*r,n)}}return a};Meshes.kc=function(){var b=Meshes.lc(),d=Meshes.Ib(!0).nb(),a=Meshes.Ib(void 0);a.transform(GLMath.Fc(0,0,2));return ma(ma(b,d),a)};Meshes.Ib=function(b){return Meshes.mc(b)};
Meshes.mc=function(b){var d=1,a=void 0,c=0,k=2,f=0,e=360,g=new R;null==a&&(a=32);null==k&&(k=1);null==f&&(f=0);null==e&&(e=360);if(2>=a)throw Error("too few slices");if(1>k)throw Error("too few loops");if(c>d)throw Error("inner greater than outer");0>c&&(c=0);0>d&&(d=0);if(0==d||0==e)return g;var h=360==e&&0==f,l=0>e?-1:1;0>e&&(e=-e);e%=360;0==e&&(e=360);var m=[],n=[],q=GLMath.Ga,e=360==e?q:e*GLMath.N,f=f*GLMath.N;0>l&&(e=-e);for(l=0;l<=a;l++){var r=1*l/a,t=1==r&&e==q?f:f+e*r,t=0>t?q- -t%q:t%q;m.push(Math.sin(t),
Math.cos(t));n.push(r)}h&&(m[0]=0,m[1]=1,m[m.length-1]=1,m[m.length-2]=0,n[0]=0,n[n.length-1]=1);a*=2;f=d-c;h=c;b?W(g,0,0,-1):W(g,0,0,1);for(l=0;l<k;l++)if(b=h,n=c+(l+1)/k*f,q=b/d,e=n/d,h=n,r=0==l&&0==c,g.mode(r?R.tb:R.s),r)for(r=a,t=a/2;0<=r;r-=2,t--){var w,v;w=m[r];v=m[r+1];r==a&&(Y(g,.5*(1+w*q),.5*(1+v*q)),g.l(w*b,v*b,0));Y(g,.5*(1+w*e),.5*(1+v*e));g.l(w*n,v*n,0)}else for(t=r=0;r<=a;r+=2,t++)w=m[r],v=m[r+1],Y(g,.5*(1+w*e),.5*(1+v*e)),g.l(w*n,v*n,0),Y(g,.5*(1+w*q),.5*(1+v*q)),g.l(w*b,v*b,0);return g};
Meshes.oc=function(){var b,d,a=new R;null==d&&(d=16);null==b&&(b=16);if(3>d)throw Error("crosswise is less than 3");if(3>b)throw Error("lengthwise is less than 3");for(var c=GLMath.Ga,k=[],f=[],e=0;e<d;e++){var g=e*c/d;k.push(Math.sin(g),Math.cos(g))}k.push(k[0]);k.push(k[1]);for(e=0;e<b;e++)g=e*c/b,f.push(Math.sin(g),Math.cos(g));f.push(f[0]);f.push(f[1]);for(c=0;c<b;c++){var h=c/b,l=(c+1)/b,m=f[2*c],n=f[2*c+1],q=f[2*c+2],r=f[2*c+3];a.mode(R.s);for(e=0;e<=d;e++){var g=e/d,t=k[2*e],w=k[2*e+1],v=w*
(1+.5*r),u=t*(1+.5*r),D=.5*q,E=r*w,I=r*t,A=q;W(a,E,I,A);Y(a,g,l);a.l(v,u,D);v=w*(1+.5*n);u=t*(1+.5*n);D=.5*m;E=n*w;I=n*t;A=m;W(a,E,I,A);Y(a,g,h);a.l(v,u,D)}}return a};
Meshes.Bd=function(b,d,a,c,k){var f=new R;null==b&&(b=1);null==d&&(d=1);null==a&&(a=1);null==c&&(c=1);if(0>b||0>d)throw Error("width or height is less than 0");if(0>=c||0>=a)throw Error("widthDiv or heightDiv is 0 or less");if(0==b||0==d)return f;var e=.5*-b,g=.5*-d;k?W(f,0,0,-1):W(f,0,0,1);for(k=0;k<c;k++){f.mode(R.s);var h=k/c,l=(k+1)/c,m=g+d*h,n=g+d*l;Y(f,0,l);f.l(e,n,0);Y(f,0,h);f.l(e,m,0);for(var q=0;q<a;q++){var r=(q+1)/a,t=e+b*r;Y(f,r,l);f.l(t,n,0);Y(f,r,h);f.l(t,m,0)}}return f};
Meshes.nc=function(){return Meshes.Bb(void 0,0,void 0,void 0,1,void 0,void 0)};Meshes.Ad=function(b,d,a,c,k,f,e){null==c&&(c=8);if(1>c)throw Error("too few stacks");return Meshes.Bb(b,d,a,2*c,k,f,e)};
Meshes.Bb=function(b,d,a,c,k,f,e){function g(a,b,c,d,e,f){W(a,c*b,d*b,e*b);a.l(c,d,e+f)}var h=new R;null==a&&(a=16);null==c&&(c=16);null==k&&(k=1);null==b&&(b=1);null==d&&(d=1);if(2>c)throw Error("too few stacks");if(2>=a)throw Error("too few slices");if(1>k&&0<d)throw Error("too few middle stacks");if(0>d)throw Error("negative length");if(0>b)throw Error("negative radius");if(0==b)return h;for(var l=.5*d,m=c/2,n=e?-1:1,q=[0,1],r=[],t=[],w=[0],v=GLMath.Ga,u=1;u<a;u++){var D=1*u/a,E=v*D;q.push(Math.sin(E),
Math.cos(E));w.push(D)}q.push(0,1);w.push(1);v=2*b;v/=v+d;D=[];for(u=1;u<c;u++){var I=1*u/c,E=Math.PI*I,A=Math.sin(E);r.push(A);D.push(-Math.cos(E));t.push(I)}r.push(0);t.push(1);D.push(1);a=2*a;for(var E=-1,V=I=0,u=0;u<c;u++){var B=D[u],x=t[u],A=b*E,N=b*B,H=u<m?-l:l,K=I,F=b*r[u],O=V,P=x;0<d&&(O=u<m?V*v:1-(1-V)*v,P=u<m?x*v:1-(1-x)*v);E=B;V=x;I=F;u==c-1||0==u?h.mode(R.TRIANGLES):(h.mode(R.s),Y(h,1,O),g(h,n,0,K,A,H),Y(h,1,P),g(h,n,0,F,N,H));for(var M=0,S=0,G=1,B=2,x=1;B<=a;B+=2,x++){var L=w[x],C,J;
u==c-1?(C=M+.5*(L-M),Y(h,1-M,O),g(h,n,S*K,G*K,A,H),Y(h,1-C,P),g(h,n,0,F,N,H),C=q[B],J=q[B+1],Y(h,1-L,O),g(h,n,C*K,J*K,A,H),S=C,G=J,M=L):0==u?(C=M+.5*(L-M),Y(h,1-C,O),g(h,n,0,K,A,H),Y(h,1-M,P),g(h,n,S*F,G*F,N,H),C=q[B],J=q[B+1],Y(h,1-L,P),g(h,n,C*F,J*F,N,H),S=C,G=J,M=L):(C=q[B],J=q[B+1],Y(h,1-L,O),g(h,n,C*K,J*K,A,H),Y(h,1-L,P),g(h,n,C*F,J*F,N,H))}if(u+1==m&&0<d)for(H=.5*v,K=2*l,M=1-H,S=1-v,G=0;G<k;G++){var A=-l+(0==G?0:K*G/k),X=G==k-1?l:-l+K*(G+1)/k,O=H+(0==G?0:S*G/k),P=G==k-1?M:H+S*(G+1)/k;h.mode(R.s);
Y(h,1,O);g(h,n,0,F,N,A);Y(h,1,P);g(h,n,0,F,N,X);B=2;for(x=1;B<=a;B+=2,x++)L=w[x],C=q[B],J=q[B+1],Y(h,1-L,O),g(h,n,C*F,J*F,N,A),Y(h,1-L,P),g(h,n,C*F,J*F,N,X)}}return f?h.mb(f,e):na(h)};this.Meshes=Meshes;
function y(b,d,a){b=b.getContext?b.getContext():b;null==d&&(d=da());null==a&&(a=ea());this.o=d=oa(b,d,a);this.attributes={};this.context=b;this.cb={};this.K={};this.sb={};this.pb={};if(null!=d){this.attributes=[];var c=null;a={};for(var k=b.getProgramParameter(d,b.ACTIVE_ATTRIBUTES),f=0;f<k;++f)if(c=b.getActiveAttrib(d,f),null!==c){var c=c.name,e=b.getAttribLocation(d,c);0<=e&&(this.attributes.push(e),a[c]=e)}k=b.getProgramParameter(d,b.ACTIVE_UNIFORMS);for(f=0;f<k;++f)e=b.getActiveUniform(d,f),null!==
e&&(c=e.name,a[c]=b.getUniformLocation(d,c),this.sb[c]=e.type);this.cb=a}}y.prototype.S=function(){this.o&&this.context.deleteProgram(this.o);this.o=this.context=null;this.cb={};this.attributes={};this.sb={}};y.prototype.getContext=function(){return this.context};y.prototype.get=function(b){b=this.cb[b];return null==b?null:b};
y.prototype.getUniform=function(b){var d="string"==typeof b?this.get(b):b;if(null==d||"number"==typeof d)return null;b=this.K[b];return null==b?this.context.getUniform(this.o,d):b instanceof Array?b.slice(0,b.length):b};y.prototype.use=function(){this.context.useProgram(this.o);T(this,this.pb);this.pb={};return this};function Z(b,d,a,c){null==c&&(c=b.context.getParameter(b.context.CURRENT_PROGRAM)==b.o);c||(b.pb[a]="number"==typeof d?d:d.slice(0,d.length),b.K[a]=null);return c}
function pa(b,d,a,c){c=null;d=d[a];var k=b.get(a);if(null===k)return c;var f=b.K[a];if("number"==typeof d){var e=!1;null==f?(b.K[a]=f=d,e=!0):f!=d&&(f=d,b.K[a]=d,e=!0);if(e)if(b.sb[a]==b.context.FLOAT){if(!(c=Z(b,f,a,c)))return c;b.context.uniform1f(k,f)}else{if(!(c=Z(b,f,a,c)))return c;b.context.uniform1i(k,f)}}else if(3==d.length)if(!f){b.K[a]=f=d.slice(0,d.length);if(!(c=Z(b,f,a,c)))return c;b.context.uniform3fv(k,f)}else{if(f[0]!=d[0]||f[1]!=d[1]||f[2]!=d[2]){f[0]=d[0];f[1]=d[1];f[2]=d[2];if(!(c=
Z(b,f,a,c)))return c;b.context.uniform3fv(k,f)}}else if(2==d.length)if(!f){b.K[a]=f=d.slice(0,d.length);if(!(c=Z(b,f,a,c)))return c;b.context.uniform2fv(k,f)}else{if(f[0]!=d[0]||f[1]!=d[1]){f[0]=d[0];f[1]=d[1];if(!(c=Z(b,f,a,c)))return c;b.context.uniform2fv(k,f)}}else if(4==d.length)if(!f){b.K[a]=f=d.slice(0,d.length);if(!(c=Z(b,f,a,c)))return c;b.context.uniform4fv(k,f)}else{if(f[0]!=d[0]||f[1]!=d[1]||f[2]!=d[2]||f[3]!=d[3]){f[0]=d[0];f[1]=d[1];f[2]=d[2];f[3]=d[3];if(!(c=Z(b,f,a,c)))return c;b.context.uniform4fv(k,
f)}}else if(16==d.length)if(!f){b.K[a]=f=d.slice(0,d.length);if(!(c=Z(b,f,a,c)))return c;b.context.uniformMatrix4fv(k,!1,f)}else{if(qa(d,f,16)){if(!(c=Z(b,f,a,c)))return c;b.context.uniformMatrix4fv(k,!1,f)}}else if(9==d.length)if(!f){b.K[a]=f=d.slice(0,d.length);if(!(c=Z(b,f,a,c)))return c;b.context.uniformMatrix3fv(k,!1,f)}else if(qa(d,f,9)){if(!(c=Z(b,f,a,c)))return c;b.context.uniformMatrix3fv(k,!1,f)}return c}
function T(b,d){var a=null;if("undefined"!==typeof Object.keys)for(var c=Object.keys(d),k=0;k<c.length;k++)var f=c[k],a=pa(b,d,f,a);else for(f in d)a=pa(b,d,f,a)}function qa(b,d,a){for(var c=0;c<a;c++)if(b[c]!=d[c]){d[c]=b[c];for(c+=1;c<a;c++)d[c]=b[c];return!0}return!1}
function oa(b,d,a){function c(a,b,c){var d=a.createShader(b);a.shaderSource(d,c);a.compileShader(d);if(!a.getShaderParameter(d,a.COMPILE_STATUS)){c=c.split("\n");for(var k=0;k<c.length;k++)c[k]="/* "+(k+1)+" */   "+c[k];console.log(c.join("\n"));console.log((b==a.VERTEX_SHADER?"vertex: ":"fragment: ")+a.getShaderInfoLog(d));return null}return d}d=d&&0!=d.length?c(b,b.VERTEX_SHADER,d):null;a=a&&0!=a.length?c(b,b.FRAGMENT_SHADER,a):null;var k=null;null!==d&&null!==a&&(k=b.createProgram(),b.attachShader(k,
d),b.attachShader(k,a),b.linkProgram(k),b.getProgramParameter(k,b.LINK_STATUS)||(console.log("link: "+b.getProgramInfoLog(k)),b.deleteProgram(k),k=null),b.detachShader(k,d),b.detachShader(k,a));null!==d&&b.deleteShader(d);null!==a&&b.deleteShader(a);return k}
function da(){return"attribute vec3 position;\nattribute vec3 normal;\nattribute vec2 uv;\nattribute vec3 colorAttr;\nuniform mat4 world;\nuniform mat4 view;\nuniform mat4 projection;\nvarying vec2 uvVar;\nvarying vec3 colorAttrVar;\n#ifdef SHADING\nuniform mat3 worldViewInvTrans3; /* internal */\nvarying vec4 worldPositionVar;\nvarying vec3 transformedNormalVar;\n#endif\nvoid main(){\nvec4 positionVec4;\npositionVec4.w=1.0;\npositionVec4.xyz=position;\ngl_PointSize=1.0;\ngl_Position=((projection*view)*world)*positionVec4;\ncolorAttrVar=colorAttr;\nuvVar=uv;\n#ifdef SHADING\ntransformedNormalVar=normalize(worldViewInvTrans3*normal);\nworldPositionVar=world*positionVec4;\n#endif\n}"}
function ea(){for(var b="#ifdef GL_ES\n#ifndef GL_FRAGMENT_PRECISION_HIGH\nprecision mediump float;\n#else\nprecision highp float;\n#endif\n#endif\nuniform vec4 md;\n#ifdef SHADING\nstruct light {\n vec4 position; /* source light direction */\n vec4 diffuse; /* source light diffuse color */\n#ifdef SPECULAR\n vec4 specular; /* source light specular color */\n#endif\n};\nconst int MAX_LIGHTS = "+Lights.V+"; /* internal */\nuniform vec3 sceneAmbient;\nuniform light lights[MAX_LIGHTS];\nuniform vec3 ma;\nuniform vec3 me;\n#ifdef SPECULAR\nuniform vec3 ms;\nuniform float mshin;\nuniform vec4 viewInvW;\n#endif\n#endif\nuniform sampler2D sampler;\nuniform vec2 textureSize;\nuniform float useColorAttr;\nvarying vec2 uvVar;\nvarying vec3 colorAttrVar;\n#ifdef SHADING\nvarying vec4 worldPositionVar;\nvarying vec3 transformedNormalVar;\nvec4 calcLightPower(light lt, vec4 vertexPosition){\n vec3 sdir;\n float attenuation;\n if(lt.position.w == 0.0){ /* directional light */\n  sdir=normalize((lt.position).xyz);\n  attenuation=1.0;\n } else { /* point light */\n  vec3 vertexToLight=(lt.position-vertexPosition).xyz;\n  float dist=length(vertexToLight);\n  if(dist==0.0){\n   sdir=vertexToLight;\n   attenuation=1.0;\n  } else {\n   sdir=vertexToLight/dist; /* normalizes vertexToLight */\n   attenuation=(1.0/dist);\n  }\n }\n return vec4(sdir,attenuation);\n}\n#endif\nvoid main(){\n vec4 tmp;\n float useTexture=sign(textureSize.x+textureSize.y);\n tmp.w=1.0;\n tmp.xyz=colorAttrVar;\n vec4 baseColor=mix(mix(\n#ifdef SHADING\n   vec4(1.0,1.0,1.0,md.a), /*when textures are not used*/\n#else\n   md, /*when textures are not used*/\n#endif\n   texture2D(sampler,uvVar), /*when textures are used*/\n   useTexture), tmp, useColorAttr);\n#ifdef SHADING\n#define SET_LIGHTPOWER(i)  lightPower[i]=calcLightPower(lights[i],worldPositionVar)\n#define ADD_DIFFUSE(i)  lightedColor+=vec3(lights[i].diffuse)*max(lightCosines[i],0.0)*lightPower[i].w*materialDiffuse;\nvec4 lightPower["+
Lights.V+"];\nfloat lightCosines["+Lights.V+"];\n",b=b+"if(baseColor.a==0.0)discard;\nvec3 materialAmbient=mix(ma,baseColor.rgb,sign(useColorAttr+useTexture)); /* ambient*/\nvec3 lightedColor=sceneAmbient*materialAmbient; /* ambient*/\n // diffuse\n vec3 materialDiffuse=vec3(md)*baseColor.rgb;\n",d=0;d<Lights.V;d++)b+="SET_LIGHTPOWER("+d+");\n",b+="lightCosines["+d+"]=dot(transformedNormalVar,lightPower["+d+"].xyz);\n";for(d=0;d<Lights.V;d++)b+="ADD_DIFFUSE("+d+");\n";b+="#ifdef SPECULAR\nbool spectmp;\n// specular reflection\nif((ms.x*ms.y*ms.z)!=0.0){\nvec3 viewDirection=normalize((viewInvW-worldPositionVar).xyz);\nfloat specular;\n";
for(d=0;d<Lights.V;d++)b+="  spectmp = lightCosines["+d+"] >= 0.0;\n  if (spectmp) {\n  vec3 lightSpecular=vec3(lights["+d+"].specular);\n    specular=dot (-lightPower["+d+"].xyz - (2.0 * dot (transformedNormalVar, -lightPower["+d+"].xyz)*\n transformedNormalVar), viewDirection);\n    specular=max(specular,0.0);\n    specular=pow(specular,mshin);\n    lightedColor+=ms*specular*lightPower["+d+"].w*lightSpecular;\n  }\n";b+="}\n#endif\n";return b+=" // emission\n lightedColor+=me;\n baseColor=vec4(lightedColor,baseColor.a);\n#endif\n gl_FragColor=baseColor;\n}"}
(function(b){function d(a){a=a||"#ff0000";this.height=this.width=1E3;var b=$("<canvas>").attr("width",this.width+"").attr("height",this.height+"").css({width:"100%",height:"100%",left:"0px",zIndex:-1,top:"0px",position:"fixed"});$("body").append(b);this.Xa=!0;this.count=0;b=b.get(0);this.context=GLUtil.get3DOr2DContext(b);this.Xa=GLUtil.is3DContext(this.context);this.w=[];this.setColor(a)}d.$c=function(a){var b=a[0]-7.5+d.j(15);360<=b?b=360-b:0>b&&(b=360+b);var k=a[1],k=15>=k?d.j(30):240<k?240+d.j(30):
k-15+d.j(30),f=a=a[2],f=15>=f?d.j(30):240<f?240+d.j(30):f+d.j(30);0<a&&0<k&&255>k&&(25>=k&&(k=25),242<=k&&(k=242));return[b,k,f]};d.j=function(a){return Math.random()*a|0};d.Nc=function(a){var b=a[0],d=a[1];a=a[2];var f=b;d>f&&(f=d);a>f&&(f=a);var e=b;d<e&&(e=d);a<e&&(e=a);var g=f+e,h=g/2;if(f===e)return[0,0>h?0:255<h?255:h,0];var e=f-e,g=255*e/(127.5>=h?g:510-g),l=0,l=e/2,l=b===f?(60*(f-a)+l)/e-(60*(f-d)+l)/e:a===f?240+(60*(f-d)+l)/e-(60*(f-b)+l)/e:120+(60*(f-b)+l)/e-(60*(f-a)+l)/e;if(0>l||360<=
l)l=(l%360+360)%360;return[l,0>h?0:255<h?255:h,0>g?0:255<g?255:g]};d.hb=function(a){var b=1*a[0],d=1*a[1],f=1*a[2],d=0>d?0:255<d?255:d,f=0>f?0:255<f?255:f;if(0===f)return[d,d,d];a=0;127.5>=d?a=d*(255+f)/255:(a=d*f/255,a=d+f-a);var e=2*d-a;if(0>b||360<=b)b=(b%360+360)%360;var g=b+120;360<=g&&(g-=360);d=60>g?e+(a-e)*g/60:180>g?a:240>g?e+(a-e)*(240-g)/60:e;g=b;f=60>g?e+(a-e)*g/60:180>g?a:240>g?e+(a-e)*(240-g)/60:e;g=b-120;0>g&&(g+=360);b=60>g?e+(a-e)*g/60:180>g?a:240>g?e+(a-e)*(240-g)/60:e;return[0>
d?0:255<d?255:d,0>f?0:255<f?255:f,0>b?0:255<b?255:b]};d.f=function(a){a="0"+(a|0).toString(16);return a.substring(a.length-2,a.length)};d.gb=function(a){a=d.hb(a);return"#"+d.f(a[0])+d.f(a[1])+d.f(a[2])};d.prototype.start=function(){GLUtil.renderLoop(this.fc.bind(this))};d.prototype.setColor=function(a){a=GLUtil.toGLColor(a);if(!a)throw Error("invalid color parameter");this.color=[255*a[0],255*a[1],255*a[2]];this.Pa=this.constructor.Nc(this.color);this.rc()};d.prototype.rc=function(){document.body.style.backgroundColor=
this.constructor.gb(this.Pa);if(this.Xa){var a=this.constructor.hb(this.Pa);this.aa=(new Scene3D(this.context)).qb(0,[0,0,-1]).Pc(a[0]/255,a[1]/255,a[2]/255);this.pc=this.aa.Ta(Meshes.jc());this.Wc=this.aa.Ta(Meshes.nc());this.Yc=this.aa.Ta(Meshes.oc());this.qc=this.aa.Ta(Meshes.kc())}else this.context.fillStyle=this.constructor.gb(this.Pa),this.context.fillRect(0,0,this.width,this.height)};d.prototype.fc=function(){this.count++;4<=this.count&&(this.count=0,this.sc());this.Xa&&this.aa.Mc()};d.prototype.sc=
function(){var a=this.constructor.$c(this.Pa);if(this.Xa){300<this.w.length&&this.aa.w.shift();var b=this.constructor.j(2E3)/1E3-1,d=this.constructor.j(2E3)/1E3-1,f=this.constructor.j(60)/60,e=[this.pc,this.Wc,this.Yc,this.qc][this.constructor.j(4)],g=(16+this.constructor.j(100))/1E3,a=this.constructor.hb(a);a[0]/=255;a[1]/=255;a[2]/=255;var h=GLMath.Hc(this.constructor.j(360),this.constructor.j(360),this.constructor.j(360)),b=e.va().Ba(g,g,g).la(h).setPosition(b,d,f).Qc(a);this.aa.Hb(b)}else b=[this.constructor.j(this.width+
30)-30,this.constructor.j(this.height+30)-30,32+this.constructor.j(200),32+this.constructor.j(200)],this.context.fillStyle=this.constructor.gb(a),this.context.fillRect(b[0],b[1],b[2],b[3])};d.colorBackground=function(a){$(document).ready(function(){(new d(a)).start()})};b.CanvasBackground=d})(this);
